tmfg/mmtis-national-access-point

database/src/main/resources/db/migration/V1_1__.sql, docs/esimerkit/taxi-geojson-example.json, docs/esimerkit/taxi-geojson-example.md
Update database tables to support pricing and additional services.
=> NAP-48 Example json for taxi services.

ote/resources/public/index.html, ote/src/cljc/ote/localization.cljc, ote/src/cljs/ote/app/place_search.cljs, ote/src/cljs/ote/tiedot/olennaiset_tiedot.cljs
**Set baseurl and user relative URLs**
=> Use relative URLs

.gitignore, nap/docker/ckan-plugin-watcher.cljs, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/header.html
When user is logged in to CKAN, show a link to OTE application in the header navigation links.
=> NAP-110 Add link to OTE for logged in users

database/devdb_migrate.sh, database/devdb_testdata.sh, database/src/main/resources/db/migration/V1_2__places.sql, docs/geometry-data.md, ote/project.clj, ote/resources/public/css/omat_tyylit.css, ote/resources/public/language/fi.edn, ote/src/clj/ote/main.clj, ote/src/clj/ote/palvelut/transport.clj, ote/src/clj/ote/services/places.clj, ote/src/clj/ote/services/places.sql, ote/src/cljc/ote/db/places.cljc, ote/src/cljc/ote/geo.cljc, ote/src/cljs/ote/app/controller/passenger_transportation.cljs, ote/src/cljs/ote/app/controller/place_search.cljs, ote/src/cljs/ote/app/place_search.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/leaflet.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/place_search.cljs
Select operation area by autocompleting from Finnish municipality data. The selected municipalities are shown on the map.
=> NAP-114 Operation area selection

ote/resources/public/css/omat_tyylit.css, ote/resources/public/language/fi.edn, ote/src/cljs/ote/app/state.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/transport_service.cljs
Some of the accessibility and mobility related translations will need more work.
=> NAP-154 Fix used terms from front page and from service page.

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/plugin.py, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/edit_base.html, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/read.html, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/package/read_base.html, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/package/search.html, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/user/dashboard_datasets.html
=> CKAN changes for ote integration

ote/resources/public/language/fi.edn
If you agree that this can be merged. Go ahead and merge :)
=> NAP-200 Finnish terms fixed

ote/resources/public/css/omat_tyylit.css, ote/resources/public/language/fi.edn, ote/src/cljs/ote/app/controller/passenger_transportation.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/napit.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/place_search.cljs
Added select-field to main header and named it as user-menu.
Slightly changed the way how our main buttons are styled.
Changed slightly map placement on the passenger transportation form.
=> NAP-192 Passenger transportation form ui tuning. Header ui tuning.

database/src/main/resources/db/migration/V1_10__add_missing_subtypes.sql, ote/resources/public/language/fi.edn, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/napit.cljs, ote/src/cljs/ote/ui/validation.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/terminal.cljs
Add required indication to terminal and passenger transport forms
=> Nap 209 indicate required fields

ote/resources/public/language/fi.edn, ote/src/cljs/ote/app/controller/brokerage.cljs, ote/src/cljs/ote/app/controller/front_page.cljs, ote/src/cljs/ote/app/controller/parking.cljs, ote/src/cljs/ote/app/controller/passenger_transportation.cljs, ote/src/cljs/ote/app/controller/rental.cljs, ote/src/cljs/ote/app/controller/terminal.cljs, ote/src/cljs/ote/app/controller/transport_operator.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/buttons.cljs, ote/src/cljs/ote/views/brokerage.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/place_search.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_operator.cljs
All texts are moved to translations file.
napit and napit/tallenna are translated to buttons buttons/save.
=> NAP-212 ensure translations

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/edit.html, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/snippets/transport_operator_edit.html, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/snippets/transport_operator_view.html, ote/src/cljs/ote/app/controller/ckan_org_editor.cljs, ote/src/cljs/ote/app/controller/ckan_org_viewer.cljs, ote/src/cljs/ote/app/controller/transport_operator.cljs, ote/src/cljs/ote/main.cljs, ote/src/cljs/ote/views/ckan_org_editor.cljs, ote/src/cljs/ote/views/ckan_org_viewer.cljs
Integrates OTE organisation info form into CKAN organisation edit view.
=> NAP-177 Use ote org form in ckan

database/src/main/resources/db/migration/V1_12__operation_area_geojson.sql, ote/src/clj/ote/services/places.clj, ote/src/clj/ote/services/places.sql, ote/src/clj/ote/services/transport.clj, ote/src/cljc/ote/db/transport_service.cljc, ote/src/cljs/ote/app/controller/place_search.cljs, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/views/front_page.cljs
**Add view that contains GeoJSON formatted location**
**Fetch/store operation area**
=> NAP-173 Fetch/store operation area properly when editing

database/src/main/resources/db/migration/V1_13__service_hour_exceptions.sql, database/testdata-ote.sql, ote/resources/public/language/fi.edn, ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/integration/export/transform.clj, ote/src/cljc/ote/db/transport_service.cljc, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs
See: https://www.pivotaltracker.com/n/projects/2126022/stories/152601155
**Add service hour exceptions**
**Transform service exception dates to ISO-8601**
**Add service exception localization keys**
**Add service exception type**
**Add formatting based on a protocol to fetch date fields**
**Add service exceptions**
**Add date picker form field type**
=> 152601155 Add service hour exceptions

ote/src/cljs/ote/ui/validation.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/place_search.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
https://www.pivotaltracker.com/story/show/152634769
**Always allow draft save**
**Allow specifying a function that checks emptiness**
**Make place search required**
**Move external interfaces after operation area**
**Add required notice, if places missing**
=> 152634769 Operation area required and above external interfaces

database/devdb_testdata.sh, database/src/main/resources/db/migration/V1_15__finnish_regions.sql
**Add finnish regions table**
Add finnish regions table and change places view to include results from that table.
=> 152601213 Finnish regions

database/devdb_testdata.sh, database/src/main/resources/db/migration/V1_16__countries.sql
Add countries table and return results from it in the places view.
=> 152795370 Add countries as possible places

ote/resources/public/css/omat_tyylit.css, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/topnav.cljs, ote/src/cljs/ote/views/main.cljs
Move header styling to stylefy. Refactor top-nav-links to use links defined as data.
=> 152797121 Header fixes

database/src/main/resources/db/migration/V1_17__companies.sql, ote/resources/public/language/fi.edn, ote/src/cljc/ote/db/transport_service.cljc, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
**Add companies to transport service.**
**Add companies to form**
**Move companies before operation area**
**Add db definition and service level key**
**Improve messages**
=> 152841074 Add companies to transport service.

ote/resources/public/language/fi.edn, ote/src/cljs/ote/views/service_search.cljs
**Improve search result view**
=> 152892931 Improve search result view

database/src/main/resources/db/migration/V1_18__external_interface_metadata.sql, ote/resources/public/language/fi.edn, ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/nap/publish.clj, ote/src/clj/ote/services/service_search.clj, ote/src/clj/ote/services/service_search.sql, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
Add license and description URL for external interfaces
=> 152918271 Metadata for external interfaces

database/src/main/resources/db/migration/V1_21__pricing_link.sql, database/testdata-ote.sql, ote/resources/public/language/fi.edn, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/test/clj/ote/services/transport_test.clj
=> 152919146 Add pricing service link

ote/resources/public/language/fi.edn, ote/src/cljs/ote/style/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
**Improve search result card UI**
=> 152919076 Improve search result card UI

ote/src/cljs/ote/app/controller/service_search.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/service_search.cljs
**Prevent default navigation to avoid polluting history**
**Make external interface title a real link (fix history)**
=> 153088926 Navigation history fixes

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/fanstatic/napote_theme.css
Some CSS tuning to get a more matching look with OTE header style.
=> 153096514 - CKAN header CSS style fine-tuning to match OTE style.

ote/src/cljs/ote/app/controller/front_page.cljs
**Handle failure in transport operator fetch**
=> 153208799 Handle failure in transport operator fetch

ote/resources/public/language/fi.edn, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/app/controller/front_page.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/theme.cljs
Change dropdown list to checkboxes
=> Add assistance information for terminal form.

database/src/main/resources/db/migration/V1_26__brokerage_flag.sql, ote/resources/public/language/fi.edn, ote/src/clj/ote/services/service_search.sql, ote/src/cljc/ote/db/transport_service.cljc, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs, ote/test/clj/ote/services/transport_test.clj
**Add companies group to all passenger transportation sub types**
**Add brokerage? flag to all transport services**
**Add brokerage? as service level key**
**Add single checkbox field type**
**Add brokerage to companies group**
**Improve form info styling (use common help component)**
**Add brokerage to test**
**Remove brokerage selection when creating a service**
=> 153249364 Brokerage and companies to all passenger transportation

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/form.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs
Move payment types to price class group
Update/upgrade the way how form fields handles classes, width and style
=> Remove currency from price class

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/place_search.cljs
**Add help text to operation area**
=> 153257698 Add help text to operation area

ote/resources/public/language/fi.edn, ote/src/clj/ote/nap/users.clj, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/app/state.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/transport_service.cljs
Fix issue in localized text `rows` attribute that caused Edge to scroll.
Refactored the routes that lead to transport service edit forms.
=> 153130316 Fix IE Edge scroll issue

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/front_page.cljs, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/main.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/ckan_org_editor.cljs, ote/src/cljs/ote/views/ckan_org_viewer.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/theme.cljs, ote/src/cljs/ote/views/transport_service.cljs
Add `onbeforeunload` handler and internal navigation dialog to prevent user from accidentally leaving a form that has modified data.
=> 152962772 Confirm when leaving a modified form

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/ckan_service_viewer.cljs
Added translations for new fields
=> 153282945 More translations for GeoJSON viewer

ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/transport_service.cljs
**Keep parsed and incomplete text in local state**
Update text representation only if the actual parsed value changes.
**Load service data if id of editing service changes**
=> 153312582 Fix :number field state

database/src/main/resources/db/migration/V1_34__service_description.sql, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
**Add new service description localized text**
**Add description to all forms**
Use common name group
=> 153554423 Service description text

ote/src/clj/ote/services/service_search.sql
=> 153593342 Service catalog shows unpublished services

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
**Add help to availability dates**
=> 152841650 Add help to availability dates

ote/src/clj/ote/authorization.clj, ote/src/clj/ote/nap/ckan.clj, ote/src/clj/ote/services/transport.clj
Nyt organisaation title muuttuu ckanissa, kun tietoja päivittää ote puolella.
Samalla korjasin sen, että organisaatioita ilmestyi useampia tietokantaan.
=> 153097454 update ckan org

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/transport.clj, ote/src/clj/ote/services/transport.sql, ote/src/cljs/ote/views/transport_operator.cljs
**Add transport operator description**
=> 153773045 Add transport operator description

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/footer.html, ote/src/cljs/ote/views/main.cljs
Fixed footer links
Fixed header active class
=> Open ckan footer links in new tab (secured)

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/integration/export/geojson.clj, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/service_search.cljs
Translate some missing words
Remove operator id from ckan service json view 
Change sub-type that didn't work to type in search result cards
=> Several bug fixes

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/plugin.py
=> 153241912 Unohdin_salasanani_antaa_SMTPDataErrorin

ote/resources/public/language/sv.edn
**Add new Swedish translations**
=> 153815844 Add new Swedish translations

ote/src/cljs/ote/app/controller/ckan_service_viewer.cljs, ote/src/cljs/ote/app/controller/service_search.cljs, ote/src/cljs/ote/style/service_viewer.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/theme.cljs
**Make dialogs a little wider**
**Don't do anything in viewer start if not in CKAN**
**Open GeoJSON viewer directly without going to CKAN**
**Add stylefy styles for service viewer**
**Add close button**
**Fix reactive derefs**
=> 153843248 Show GeoJSON in OTE

ote/src/cljs/ote/style/base.cljs
Make error snackbar wider so the "anna palautetta palvelusta" button will fit
=> Make error snackbar wider

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/transport_service_common.cljs
**Add notice card if missing required fields for publication**
=> 153872539 Add notice card if missing required fields for publication

ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/validation.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
**Pass raw error data as well**
**Nested validation of :table type**
Validate all rows of a table with the table field schema
**Make external interface description, url and format required**
**Show missing required fields in tables**
**Make table row taller if it has errors**
**Add required? fields to tables**
=> 153988215 Missing required fields and validations for tables

ote/resources/public/css/bootstrap_style_grid.css, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/form_fields.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/validation.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
Added bootstrap style to tables - helps mobile users
Added warning and error texts to localized text areas
Updated localized text areas ui a bit.
=> 154014860 required text in localized text area

ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/validation.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
Fix 24h allday checkbox to add nil values when checkbox is checked off
Add "tieto vaaditaan" text to dropdowns even after value is removed
=> Fix dropdowns warning/error indication

ote/project.clj, ote/src/cljc/ote/db/transport_service.cljc
Upgrade specql, fixes a parsing error when a composite special character was in a quoted value.
**Upgrade specql**
**Remove unneeded work arounds**
=> 154031077 Upgrade specql

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/footer.html, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/home/layout1.html, ote/src/cljs/ote/style/form_fields.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
Changes to footer liikennevirasto.fi/nap link
=> New test server warning text

ote/src/cljs/ote/ui/common.cljs
**Fix IE issues**
Use "top" property and window instead of document scroll listener.
=> 154018937 take 2: Fix IE issues

ote/project.clj, ote/src/clj/ote/services/index.clj, ote/src/clj/ote/tools/git.clj, ote/src/clj/ote/tools/postbuild.clj
**Buildtime tools to get git revision and rename JS file**
**Determina JS location by buildtime git SHA**
**Add postbuild action**
=> 154237443 Use unique JS name based on git revision SHA

ote/src/clj/ote/nap/publish.clj, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/ui/form_fields.cljs
Second try for deleting external resources. UI changes removed.
=> 154215241 empty row should not be removed

ote/src/clj/ote/main.clj
**Add daily rolling file appender to logging**
=> 154205786 Add daily rolling file appender to logging

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
Implemented features:
https://www.pivotaltracker.com/story/show/154170724
https://www.pivotaltracker.com/story/show/153871172
=> 154170724 pricing info text

aws/ansible/templates/ote/config.edn.j2, ote/config.edn, ote/project.clj, ote/src/clj/ote/main.clj
**Configure logging level**
Add slf4j timbre so that Java libraries that use slf4j will log
through timbre and respect the same logging configuration.
**Set stg/prod log level to INFO**
=> 154205786 Logging improvements, take 2

ote/src/cljs/ote/style/form_fields.cljs
**Move language selection links to left**
=> 154124869 Move language selection links to left

ote/resources/public/language/fi.edn
New header text for brokerage section
=> 154327436 New header text

.circleci/Dockerfile, .circleci/README.md, .circleci/build-docker-image.sh, .circleci/config.yml, database/circleci_setup.sh
* Added a custom circleci Docker image
* Using a new cache version for circleci jobs
* Production builds and db dumps are now deployed into a S3 bucket
=> 154390128 pr test instances

aws/ansible/jenkins/jobs/changelog.groovy, tools/changelog/project.clj, tools/changelog/src/ote/tools/changelog.clj
- Add tool to generate changelog html
- Add Jenkins job to run changelog tool daily
=> 154471181 Add tool to generate changelog html

.gitignore, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/base.html, ote/config.edn, ote/src/clj/ote/services/index.clj
* Google Analytics trackers for OTE and CKAN indexes.
=> 153170774 palvelun käytön analysointi

database/src/main/resources/db/migration/V1_48__rental_pickup.sql, ote/src/cljs/ote/app/controller/transport_service.cljs
- Save name of pick-up locations
- Save pick-up locations time schedule exceptions
- Added pick-up location specific name field
=> 154586331 rentals pickup location save

ote/config.edn, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/index.clj, ote/src/cljs/ote/app/controller/flags.cljs, ote/src/cljs/ote/views/main.cljs
- Add ote-login flag to config.edn
- Add flag controller that can be used to check if feature is shown in production
- Add check to login feature whether or not to show it in production
=>  154625968 Enable feature flags

ote/src/cljs/ote/app/controller/place_search.cljs
- Improved place search, added 500ms search delay as in other search fields
=> 154761361 Delay place search 500ms

ote/resources/public/language/sv.edn
* Translation improvements for #277
=> SV translation improvements.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
- Added translated texts to rental geojson view.
=> Rental location type fix.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljc/ote/localization.cljc, ote/src/cljs/ote/views/service_search.cljs
- Support pluralization in message definitions
=> 154833682 Support pluralization in OTE localization messages

ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/services/places.clj, ote/src/cljc/ote/time.cljc, ote/test/clj/ote/integration/export/geojson_test.clj, ote/test/clj/ote/test.clj
- Fix error when exporting GeoJSON that has an interval type
=> 154867768 Fix GeoJSON interval type encoder

docs/api/README.md, ote/src/clj/ote/components/http.clj, ote/src/clj/ote/services/service_search.clj
- Support JSON output in service search backend calls
- Add developer documentation
=> 154832365 Service search API

ote/src/clj/ote/services/admin.clj, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
- New service search list for admin users
- Let admin to open service but don't let them edit.
=> 15439774 Add search service list to admin panel

database/src/main/resources/db/migration/V1_54__parking_pricing.sql, ote/test/clj/ote/db/service_generators.clj
- Add missing pricing attribute to parking info
=> 154914702 Add missing pricing attribue to parking info

ote/project.clj
=> 154915112 Upgrade specql dependency

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* Fixed
- GeoJson view localization update for maximum parking time and availability time
=> 154392247 translate geojson texts

cypress/integration/main_spec.js, ote/src/clj/ote/services/login.clj, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/main.cljs
- Fix user data returned by OTE login dialog
- Allow login by pressing Enter key
- Add e2e test for login dialog
=> 154956609 Login dialog e2e test and minor fixes

ote/src/clj/ote/components/http.clj, ote/test/clj/ote/test.clj
- Specify UTF-8 charset in JSON response
=> 154960666 Add charset to JSON Content-Type header

ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/operators.cljs
- Add grey background for operators view
- Fix operators view header h3 -> h1
- Change p element to span to fix item headers padding
=> 154434208 finalize ote organizations view

ote/src/clj/ote/services/service_search.clj, ote/test/clj/ote/services/service_search_test.clj
- Operator search no longer returns deleted companies
=> 155025306 Operator search returns deleted companies

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/footer.html, ote/src/cljs/ote/views/main.cljs
- Developers info link in footer
=> 154954719 Add developers link to footer

ote/resources/public/language/en.edn
=> 155031015 English translations

.gitignore, tools/dashboard/jenkins.edn, tools/dashboard/project.clj, tools/dashboard/resources/public/index.html, tools/dashboard/src/clj/dashboard/data/finap_services.clj, tools/dashboard/src/clj/dashboard/data/jenkins.clj, tools/dashboard/src/clj/dashboard/main.clj, tools/dashboard/src/cljs/dashboard/events.cljs, tools/dashboard/src/cljs/dashboard/main.cljs, tools/dashboard/src/cljs/dashboard/view.cljs
A simple React app and backend for running on the raspberry pi radiator machine.
Currently looks like:
- Added a simple radiator dashboard
=> 154802195 Radiator dashboard

ote/src/clj/ote/integration/export/transform.clj, ote/src/cljc/ote/db/transport_service.cljc, ote/test/clj/ote/integration/export/geojson_test.clj
- Week days in GeoJSON are now sorted (monday first)
=> 154868930 Sort week days in GeoJSON

database/src/main/resources/db/migration/V1_55__collate.sql
- Change collation of operator/service name (for better result ordering)
=> 154872430 Migration to alter collation of transport operator/service name

ote/src/cljs/ote/views/transport_operator.cljs
- Add regex check to operator gsm input field
=> Add regex to operator gsm input field

ote/src/clj/ote/integration/export/transform.clj, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/test/clj/ote/integration/export/geojson_test.clj
- Maximum stay is now formatted as ISO-8601 period in exported GeoJSON
=> 155062911 Export maximum-stay as ISO-8601 period in GeoJSON

database/src/main/resources/db/migration/V1_57__add_cascade_delete.sql
- Fix delete service 
- Add cascade delete to service_company.transport-service-id -> transport-service.id foreign key
=> 155213704 Add cascade delete to table service_company

database/src/main/resources/db/migration/V1_59__lower_case_operation_area.sql, ote/src/clj/ote/services/service_search.clj
- API search for operation area to case insensitive
=> API search Capitalization for operation area

tools/dashboard/pivotal.edn, tools/dashboard/project.clj, tools/dashboard/src/clj/dashboard/data/pivotal.clj, tools/dashboard/src/clj/dashboard/main.clj, tools/dashboard/src/cljs/dashboard/view.cljs
- Added information from Pivotal to radiator dashboard
=> 155225047 Add Pivotal information to radiator dashboard

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/service_search.clj, ote/src/cljs/ote/style/service_search.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/service_search.cljs
=> 153924765 service search new result card

database/src/main/resources/db/migration/V1_60__company_stats.sql, ote/project.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/admin.sql, ote/src/clj/ote/services/transport.clj, ote/src/clj/ote/tasks/company.clj, ote/src/clj/ote/tasks/company.sql, ote/test/clj/ote/tasks/company_test.clj, ote/test/clj/ote/test.clj
- Company list CSV URLs are automatically updated in the background
- Store daily statistics about company count to database
=> 155057529 Update company CSV in the background

ote/src/clj/ote/services/external.clj
- CSV parsing tries to detect separator
- CSV parsing trims values before validation
=> 155355570 CSV robustness improvements

database/src/main/resources/db/migration/V1_61__company_sources.sql, ote/project.clj, ote/resources/public/css/styles.css, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/external.clj, ote/src/clj/ote/services/transport.clj, ote/src/cljc/ote/db/transport_service.cljc, ote/src/cljc/ote/util/csv.cljc, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/transport_service_common.cljs, ote/test/clj/ote/tasks/company_test.clj
- CSV import
- UI tuned company group
- Added brokerage group
- Added company-source to transport-service table
=> 154239984 csv import and new company group ui

ote/project.clj
=> 155430430 Upgrade specql

database/src/main/resources/db/migration/V1_63__add_csv_file_name.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/services/external.clj, ote/src/cljc/ote/util/csv.cljc, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/ui/form_fields.cljs
- Uploaded csv filename
- Allow semicolon ; as column separator in csv file
- Add company-csv-filename to transport-service table
=> 154239984 add csv filename

database/src/main/resources/db/migration/V1_64__external_interfaces_format.sql, ote/project.clj, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/nap/publish.clj, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/mui_chip_input.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/transport_service_common.cljs, ote/test/clj/ote/db/generators.clj
* Added autocomplete and chip-input form fields.
* External interface form group changes:
* Using autocomplete field type for license field. Added some license suggestions.
* Using chip-input field type for format field. Added some response file format suggestions.
* Format attribute/column is now type of TEXT[].
=> 154918168 ulkoisten rajapintojen formaatti  ja lisenssi kenttien uudistaminen

ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/app/controller/operators.cljs, ote/src/cljs/ote/views/admin.cljs
- Clear search string from service search page when operator services are selected from operator list page.
- Add source (service/operator) to admins business-id report.
=> 155321423 clear search parameter

ote/project.clj, ote/src/clj/ote/services/external.clj
- Use clj-http client instead of httpkit client to fetch CSV files
=> 155433652 Fix let's encrypt client certificate problem

ote/resources/public/language/en.edn
=> Localization fixes

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/transport_service_common.cljs
- Fix brokerage section header text
=> 154389816 Add correct header text to brokerage section

ote/src/clj/ote/services/localization.clj
- Add route to change service language
=> 155249108 Add route to change service language 

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/footer.html, ote/src/cljs/ote/views/main.cljs
=> 155062047 Enable english

ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/views/admin.cljs
- Add gsm number to business id report
- Fix service and operator source to business-id report
=> 155248860 Add gsm number to business-id report

cypress/integration/naughty_spec.js, cypress/integration/own-services_spec.js, cypress/integration/smoke/ote_spec.js, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/places.clj, ote/src/clj/ote/services/places.sql, ote/src/cljs/ote/app/controller/place_search.cljs, ote/src/cljs/ote/views/place_search.cljs, ote/test/clj/ote/db/generators.clj, ote/test/clj/ote/integration/export/geojson_test.clj
- Primary and secondary operation area.
=> 152962937 Add secondary operation area.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
- Renamed Creative Commons license names
=> 155695737 Licence renaming

ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/place_search.cljs
- Clear place search input field when place is selected
=> 155808160 Clear search

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
- Removed AGPL from external interface license list.
=> 155533490 Remove AGPL license.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn
- Operation area english translation fix
=> 152962937 Operation area english translation fix

database/src/main/resources/db/migration/V1_67__route_traffic.sql, ote/src/cljc/ote/db/transit.cljc
- Added database types and tables for route transit data
=> 155616070 Add route traffic data model

ote/src/cljs/ote/app/controller/place_search.cljs
- Operation area drawing feature is linked to primary area.
=> 155815646 - Use primary operation area for drawing.

ote/resources/public/css/balloon.css
- Operation area header tooltips do not hide behind map anymore.
=> 155815646 - Bring tooltip text box front. 

ote/resources/public/css/styles.css
- Fix paragraphs in external interface modal
by removing margins only from the first p element.
Toni, did I do well?
=> 155062911 Fix paragraphs in external interface modal

ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/app/controller/route.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/service_calendar.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/service_calendar.cljs
- Rules for specifying dates a service is provided
=> 155616293 Rule-based date selection for service route service

ote/config.edn, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/routes.clj, ote/src/cljs/ote/app/controller/route/route-list.cljs, ote/src/cljs/ote/app/controller/transport_operator.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/route/route_list.cljs, ote/src/cljs/ote/views/transport_operator.cljs, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
- Hard coded page to list sea routes
=> 155616147 sea routes

ote/project.clj, ote/src/clj/ote/services/routes.clj, ote/src/cljc/ote/db/transit.cljc, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/views/route/basic_info.cljs, ote/src/cljs/ote/views/route/route_list.cljs
- Route list now fetches real data from database
- Added more fields to route basic info
=> 155897101 Fetch routes from database

ote/src/cljs/ote/app/controller/route.cljs, ote/src/cljs/ote/style/route.cljs, ote/src/cljs/ote/views/route.cljs
- Cancel button to sea route wizard
- Links to wizard steps to make it more usable when editing route
=> 155933397 add cancel and links to route view

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/place_search.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/place_search.cljs
- Hide operation drawing tools by default.
- Let user select drawing tools for primary and secondary operation areas.
=> 155847048 operation area drawing

ote/src/cljs/ote/views/service_search.cljs
- Add url as external interfaces link text if data-content is missing
=> 155941595 Add url as text when data-content is missing

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/base.html, ote/config.edn
* New GA tracking code (LiVi administrated).
=> 154956589 Change GA tracking code.

ote/src/cljs/ote/app/controller/route.cljs, ote/src/cljs/ote/style/route.cljs, ote/src/cljs/ote/views/route/route_list.cljs, ote/src/cljs/ote/views/route/trips.cljs
- Pick up and drop off exceptions
=> 155616209 stop exceptions

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljc/ote/db/transport_service.cljc
- Removed unnecessary accessibility fields.
=> 154843167- Removed unnecessary accessibility fields. Includes also changes to ticket #154843264.

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/emails/invite_user.txt, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/emails/reset_password.txt
- Add 3-language password reset email template
- Add 3-language user invite email
=> 154586747 Multi language email templates

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/header.html, ote/src/cljs/ote/views/main.cljs
* Removed Dashboard (Yhteenveto) link from header menus.
=> 155396075 Remove dashboard link from header menus

ote/resources/public/language/sv.edn
- Translated finnish texts to swedish
=> 155619534 - Remove finnish text from swedish accessibility text.

ote/src/clj/ote/main.clj, ote/src/clj/ote/services/login.sql
- OTE login form also supports username
=> 156039797 Support username in OTE login

ote/src/cljs/ote/views/route/stop_sequence.cljs, ote/src/cljs/ote/views/route/trips.cljs
- Round trips are allowed routes.
=> 155935823 Allow round trips.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/route/trips.cljs
- Adding a new trip is now allowed only after an user has defined a calendar schedule for the first trip.
=> 155971785 copy calendar

ote/resources/public/language/sv.edn
* Add Swedish translations to operator page
=> Add Swedish translations to transport operator page

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/transport_service_common.cljs
* Add one missing new text to external interfaces info
* Translate new sea route texts
=> 156156626 Add one new text to external interfaces info

ote/src/cljs/ote/app/controller/route.cljs, ote/src/cljs/ote/app/controller/route/route-list.cljs, ote/src/cljs/ote/views/route.cljs
- Keep selected operator in route list and route creation views.
=> 155967816 Keep selected operator in route list and route creation views.

ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/ui/service_calendar.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/basic_info.cljs, ote/src/cljs/ote/views/route/service_calendar.cljs, ote/src/cljs/ote/views/route/stop_sequence.cljs, ote/src/cljs/ote/views/route/trips.cljs
* First pr when changing sea route editor to one page form
=> 156334549 change wizard to form

database/src/main/resources/db/migration/V1_73__update_taxi_service_transport_type.sql
- Update existing taxi service data to use new transport type road.
=> 154389778 - Update existing taxi service data to use transport type road.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/route/service_calendar.cljs, ote/src/cljs/ote/views/route/stop_sequence.cljs, ote/src/cljs/ote/views/route/trips.cljs
- Tooltips for sea route icon buttons
- Styling improvements to sea route form
=> 156262985 Sea route UX improvements

ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/views/route/trips.cljs
- Adding custom stop to stop sequence works
=> 156461984 Fix adding custom stop

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljc/ote/util/collections.cljc, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/views/route/trips.cljs
- Possibility to delete trip from trip listing
=> 156035399 Delete trip functionality

ote/src/cljs/ote/style/form_fields.cljs
* Fix localized-text element in table-td by overwriting word-wrap by pre-wrap
=> 156080833 pre wrap 

ote/src/cljs/ote/app/controller/route/route_list.cljs, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/views/route/basic_info.cljs
* Inform user that there is unsaved changes in sea route form if trying to leave the page without saving.
=> 156035127 inform cancel and exit

ote/src/cljs/ote/ui/form_fields.cljs
- Date picker respects the selected language
=> 153593652 Set locale for date picker

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/views/route.cljs
* Make name as mandatory field
* Clear "you have unsaved changes" dialog when "cancel" button is pressed
* Fix translation
=> 156338179 make route name mandatory for draft

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/route/service_calendar.cljs
- Trip service calendar is now in a dialog
=> 156461755 Service calendar dialog

ote/src/clj/ote/integration/export/gtfs.clj, ote/src/clj/ote/services/routes.clj, ote/src/cljc/ote/db/transit.cljc, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/route/trips.cljs
- Stop times greater than 24h work and can be stored
=> 156564188 Stop times to/from 24h

ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/route/trips.cljs
* Trips port name use smaller font size (16->14)
* Force trip list header texts and arrows to be in the same row even if names are long.
* sv translations
=> 156461568 improve trip list

ote/src/cljs/ote/views/route/stop_sequence.cljs
- Sea route: Empty strings not allowed for custom stop name.
=> 156567484 - Empty strings not allowed for custom stop name.

database/src/main/resources/db/migration/V1_75__transit_pre_notice.sql
- Tables for 60 days pre notice
=> Add transit pre notice datamodel

ote/config.edn, ote/project.clj, ote/src/clj/ote/authorization.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/pre_notices.clj, ote/src/cljc/ote/db/transit.cljc
- Backend service for upload/download attachments
=> 156611950 Pre notice attachments in S3

ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/route/service_calendar.cljs, ote/src/cljs/ote/views/route/trips.cljs
* Better validations to trip calendars.
=> 156567661 more calendar validation

ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/views/route/trips.cljs
* Hide route trips help box only when the first calendar is valid.
=> 156495547 Fix route trips help box visibility issue

cypress/integration/route_spec.js, cypress/integration/smoke/ote_spec.js
* Fix problems in Cypress se route tests
=> Fix cypress route tests.

ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/route/route_list.cljs
* New swedish translations
* Remove id from route list, Make gtfs input field a bit bigger.
=> 156529708 remove ids from searoutelist

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/views/pre_notices/listing.cljs
* Show some relevant information on prenotices listing page.
* Prenotice modify event. (Not actually modifying yet, just opening the prenotice create form page.)
=> 156688462 Pre-notice list view

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/authorization.clj, ote/src/clj/ote/nap/users.clj, ote/src/clj/ote/nap/users.sql, ote/src/clj/ote/services/pre_notices.clj, ote/src/clj/ote/services/pre_notices/authority.clj, ote/src/cljc/ote/db/transit.cljc, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
- Pre noticy listing for transit authority users
=> 156533232 pre notice listing for transit authority

database/src/main/resources/db/migration/V1_77__pre_notice_comments.sql, database/testdata-ckan.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/pre_notices/authority.clj, ote/src/cljc/ote/db/auditlog.cljc, ote/src/cljc/ote/db/common.cljc, ote/src/cljc/ote/db/operation_area.cljc, ote/src/cljc/ote/db/places.cljc, ote/src/cljc/ote/db/service_search.cljc, ote/src/cljc/ote/db/specql_db.clj, ote/src/cljc/ote/db/transit.cljc, ote/src/cljc/ote/db/transport_operator.cljc, ote/src/cljc/ote/db/transport_service.cljc, ote/src/cljc/ote/db/user.cljc, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/style/pre_notice.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
- Pre notice listing and detail view for transit authority users
=> 156724662 Authority pre notice view

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/leaflet_draw.cljs
* Fixed custom port delete by ensuring that js object receives element that tells what is the id that is used in clojurescript.
=> 156794271 deleting port from map doesnt work

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/leaflet.cljs, ote/src/cljs/ote/ui/leaflet_draw.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/place_search.cljs, ote/src/cljs/ote/views/route/stop_sequence.cljs
* Take zoom button translations into use in sea route map.
=> 156872006 translate zoom buttons

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/buttons.cljs, ote/src/cljs/ote/ui/list_header.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/route_list.cljs
* Link to sea route editor user guide
=> 156794815 help link button

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* Changed effective date description input field to autocomplete field.
=> 156871433 effective date description input to autocomplete

cypress/integration/route_spec.js, cypress/integration/smoke/ote_spec.js, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/route/service_calendar.cljs
* Changed Merireitti word to Laivareitti
* Changed word ajopäivät to kulkupäivät
* Changed muoto to formaatti
* Added new info text to trip calendar to help users to create better calendars.
=> 156835217 small fixes

ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/views/route/service_calendar.cljs
* Cancel button to trip calendar
=> 156836777 cancel changes

ote/src/cljs/ote/ui/form_fields.cljs
=>  156952821 Fix file input tooltip visibility issue in pre-notice form

aws/ansible/templates/ote/config.edn.j2, ote/config.edn, ote/src/clj/ote/components/http.clj, ote/src/clj/ote/main.clj
- Add SSL upgrade to OTE backend (no need for separate nginx installation)
=> 156468030 Add SSL upgrade listener

ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/integration/export/geojson.sql, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/service_search.cljs
- GeoJSON export adds style information base on primary status
=> 157044180 Add styling to GeoJSON geometry

ote/resources/public/css/styles.css, ote/src/cljs/ote/style/form_fields.cljs, ote/src/cljs/ote/ui/form_fields.cljs
* Converted upload button css styles to stylefy styles.
=> Move upload-button css styles tyo style.form-fields

aws/ansible/templates/ote/config.edn.j2, ote/config.edn
=> 157111594 Increase max body

ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/app/routes.cljs
- Show pre notice by direct link
=> 157118940 Show pre notice route

ote/src/cljs/ote/ui/leaflet.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
- Pre notice map now zooms to selected regions
=> 157118244 Zoom pre notice map to regions

database/src/main/resources/db/migration/V1_80__lock.sql, ote/src/clj/ote/db/lock.clj, ote/src/clj/ote/db/lock.sql, ote/src/clj/ote/db/transaction_lock.sql, ote/src/clj/ote/db/tx.clj, ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/tasks/pre_notices.sql
- pre notice email sending now use a cluster wide lock to prevent both nodes from sending
=> 157147308 Use a locking table for cluster wide locks

aws/ansible/templates/ote/config.edn.j2, ote/config.edn, ote/src/clj/ote/main.clj, ote/src/clj/ote/tasks/company.clj, ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/tasks/pre_notices.sql, ote/src/clj/ote/tasks/util.clj, ote/test/clj/ote/services/operators_test.clj
- 1st scheduled task time was skipped if restarting before it
=> 157247809 Fix scheduled task time bug

ote/src/cljs/ote/views/pre_notices/listing.cljs
- Removed id field from pre notice listing table
=> 157111344 Remove id from pre notices listing

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/plugin.py, nap/docker/nginx/proxy.conf
=> 156885013 Allow user autocomplete API calls through

ote/resources/public/language/fi.edn
- Better Finnish term for sea routes
=> 157110907 Change finnish term for sea routes

ote/src/clj/ote/services/pre_notices/operator.clj
- Also delete attachments when deleting draft pre notice
=> 157111425 Delete pre notice attachments

ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/views/main.cljs
* Redirect own services page after register or login.
=> 157110829 Change redirect after register and login

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* Hint text for effective dates description autocomplete field.
* Effective date and regions related fields are now mandatory.
=> 157246548 Change pre-notices field to mandatory, add hint text.

ote/test/clj/ote/db/service_generators.clj, ote/test/clj/ote/services/pre_notice_test.clj
* Added more unit tests for pre notices
=> Add unit tests for pre-notice

ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/views/admin.cljs
- Admin business id report now has transport-operator id column
=> 157393564 Add operator id to business id report

database/src/main/resources/db/migration/V1_82__gtfs.sql, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/import/stop_times.sql, ote/src/clj/ote/tasks/gtfs.clj, ote/src/cljc/ote/db/gtfs.cljc, ote/src/cljc/ote/gtfs/parse.cljc, ote/src/cljc/ote/gtfs/spec.cljc, ote/src/cljc/ote/util/zip.cljc
- GTFS import now saves all the data
=> 157311328 Improved GTFS import

ote/src/cljs/ote/app/controller/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
* Take chip-input into use in service search sub-type
=> 156871396 chip

database/src/main/resources/db/migration/R__GTFS_query.sql, database/src/main/resources/db/migration/V1_84__gtfs_date_hash.sql, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/import/stop_times.sql, ote/src/cljc/ote/gtfs/parse.cljc, ote/test/clj/ote/db/migration_file_test.clj
- GTFS import: the "shape" of traffic per day is calculated and stored as a hash
- Added "gtfs-date-hash" table which stores per day hash
=> 157274612 Add per date hashes to GTFS package import

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* SV translations for 60days change pre notice
=> sv translations

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/import/kalkati.clj, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/tasks/gtfs.sql
- Kalkati.net external interfaces are imported as GTFS
=> 157424697 Import Kalkati as GTFS via kalkati-to-gtfs lambda

ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/tasks/pre_notices.sql
* Added pre-notice description into pre-notice email.
* Changed ordering and styling of the pre-notice email columns.
=> 157508240 Pre-notices email improvements

ote/src/clj/ote/services/routes.clj, ote/src/cljc/ote/db/transit.cljc, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/route/service_calendar.cljs
- Use date-fields maps (not Date objects) in transit route calendars
=> 157692001 Fix Date object timezone problems

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/integration/export/csv.clj, ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/service_search.sql, ote/src/cljs/ote/app/controller/ckan_service_viewer.cljs, ote/src/cljs/ote/style/service_viewer.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/service_search.cljs
* Involved companies can be exported as csv
=> 157420838 show business id list

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/src/clj/ote/services/places.clj, ote/src/clj/ote/services/places.sql, ote/src/cljs/ote/app/controller/place_search.cljs
*  Sort operation area places search results in following alphabetical order finnish-region, finnish-municipality, finnish-postal, country, continent
=> Sort operation area search results 

ote/src/clj/ote/services/service_search.clj, ote/src/clj/ote/services/service_search.sql, ote/src/cljs/ote/app/controller/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
* Added transport type option to search service page
=> 157656007 transport type

ote/src/cljs/ote/app/controller/operators.cljs, ote/src/cljs/ote/views/operators.cljs
* Changed result-chip map values to make operator appear as search option in service search page
=> Fix operator selection from operator list

aws/ansible/environments/staging/group_vars/ote/vars, ote/src/clj/ote/tasks/gtfs.clj
- GTFS import only runs during night hours
- Enable GTFS import in staging
=> 157654510 Enable GTFS import at night

ote/src/clj/ote/nap/users.sql, ote/src/clj/ote/services/admin.clj, ote/src/cljs/ote/views/admin.cljs
* Added transport operator id and title into admin panel user search results.
* Fixed some minor style issues in the admin panel user search tab.
=> 157420440 Add better service provider listing in admin panel user search results

cypress/integration/pre-notice_spec.js, ote/project.clj, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/views/pre_notices/listing.cljs
- Region geometry is loaded when editing a pre-notice
=> 157547079 Load region geojson when editing pre-notice

ote/src/cljs/ote/views/service_search.cljs
* Capitalize operation area texts in search page
=> 157687729 Capitalize operation-area in search result page

database/src/main/resources/db/migration/V1_91__gtfs_error.sql, ote/src/clj/ote/tasks/gtfs.clj
- GTFS import error handling now logs error to db
=> 157834650 Store GTFS import error to database

ote/src/cljs/ote/app/controller/front_page.cljs, ote/src/cljs/ote/views/main.cljs
* Log in dialog don't appear anymore after register
=> 157621199 Fix login dialog issue after register

ote/src/cljc/ote/db/transit.cljc, ote/src/cljc/ote/gtfs/transform.cljc
* Fix broken date-time conversions during GTFS export.
=> 157773988 Fix problems in gtfs date type conversions during export.

ote/src/cljs/ote/ui/leaflet.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/place_search.cljs
* Add MML data and MIT licence text.
=> 157420623 Add MML data and MIT licence text.

ote/src/cljs/ote/views/main.cljs
* A new link for the privacy policy.
=> 156947330 Add a new link for privacy policy in the footer.

aws/ansible/environments/production/group_vars/ote/vars, aws/ansible/environments/staging/group_vars/ote/vars, aws/ansible/templates/ote/config.edn.j2, ote/config.edn, ote/src/clj/ote/tasks/gtfs.clj
- Prevent gtfs updates and downloads for listed operators
=> 157654432 Prevent gtfs updates and downloads for listed operators

ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/route_list.cljs
* Use a more generic link for sea route user guid pdf
=> 157116577 Use a more generic link for sea route user guid pdf

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* More info added for service providing companies
=> 157081534 Add info text for service providing companies.

database/src/main/resources/db/migration/R__GTFS_query.sql, ote/src/clj/ote/components/service.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_changes.sql, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/app/controller/common.cljs, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/app/controller/transit_changes.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/transit_changes.cljs
- Transit changes view that lists upcoming changes in transit services
=> 157654517 Transit changes view

docs/geometry-data.md
- Add documentation for country data
=> 157964553 Document country geometry data

aws/ansible/environments/production/group_vars/ote/vars, aws/ansible/environments/staging/group_vars/ote/vars, aws/ansible/templates/ote/config.edn.j2, ote/src/clj/ote/tasks/gtfs.clj
=> Enable gtfs import in production

aws/ansible/environments/production/group_vars/ote/vars, aws/ansible/environments/staging/group_vars/ote/vars, aws/ansible/templates/ote/config.edn.j2, ote/config.edn, ote/src/clj/ote/components/service.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/robots.clj
- robots.txt to exclude crawlers in test environment
=> 157874968 Add robots.txt path

ote/project.clj, ote/src/cljs/ote/ui/service_calendar_timeline.cljs
* Refactor transit timeline visualization code. Get rid of core.async dependency.
* Fixed some issue related to dragging of service calendar timeline.
=> Refactoring and fixes for service-calendar-timeline

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Stop sequences with times are shown in transit visualization
=> Show stop sequences for selected route

ote/project.clj, ote/src/clj/ote/components/http.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/nap/cookie.clj, ote/src/clj/ote/nap/users.clj, ote/src/clj/ote/services/index.clj, ote/src/cljs/ote/main.cljs
- Pass user info in index page (faster load time)
=> 158069459 Pass user-info to unauthenticated routes

ote/src/clj/ote/nap/users.sql, ote/src/clj/ote/services/pre_notices/authority.clj, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
- Button to open transit authority user listing dialog
=> 157242189 Transit authority users dialog

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/transport_service.cljs
- License information box to service form
=> 157421434 Add license information to form

database/src/main/resources/db/migration/V1_95__fix_companies_service_search.sql
- Fix "empty arrays" bug in service catalog
=> 157653034 Fix "cannot accumulate empty arrays" error in VIEW

ote/src/cljs/ote/app/routes.cljs
* Require login for transit-visualization and transit-changes routes.
=> 158103376 - Require login for transit-changes and transit-visualization routes.

database/src/main/resources/db/migration/V1_96__fix_companies.sql, ote/src/clj/ote/services/service_search.clj
- Service catalog companies companies fix
=> 157653034 Fix service catalog companies

ote/src/cljs/ote/main.cljs, ote/src/cljs/ote/style/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
* New amazing stylings for search page
=> 157656151 fine tuning

ote/src/clj/ote/services/service_search.sql
* Show only published services in the search results. This should also fix the wrong search result count value in the service catalog.
=> 158139429 - Prevent non-published services appearing in the search results

nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/plugin.py
* Hide user/activity/<id> and user/<id> routes in ckan.
=> 158138065 - Hide user/activity and user/<id> routes in ckan.

ote/src/clj/ote/services/transit_changes.sql, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/transit_changes.cljs
* Add days to next different week count column.
* Add service name that is proposing the change.
* Improve wording of the changes column.
=> 158103934 - Transit changes view improvements

ote/resources/public/favicon/browserconfig.xml, ote/resources/public/favicon/manifest.json, ote/src/clj/ote/components/http.clj, ote/src/clj/ote/nap/users.clj, ote/src/clj/ote/services/index.clj
- Fixed user info caching problem
=> 158142210 Fix caching problems

database/src/main/resources/db/migration/V1_97__transit_changes_view.sql, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_changes.sql, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/tasks/gtfs.sql
- New background task to determine upcoming transit changes nightly
=> 158104803 Determine transit changes every night

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/route/route_list.cljs
- Force creation of transport operator before being allowed to go to new route form
=> 158246843 Force operator creation before route

ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/tasks/gtfs.sql
* Operator blacklist for external interfaces
=> 157654432 Operator blacklist for external interfaces

ote/src/cljs/ote/views/service_search.cljs
=> 158290726 Add missing geojson link

ote/project.clj, ote/src/clj/ote/integration/export/geojson.clj, ote/test/clj/ote/integration/export/geojson_test.clj
- Endpoint to fetch up to date GeoJSON json-schema
=> 155279676 Add GeoJSON schema endpoint

database/src/main/resources/db/migration/V1_99__refresh_changes_procedure.sql, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/tasks/gtfs.sql
- nightly update of transit changes access rights
=> 158317993 Use sproc to update view because OTE is not the owner

ote/src/cljs/ote/views/transit_changes.cljs
* Make transit-changes table style more interactive.
=> 158322369 - Improve transit-changes table style.

ote/src/cljs/ote/app/controller/route/route_wizard.cljs
- Don't allow new route form if no operator
=> 158246843 Prevent new route form if no operator

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/footer.cljs, ote/src/cljs/ote/views/front_page.cljs
* Remove register button when user is logged in
* Added link to eu
=> 158383332 register eu link

ote/src/cljs/ote/views/admin/interfaces.cljs
* Changes in admin interface list.
* Combine import error, db error and show interface texts to one column.
* Show different error modal title according to error type.
* Add interface url to list.
=> 158323452 Combine admin interface list errors to one column in ui

database/src/main/resources/db/migration/V1_100__gtfs_day_changes.sql
* Detailed change information in nightly transit changes database view
=> 158382894 Add detailed change information to nightly transit changes

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/views/admin/interfaces.cljs
* Added url as a new filter to admin interface list
=> 158322556 interface url as a filter

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* Optional allowed file format vector. It only adds a text to ui. Doesn't affect to back end.
=> 158178789 pre notice file formats

ote/resources/public/css/styles.css, ote/src/cljs/ote/style/topnav.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/main.cljs
* Header size now changes when scrolling down the page.
* Header is now fixed in the viewport.
=> 158394433 fixed header

cypress/integration/main_spec.js
- Use typeRaw in cypress test login
=> 158453129 Use typeRaw in login

ote/src/cljs/ote/views/main.cljs
- Fixed inconsistent window scroll position when navigating
=> 154765111 Scroll window to top whenever page changes

ote/src/cljs/ote/style/front_page.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/front_page.cljs
=> Fp small ui tuning

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/views/front_page.cljs
* Fix delete attachment by changing define-event path
=> 158425715 Fix delete attachment 

ote/src/cljc/ote/util/text.cljc, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/admin/interfaces.cljs, ote/src/cljs/ote/views/operators.cljs, ote/src/cljs/ote/views/service_search.cljs
- Admin can download interaface list as CSV
=> 158322610 Download interface list as CSV

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/gtfs_viewer.cljs
- Improve GTFS load failed error message
=> 158288530 Improve GTFS load failed error message

database/src/main/resources/db/migration/R__Delete_operator.sql
- Deletion of operator with pre notices now works
=> 158211394 Delete pre notices when deleting operator

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/clj/ote/services/operators.sql, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/app/controller/transport_operator.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/buttons.cljs, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/transport_operator.cljs
* Delete functionality to operator page.
* Smaller padding for admin panel operator list
=> 153114037 delete operator

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/gtfs_viewer.cljs, ote/src/cljs/ote/views/gtfs_viewer.cljs
- More prominent error display in GTFS viewer
=> 158288530 More prominent error display

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Help message for real-time service field
=> 153215535 Add help message for real-time information

database/src/main/resources/db/migration/R__Delete_operator.sql
* Add delete from transit_route when operator is deleted.
=> 153114037-fix-delete-operator

ote/src/cljs/ote/app/controller/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
- Timing issue in operator filter
=> 158588534 Fix timing issue in operator filter

ote/src/cljs/ote/views/place_search.cljs, ote/src/cljs/ote/views/route/stop_sequence.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Set position and lower z-index for map containers to help fixed header hover above them.
=> 158681462 Fix fixed header on map components

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/integration/export/geojson.clj
* Added operator data to service search view
=> 158683230 operator data to service search view

.circleci/config.yml, aws/ansible/environments/staging/group_vars/ote/vars, ote/config.edn, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/login.clj, ote/src/clj/ote/services/login.sql, ote/src/clj/ote/util/feature.clj, ote/src/cljc/ote/db/user.cljc, ote/src/cljs/ote/app/controller/front_page.cljs, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/register.cljs, ote/test/clj/ote/services/login_test.clj
- New registration form in OTE
=> 158688099 New registration form

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljc/ote/db/user.cljc, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/views/register.cljs
- Registration error messages are hidden until the field is modified
=> 158688099 Hide error messages until field modified

database/src/main/resources/db/migration/V1_101__gtfs_package_cascade.sql
- Remove operator with imported GTFS data
=> 158833977 Add CASCADE constraints to imported GTFS data

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* Fixes for swedish and english translations.
* New english translations.
=> Translation fixes and additions

ote/resources/public/language/en.edn
* Translated a link in header menu into english.
=> Translate a header menu link into english.

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/import/stop_times.sql, ote/src/clj/ote/services/transit_visualization.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs
- GTFS import no longer duplicates stops
- Day comparison route listing and selection fix
=> 158941293 GTFS visualization fixes

ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
- Group routes with same name by headsign
- Show a compact trip list for route
- Don't highlight by default
- Show operator name on the page
=> 158974536 GTFS visualization improvements

ote/resources/public/language/fi.edn, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/login.cljs, ote/src/cljs/ote/views/main.cljs
- Make login dialog a page (instead of a modal dialog)
=> 158689876 Login dialog as a page

ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
- GTFS visualization: Add checkbox to toggle displaying of stops on/off
=> 159100538 Add checkbox to toggle displaying of stops on/off

ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
- GTFS visualization: show full stop listing when clicking a trip
=> 159102661 Show trip stop listing

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/import/kalkati.clj
* We'll now check and store also GTFS external interface URL errors.
=> 159064940 Handle GTFS interface URL errors and store the errors messages.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/service_search.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/icons.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/service_search.cljs
- Service catalog opens service info to new page instead of modal dialog
=> 159099643 Show service GeoJSON in its own route instead of modal dialog

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/icons.cljs, ote/src/cljs/ote/views/transport_service.cljs
* Added "Rotate device" suggestion if using service forms on mobile device in portrait-mode.
=> 159136086 suggest landscape mode

ote/src/cljs/ote/app/controller/route/route_wizard.cljs
* Use also service added dates in route validity from/to computation.
=> 159069152 Use added-dates in route-validity-dates computation.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/validation.cljs, ote/src/cljs/ote/views/transport_operator.cljs
* Add business-id field validation translations and a hint text.
=> 159102123 Translate Business-ID field vallidation text and add a hint text for the field

ote/resources/public/css/styles.css, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/login.clj, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/app/controller/front_page.cljs, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/login.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/register.cljs, ote/src/cljs/ote/views/user.cljs
- Replace CKAN dialog with new user edit page
=> 159129144 New user edit page

ote/resources/public/language/en.edn
* Pre-notices english translations.
=> 158935438 - Fully translate own pre-notices listing and pre-notices form in english.

ote/resources/public/language/sv.edn
* Changes to sv translations related in register page.
=> Update sv translations.

ote/resources/public/language/sv.edn
* Fix SV translations in login page.
=> 159191825 SV translation fixes.

ote/src/cljs/ote/app/controller/pre_notices.cljs
* Now showing correct nofications when saving or sending a pre-notice.
=> 158656761 Pre notices save notification fixes

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/service_search.cljs
* Changed operation area search hint texts. Added a hint for searching operation areas using finnish keywords.
=> 158658509 Add a new operation area search hint text in relevant places

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* Fixed a typo in sea traffic page.
* Changed brokerage related info texts.
=> 157791258 Translation improvements

database/src/main/resources/db/migration/V1_103__map_and_location.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljc/ote/db/transport_service.cljc, ote/src/cljs/ote/views/transport_service_common.cljs
- New `map-and-location` enum value to interface data content
=> 155776829 Add map-and-location value to interface data content

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/route/route_list.cljs
- Swedish language sea route user guide link
=> 159756416 Add swedish language user guide link

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
=> 158490132 Add missing translations from GeoJSON view

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/footer.cljs
* Add a link to SV NAP user guide.
=> 159820455 Add a link to sv nap user guide.

database/src/main/resources/db/migration/V1_104__rental_pick_up_locations_url.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/views/rental.cljs
* Added Pick up locations url field and related instructions and translations.
* Added pick-up-locations-url attribute in rental_provider_information.
=> 153957663 Pick up locations url

ote/src/clj/ote/integration/import/gtfs.clj
* Old GTFS import errors should now be successfully removed if a package was successfully loaded.
=> 159791695 Remove old gtfs import errors if package was successfully loaded.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/service_search.clj, ote/src/clj/ote/services/service_search.sql, ote/src/cljs/ote/app/controller/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
- Service catalog shows total count of companies
=> 159559239 Show service and company count

ote/src/clj/ote/integration/import/gtfs.clj
* Remove gtfs-import errors also when we receive 304 not modified from he target GTFS interface.
=> 159791695 Remove gtfs-import errors also when we receive 304

ote/resources/public/css/balloon.css, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/transit_changes.cljs
* Tooltip support for ote.ui.table
* Changed labels, tooltips and texts in transit changes table.
=> 159792487 muutostietojen tunnistaminen tekstimuutoksia

.circleci/config.yml, database/src/main/resources/db/migration/R__GTFS_query.sql, database/src/main/resources/db/migration/V1_105__transit_change_regions.sql, ote/src/clj/ote/services/transit_changes.clj, ote/src/cljs/ote/app/controller/transit_changes.cljs, ote/src/cljs/ote/views/transit_changes.cljs
- Region filter in detected transit changes listing
=> 159792284 Add region info and selection to transit changes

ote/src/clj/ote/services/login.sql
* Handle username and email in lowercase during login.
=> 160166108 Compare login email and username in lowercase

ote/src/cljs/ote/style/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
* Service search result card title text no longer overlap and the main result title text will auto-wrap.
=> 158721255 Fix overlapping text in service search result card title.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* Improved search info text in service catalog.
=> 160092329 Improve info text about total companies amount.

nap/docker/README.md, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/main_header.cljs
* New link to user menu - points to youtube video
=> Add link to video tutorials to user menu

ote/src/cljs/ote/style/front_page.cljs, ote/src/cljs/ote/views/front_page.cljs
* Hero text issue by replacing flex with display: block
=> 160052841 ie11 hero text problem

ote/src/clj/ote/services/transit_changes.sql
* Transit changes: list previously detected change
=> 160480941 Fetch latest upcoming change for each service

ote/src/clj/ote/services/transit_changes.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_changes.cljs
* Transit changes: clear old data when navigating to page
* Transit changes: use correct date for previously detected changes
=> 160509442 Clear old data when navigating to page

ote/src/cljs/ote/app/controller/transit_visualization.cljs
* Allow viewing unchanged routes in traviz.
=> Add default dates for all route selections in traviz.

ote/src/clj/ote/services/transit_changes.sql, ote/src/cljs/ote/views/transit_changes.cljs
* Check if transit changes service interfaces have problems and show results sorted in the transit changes list.
=> 160547073 Add interface error state into transit changes list and sort it in a better way

ote/src/clj/ote/services/transit_changes.sql, ote/src/cljs/ote/views/transit_changes.cljs
* Separated services with that have no imported interfaces in transit changes listing.
=> 160654680 Separate services with that have no imported interfaces in transit changes listing.

database/src/main/resources/db/migration/R__GTFS_query.sql, database/src/main/resources/db/migration/V1_109__gtfs_package_service_idx.sql
* GTFS change detection queries are much faster
=> 160649260 GTFS change speed improvements

aws/ansible/templates/ote/config.edn.j2, database/src/main/resources/db/migration/V1_111__reset_password.sql, nap/docker/docker-compose.yml, ote/config.edn, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/components/service.clj, ote/src/clj/ote/email.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/login.clj, ote/src/clj/ote/services/login.sql, ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/util/throttle.clj, ote/src/cljc/ote/db/user.cljc, ote/src/cljc/ote/environment.cljc, ote/src/cljs/ote/app/controller/front_page.cljs, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/views/login.cljs, ote/src/cljs/ote/views/main.cljs, ote/test/clj/ote/services/login_test.clj, ote/test/clj/ote/test.clj
* Password reset functionality in OTE
* New table for password reset requests
=> 160681684 OTE password reset

ote/src/clj/ote/tasks/pre_notices.clj
* Add sleep to email sending to prevent SES sending limits to be exeeded
=> Add 200ms sleep after every pre-notice email

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/login.cljs
* Better success message when saving user info
=> 160129965 Better success message when saving user info

ote/src/clj/ote/services/transit_changes.sql
* Do not show non-published services in the transit changes list.
=> 160715310 Show only published services in transit changes list.

ote/src/cljs/ote/app/controller/front_page.cljs, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/email_notification_settings.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs, ote/src/cljs/ote/views/pre_notices/listing.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/stop_sequence.cljs, ote/src/cljs/ote/views/theme.cljs, ote/src/cljs/ote/views/transport_service.cljs
* Language change is applied without reloading app
=> 158612424 Don't reload on language change

ote/src/clj/ote/components/service.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/reports.sql, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/admin/reports.cljs
* A new csv http route type for easily returning csv formatted data as downloable files.
* Three transport operator csv report interfaces in the admin panel.
=> 160278649 CSV Reports in admin panel

ote/src/cljs/ote/ui/nprogress.cljs, ote/src/cljs/ote/views/theme.cljs
* Remove "lataa" text form loading indicator
=> Change loading indicator

database/src/main/resources/db/migration/R__GTFS_query.sql
* Exception dates are now handled properly for specific date in gtfs_services_for_date sproc.
=>  160722453 GTFS change detection algorithm fixes

ote/test/clj/ote/gtfs/kalkati_to_gtfs_test.clj, ote/test/resources/kalkati/test1.xml
* Added test for kalkati->gtfs conversion
=> Add kalkati->gtfs smoke test

ote/src/clj/ote/db/lock.clj, ote/src/clj/ote/services/settings.clj, ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/tasks/pre_notices.sql, ote/test/clj/ote/tasks/pre_notices_test.clj, ote/test/clj/ote/test.clj
* Pre notice email includes changes detected from GTFS packages
=> 160184959 Include detected changes in pre notice email

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/app/controller/transit_changes.cljs, ote/src/cljs/ote/style/tabs.cljs, ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/ui/tabs.cljs, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/theme.cljs, ote/src/cljs/ote/views/transit_changes.cljs
* New custom tab component
* Take page controls and new tab component into use in admin and transit changes page
* Removed warnings by fixing styles and key elements
=> 158486115 add page controls to transit changes page

database/src/main/resources/db/migration/R__GTFS_query.sql
* Increase window size of gtfs_route_next_different_week sproc
=> 160949100 Increase window size of route_next_different_week.

database/src/main/resources/db/migration/R__GTFS_query.sql, database/src/main/resources/db/migration/V1_113__gtfs_route_with_daterange.sql, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/cljs/ote/app/controller/admin.cljs
- Use min/max dates for change detection
=> 160953789 GTFS detection changes

ote/src/clj/ote/integration/import/gtfs.clj
* Fix fetching saved ETag value for GTFS interface
=> 161076465 Fix fetching latest saved etag

ote/src/cljs/ote/ui/tabs.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs, ote/src/cljs/ote/views/transit_changes.cljs
=> Fix selected tab on refresh

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/services/external.clj, ote/src/cljc/ote/util/zip.cljc, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Zip package validation when unzipping.
* Zip file content listing without extracting utility function.
* Zip file list validation in transport service form.
* Improved GTFS and Kalkati.net interface zip package validation. Checking that required files must be present.
=> 160957934 improve malformed interface url detection

ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Transit visualization now separates different stop sequences
=> 161084197 Show different stop-sequences separately

ote/src/clj/ote/main.clj
* Changed logging configuration
=> 161141704 Only do println logging in dev and file logging in prod

ote/src/cljs/ote/views/transport_service_common.cljs
* Fix external interfaces required field warning visibility issue.
=> 161141399 Fix external interfaces required field warning visibility.

database/src/main/resources/db/migration/R__GTFS_query.sql
* GTFS change route active date range fix
=> Use date iterating query for active route determination

database/src/main/resources/db/migration/R__GTFS_query.sql
* Add a fix from gtfs_services_for_date to another signature of this fn.
=> 160649464 Add a fix from gtfs_services_for_date to another signature of this fn.

ote/src/clj/ote/services/transit_visualization.clj, ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Changed how packages are shown in GTFS visualization page
=> 160124333 Show latest and previous GTFS package info

database/src/main/resources/db/migration/R__GTFS_query.sql, ote/src/clj/ote/services/transit_changes.sql, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/views/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Change date is the actual different day of week, not the beginning of differing week
* Prefer change date that has traffic in both compared weeks
=> 160649316 Use actual differing date instead of week beginning

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_changes.sql, ote/src/cljs/ote/views/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* max-date to gtfs transit changes table
=> 160949269 gtfs until date

ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
=> 160124333 Improve GTFS package list styling

ote/src/cljs/ote/views/operators.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_operator.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Fixed db insert/update errors on inputs where it was possible to add more data to input field that db could receive.
=> Add max length to input fields

ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/service_search.cljs
* Now using :chip-input for operator search in service catalog
* Improvded :chip-input form field so that one can provide dynamic suggestions by providing customized on-update-input, on-request-add and on-request delete fns.
=> 161049449 service catalog chip input fix

aws/ansible/templates/ckan.ini.j2
* Fix CKAN email from name by changing ckan site_title setting to NAP.
=> 160953306 Update ckan site_title from CKAN to NAP

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* Update instructions concerning the external interface form fields.
=> 158444721 External interfaces instructions update

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/transport_service.cljs
* Fixed interface url update. It leaved wrong key to map that was passed to server and it could not be saved to db.
* New texts when reseting password
=> 161215776 interface error

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
* New text: Change notifications are for official use only.  
* Removed ID from own services list
=> 158355218 only for authorities

ote/src/clj/ote/services/admin.clj, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/admin/service_list.cljs
* modified timestamp to service list in admin panel
=> 160951576 modified

ote/src/cljs/ote/views/transit_visualization.cljs
* show boxed days only in future
=> 161109494 show boxed days only in future

ote/src/cljs/ote/views/transit_visualization.cljs
*Changed calendar hover logic to prevent color change on already selected days.
=> 160653609 Improve calendar hover highlighting.

ote/src/cljs/ote/views/service_search.cljs
* Show three companies (instead of 2) and only count of companies if there is more than three.
=> 160752628 Service search involved companies

ote/src/clj/ote/services/transport.clj, ote/src/clj/ote/services/transport.sql, ote/src/cljs/ote/app/controller/transport_service.cljs
* Fix transport service interface modification
* Change transport service query to be in type, modified order. And to do that, update the way they are fetched from db.
=> Order by modifified and fixed interface

ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/time.cljc, ote/src/cljc/ote/transit_changes.cljc, ote/test/clj/ote/transit_changes/detection_test.clj
* List of static holidays
* Skip static holidays in automatic gtfs data parsing
* Test to test that skip holidays works
=> Skip Static holidays

ote/resources/public/css/styles.css, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/tabs.cljs, ote/src/cljs/ote/ui/list_header.cljs, ote/src/cljs/ote/ui/tabs.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/email_notification_settings.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/pre_notices/listing.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/route_list.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/user.cljs
* Our tab component didn't handle mobile views very well.
*Update header (h1-h4) styles
=> 158442962 header styles

database/query_logging.sh, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/reports.sql, ote/src/cljs/ote/views/admin/reports.cljs
* CSV report for taxi operators and their subcontractors
* CSV report for request operators and their subcontractors
* CSV report for operators that have payment interface
* Script that enables sql logging in local development environment
=> 161774552 taxi, request, price csv reports to admin panel

ote/config.edn, ote/project.clj, ote/src/clj/ote/components/http.clj
Verify using netstat -at (check that LISTEN sockets are bound to localhost) and/or by trying to connect to these using localhost and networked addresses.
=> Backend:  Bind nrepl & http to localhost

ote/src/cljc/ote/transit_changes.cljc, ote/src/cljs/ote/views/transit_visualization.cljs
* Added key-fn to table to remove react warnings (there is still tables that needs unique keys)
* Formatted stop-name according to specification
=> 161811051 stop name

ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/tasks/pre_notices.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs
* Break in traffic text to email
* Transit visualization route list sorting changed to take into account route-long-name as well.
=> 161804833 email break in traffic

ote/src/cljs/ote/app/controller/transport_operator.cljs
nil'd out new? value caused save error on backend
=> Preserve new? in operator view controller

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/ui/scroll.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Scroll browser viewport to calendar when route is selected.
* Text to describe what is happening when routes are loading
* Routes with changes are sorted also using route short name.
* Added sortin to no changes also.
=> 161218363 scroll to calendar

database/src/main/resources/db/migration/V1_119__create_table_for_detected_routes.sql, database/src/main/resources/db/migration/V1_120__add_route_hash_ids.sql, database/src/main/resources/db/migration/V1_121__create_detection_service_route_type.sql, ote/src/cljc/ote/db/gtfs.cljc
* Added detection-route table
* Added table to store different route keys for different services
* Added created/modified columns to help with debugging
=> 162177663 route hash id table

ote/src/clj/ote/services/transit_visualization.sql
* Fix transit changes calendar coloring issues with external-id instead of package-id
=> 162342291 - Return date hashes to ui based on external-id ordering instead of package-id

database/src/main/resources/db/migration/R__GTFS_query.sql
* Change gtfs package created time from timestamp to date and compare if detection date is same or greater. If so, take changes from the newest package into account.
=> 161981836 Change newest package at the current day 

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/pre_notices/attachments.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_changes.sql, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs
* Upload gtfs package for service at a given day
* Improve admin panel ui
* List all services with route-hash-id
=> Improve admin panel ui and upload gtfs package for service

ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
* Removed inline css style that broke whitespacing.
=> 161489967 removed breaking in-line style

database/src/main/resources/db/migration/V1_123__add_value_to_external_interface_type_enum.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljc/ote/db/transport_service.cljc
* New options to external API selection.
* Added new enums to interface_data_content: 'on-behalf-errand'
* Check translations
=> 162165350 Added new options to interface data content, WIP: translations

ote/resources/public/img/icons/outline-add-box.svg, ote/resources/public/img/icons/outline-indeterminate-checkbox.svg, ote/src/cljs/ote/ui/icons.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
v2 of the icon change, specs on the pivotal ticket.
=> 162012032 icon changes to transit vis. view / palvelukohtaisten muutosten näkymän muutoksia

ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/theme.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Click handler to to close header menus after click event happens outside of dropdowns.
* When esc is pressed while navigation menus are open they are closed.
* Changed texts when routes change in a way that removes some route completely
=> 161672748 pysakki ei kuulu reitille

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/reports.sql, ote/src/cljs/ote/views/admin/reports.cljs
* Way to fetch all active users emails
=> 162635545 emails csv

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/tasks/pre_notices.clj, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/footer.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/own_services.cljs
* Remove references to Finnish Transport Agency
=> 162752327 drop livi

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/reports.sql, ote/src/cljs/ote/views/admin/reports.cljs
* Add transport-type to taxi and request csv report and create new report for schedule
=> 162726190 update csv reports

aws/ansible/environments/staging/group_vars/ote/vars
* enable :open-ytj-integration for staging env
=> environments: enable :open-ytj-integration for staging env

.gitignore, cypress/integration/own-services_spec.js, ote/resources/public/css/styles.css, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/buttons.cljs, ote/src/cljs/ote/style/info_style.cljs, ote/src/cljs/ote/theme/colors.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/transport_operator_selection.cljs
* Theme folder to contain theme related color constants
* Some general html spec related issues.
* UI of own services page
=> 162577600 omat palvelutiedot tyylit

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/info.cljs, ote/src/cljs/ote/views/transport_operator_ytj.cljs
* ui: info-toggle default state true i.e. expanded
* ui: form field support for info-toggle component
* language: initial localisation for operator ytj help info toggles
* views: transport-operator ytj info-toggles
=> 161874264 transport operator info toggles

ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/transport_operator_ytj.cljs
* ui: new form field for reagent/material divider component
* views: transport-operator adjust dividers
* views: transport-operator code formatting
=> 161836698 transport operator style layout

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/operators.sql, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/app/controller/transport_operator.cljs, ote/src/cljs/ote/views/transport_operator_ytj.cljs
* Added check that business-id must be valid and unique before data can be fetched from ytj using given business-id.
=> 162807267 does company exists

ote/src/clj/ote/nap/users.clj, ote/src/clj/ote/services/admin.clj, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/app/controller/transport_operator.cljs, ote/src/cljs/ote/views/admin.cljs
* Added possibility to edit company data for admin users.
=> 162754995 ytj admin

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* Language string updated to match traficom
=> 162981632 transport service brokerage checkbox update to traficom

ote/src/cljs/ote/views/transport_service_common.cljs
* Brokerage link from trafi to traficom
=> Update brokerage link to traficom

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/src/cljs/ote/app/controller/transport_operator.cljs
* Selected transport operator in own services page
* Translations
=> 163048192 default operator in own services

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/reports.sql, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/monitor.cljs
=> Valvontanäkymä 0.5

ote/src/clj/ote/services/operators.sql, ote/src/clj/ote/services/transport.clj
* Give permissions to all users within the same business-id family
=> 162754989 give permissions to all users

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Required contact details in transport service page. Now phone and email can also be counted as required data.
=> 162632091 contact details

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/theme/colors.cljs, ote/src/cljs/ote/ui/circular_progress.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/success_msg.cljs, ote/src/cljs/ote/ui/warning_msg.cljs, ote/src/cljs/ote/views/transport_operator_ytj.cljs
* new circular-progress component and accompanying styles
* circular-progress field for form
* views: transport-operator: Disable ytj fetch field and button when fetching
* views: transport-operator: progress spinner when fetching
* views: transport-operator: icon+text ytj fetch result indication next to YTJ fetch button
* string updates, e.g. removed a duplicate string
=> 163146424 transport operator improvement

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/theme/colors.cljs, ote/src/cljs/ote/ui/circular_progress.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/success_msg.cljs, ote/src/cljs/ote/ui/warning_msg.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_operator_ytj.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Re-merge PER https://github.com/finnishtransportagency/mmtis-national-access-point/pull/809 to fix integration problems
=> 163146424 FIX pr to re-merge PR#809

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/reports.sql, ote/src/cljs/ote/views/monitor.cljs
=> Monitor view (aka valvontankymä) CSV download & view explanation texts

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/transport_operator_ytj.cljs
* language: transport-operator view specific phone field labels
* views: transport-operator view specific phone field labels
=> 161836698 different phone field labels transport operator view

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Change opening-time and closing-time to starting-time and ending-time
to service-hours-group for passenger transportation services.
* Translations are missing
=> 153214355 - opening time texts

ote/resources/public/language/fi.edn, ote/src/cljs/ote/views/footer.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/own_services.cljs
* Nap help link address for finnish language
=> 163247974 new info page link for nap

cypress/integration/operator.js, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/transport_operator.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/transport_operator_ytj.cljs
* cypress: Initial operator e2e test module
* views: own-services set some element-ids to enable test automation
* views: transport-operator set some element-ids to enable test automation
* ui: form fields support for setting DOM element id
* views: fix operator deleting, button not displayed or working
* views, controller: renamed :business-id-exists? and code formatting
=> 161836698 operator style and misc fixes pt1

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Confirm dialog for brokering services
=> 163015263 brokering service dialog

ote/src/cljs/ote/app/controller/transport_operator.cljs
=> controller: transport-operator code refactoring

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
* language: transport-operator related string updates
=> language: transport-operator related string updates

ote/src/clj/ote/services/transit_changes.sql, ote/src/clj/ote/tasks/pre_notices.sql, ote/src/cljs/ote/views/transit_changes.cljs
* Service list changed to use different-week-date instead of change-date
=> 163553973 next different day to service list

database/src/main/resources/db/migration/V1_130__service_search_view_fix.sql, ote/src/clj/ote/services/service_search.clj
* Transport service catalog -> removed all but the current searched provicder from the "other companies providing the service" list.
* Changed transport_service_search_result view to contain all the participating service provicers properly.
=> Transport service catalog change

database/src/main/resources/db/migration/R__GTFS_query.sql, database/src/main/resources/db/migration/V1_128__per_route_changes_table.sql, ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/db/gtfs.cljc, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
** cleanup old code
** transit-visualization 
*** front-end: take new trip stop seq/time keys into use
*** service:  route-differences remove composite parsing
* detected changes query use new stop seq&time columns
* db: change gtfs-route-change stop seq&time columns from range to int type
=> 163481118 route changes composite type etc

aws/ansible/templates/ote/config.edn.j2, ote/src/cljc/ote/transit_changes.cljc, ote/src/cljs/ote/views/transit_changes.cljs
* Dev favicon in production.
* Slight bug in stop list order.
* Icon colors in FIrefox weren't showing because they color wasn't inside `:style` key.
=> 163550034 stop list order

ote/project.clj, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/external.clj, ote/src/clj/ote/services/login.clj, ote/src/clj/ote/services/places.clj, ote/src/clj/ote/services/service_search.clj, ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transport.clj
* kibit to project.clj
* Few backend files refactored according to kibit suggestions
=> Kibit refactoring

database/src/main/resources/db/migration/V1_131__add_service_id_to_date_hash.sql
* Add service-id to gtfs-date-hash table to speed up problem solving
=> Add service-id to gtfs-date-hash table

ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* controller, views: transport-visualization code formatting improvements
* controller: transport-visualization route filter checkbox disabling logic
views: transport-visualization route filter checkbox disabling logic
* views: transport-visualization add unique key for route-trips table
* controller: fix keys assoced under wrong parent in transit-visualization
=> 163788230 transport visualization checkbox disabling and other improvements

cypress/integration/pre-notice_spec.js, ote/src/cljs/ote/views/transit_visualization.cljs
* Remove headsign from route name if route-hash-id-type doesn't suppor it.
=> 163692268 trip headsign in route name

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Service contact details are not required anymore
=> 163783371 service contact details

database/src/main/resources/db/migration/V1_132__remove_constraint_gtfs_agency.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/style/buttons.cljs, ote/src/cljs/ote/style/service_search.cljs, ote/src/cljs/ote/theme/colors.cljs, ote/src/cljs/ote/views/service_search.cljs
* Service card styles to match Jussis spec
* Route changes checkbox should be toggleable even though changes-filtered is empty
* Removed `NOT NULL` constraint from gtfs-agency table
=> 163691778 no traffic

database/src/main/resources/db/migration/R__Transport_service.sql, database/src/main/resources/db/migration/V1_132__transport_service_publish_time.sql, database/testdata-ote.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/clj/ote/services/operators.sql, ote/src/clj/ote/services/reports.sql, ote/src/clj/ote/services/service_search.clj, ote/src/clj/ote/services/service_search.sql, ote/src/clj/ote/services/transit_changes.sql, ote/src/clj/ote/services/transit_visualization.sql, ote/src/clj/ote/services/transport.clj, ote/src/clj/ote/services/transport.sql, ote/src/clj/ote/tasks/gtfs.sql, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/views/admin/service_list.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/transport_service_common.cljs, ote/test/clj/ote/integration/export/geojson_test.clj, ote/test/clj/ote/services/service_search_test.clj
* Published timestamp to newly created services.
* Everything that used the old published? now use the published timestmap
* Transport-service table now contains published as a timestamp instead of a boolean "published?"
=> 163816930 published time

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/service_search.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Height problem of table rows because selected table row will need some more height.
* Normal links color and text decoration
* Service card styles not matching the webflow specs.
=> 163478330 service card - new fixes

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/footer.cljs, ote/src/cljs/ote/views/theme.cljs
* mailto links instead of google form.
=> 163940009 mailto link 2

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/footer.cljs, ote/src/cljs/ote/views/theme.cljs
* Google form urls to mailto links.
=> Changed google form urls to mailto links.

ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* transit-visualization column "chnage detected" added for route-changes table
* Style changes for the table to improve responsiveness, mobile first :)
=> 163902792 transit visualization simplify route filtering checkbox logic

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs, ote/src/cljs/ote/views/main.cljs
* New tab to admin panel where admin users can mark if scheduled service is commercial or contract traffic.
=> 163649701 skip contract traffic

ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/ui/icon_labeled.cljs, ote/src/cljs/ote/ui/success_msg.cljs, ote/src/cljs/ote/ui/warning_msg.cljs, ote/src/cljs/ote/views/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* views: transit-visualization tables refactored for better responsiveness
* views: transit-changes tables refactored for better responsiveness
* ui: success-msg and warning-msg to reuse icon-labeled-icon and stylefy
* ui: introduced icon-labeled
* style: icon-labeled-*, transit-changes-legend-*, transit-changes-icon*
=> 163935474 refactor transit table styles part ii

ote/resources/public/language/fi.edn
* language: transit service privacy statements updated for FI
=> 164075352 transit service privacy statements updated for FI

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
Continuation of https://github.com/finnishtransportagency/mmtis-national-access-point/pull/903 now when remaining strings are available.
* language: transit service privacy statements updated for SE and EN
=> 164075352: transit service privacy statements updated for SE and EN

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
=> Translations: For service-card.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/transport_service.cljs
* transport-service open license url in new tab or window
=> 164075352 transport-service open license url in new tab or window 

ote/resources/public/language/sv.edn
* fix transit-service license link for SE
=> language: fix transit-service license link for SE

database/src/main/resources/db/migration/V1_140__hash_recalculation.sql, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_changes.sql, ote/src/clj/ote/tasks/gtfs.sql, ote/src/clj/ote/tasks/pre_notices.sql, ote/src/clj/ote/transit_changes/detection.clj, ote/src/clj/ote/transit_changes/detection.sql, ote/src/cljc/ote/db/gtfs.cljc, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/app/controller/transit_changes.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/style/admin.cljs, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/transit_changes.cljs
* Admin panel: Added a block to three tab to prevent multiple hash calculations
* Controller: Added new controller for admin change detection tools.
* Added new table which contains information about ongoing hash calculations
* Admin panel: Filtered out services from contract/business list by ensuring that they have interface.
=> 163945472 block

ote/src/cljs/ote/style/table.cljs, ote/src/cljs/ote/ui/table.cljs
* Added own style file for table styles.
* table component:  Changed container element for no rows message from common help to plain white div.
=> 164047545 no route changes message

aws/ansible/environments/staging/group_vars/ote/vars, ote/config.edn
* config: disable :open-ytj-integration for default config 
* environments: disable open-ytj-integration on staging
=> 164266827 disable open ytj integration staging

ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* The logic behind date selections in the calendar component.
=> 164101934 calenda date pick

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/service_search.clj, ote/src/cljs/ote/style/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
* Implemented new service card styles.
=> 164266607 service card

ote/src/cljs/ote/views/transit_changes.cljs
* transit-changes: Filters are now a list. It fixes IE bug also.
* transit-changes: Changed texts to be more precise.
=> 161775593 Transit page filter change

ote/project.clj, ote/src/clj/ote/components/db.clj, ote/src/cljs/ote/ui/common.cljs
Let's see how this fares on CircleCI - seems fine on local dev setup
=> Update clojurescript and clojure

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/service_search.cljs
* Some minor fixes requested by Susanna and Jussi.
=> Some minor changes requested by Jussi.

ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljs/ote/app/controller/transit_visualization.cljs
* transit-visualization page: Fixed detected changes count in calendar component
* detection.clj backend: Counts were not calculated for ending or new routes. Calculation added.
=> 164000883 detected changes count in calendar

ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_changes.cljs
* Transit changes: Sort transit changes by different week date and first at the top.
* Transit visualization: Add more color options to calendar
=> 164624270 sort detected chages

ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/time.cljc
* cljc: joda.time.localdate to date-fields protocol fixes native->date
* transit-changes: fix update-transit-changes! :pre package id assert
=> 163148392 fix update transit changes

database/src/main/resources/db/migration/V1_141__remove_foreign_key_from_detected_routes.sql
* Fixed broken foreign-keys from gtfs-packages and detected-route-changes
=> 164725467 Remove and replace foreign-keys in transit-changes/gtfs

ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/transit_changes.cljc, ote/test/clj/ote/transit_changes/detection_test.clj
* transit-changes: transit-changes: func and test to detect all changed days on a week hash
=> 164759294 detect all changed days on a week

ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs, ote/src/cljs/ote/views/footer.cljs
* Admin: Hash calculation status might get stuck in testing environment when deploying new package. Added button to reset latest calculation status.
* Fixed few private functions to remove warnings from figwheel.
* Admin: Added form to enable change detection for given service.
=> 164600197 reset calculation status

ote/project.clj, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/ui/icon_labeled.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/footer.cljs, ote/src/cljs/ote/views/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/change_icons.cljs, ote/src/cljs/ote/views/transit_visualization/change_utilities.cljs
* Transit-visualization page: Added summary of changes to all route rows
* Transit-changes page: Added colors to change icons at the top of the page
* Transit-visualization page: Added new route-ending icon.
* Transit visualization page: Added more colors to calendar to visualize traffic
=> 164756947 route summary

ote/src/cljs/ote/app/controller/transit_visualization.cljs
*  Update detection calendar colors
=> 164629314 Update detection calendar colors

ote/resources/public/css/styles.css, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/page.cljs, ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/ui/icon_labeled.cljs, ote/src/cljs/ote/ui/page.cljs, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
* transit changes page: detected changed help text
* Few text updates to "mahdollisesti päättyvät reitit" category
* small ui element updates
=> 163451566 detected changed help text

database/src/main/resources/db/migration/V1_142__remove_old_change_dates.sql, ote/test/clj/ote/transit_changes/detection_test.clj, ote/test/clj/ote/transit_changes/detection_test_utilities.clj, ote/test/clj/ote/transit_changes/detection_window_test.clj
* Add tests for 25 weeks and 35 weeks to ensure that 30 week detection window works
* I had to refactor detection test codes. I didn't change them. I only added two more.
=> 163148396 Clean up wrong change-dates from db

ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/transit_changes.cljc, ote/test/clj/ote/transit_changes/detection_test.clj
* Detect properly route starting & ending during window
*  transit-changes: tests for detection holiday comparison
* transit-changes: detect traffic after weekday nil and refactor route end
* fix change added/removed counts when route ends&starts during the same detection window
=> 164796337 detect traffic: after no traffic on same week,  removed route, fix change added/removed counts when route ends&starts

ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/change_icons.cljs, ote/src/cljs/ote/views/transit_visualization/change_utilities.cljs
* Added different day indicators to map section
* Removed map from section header and moved it to section body
* Tuned a bit icon element widths
=> 161871710 transit visualization map section ui tuning

ote/test/clj/ote/transit_changes/detection_test.clj, ote/test/clj/ote/transit_changes/detection_test_days.clj, ote/test/clj/ote/transit_changes/detection_test_utilities.clj, ote/test/clj/ote/transit_changes/detection_test_weeks.clj, ote/test/clj/ote/transit_changes/detection_window_test.clj
* test: detection_window use test data fn moved to util
* test: detection day tests into separate file
* test: test weeks creation by utility fn not manually
* test: code formatting
=> Detection test refactoring

cypress/integration/service-viewer_spec.js, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/service_viewer.cljs, ote/src/cljs/ote/ui/link_icon.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/service_viewer.cljs
* Some fixes suggested by Jussi.
=> 164267877 service view fix

ote/src/clj/ote/tasks/pre_notices.clj
* Detected changes were sent only for the first user. Then they were marked as sent.
=> Fix detected changes email 

ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/app/controller/transit_changes.cljs, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/app/routes.cljs
* cljc: now-iso-date-str for getting current ISO format date in as string
* controller: transit-visualisation hide changes in past
=> 165113720 transit-visualization: hide past transit changes

ote/src/cljs/ote/views/service_viewer.cljs
=> Service view: Fixed bug of service times not showing.

cypress/integration/main_spec.js, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/login.clj
* Update credentials error message
=> Update login credentials error message

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/app/controller/transit_changes.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs, ote/src/cljs/ote/views/admin/interfaces.cljs, ote/src/cljs/ote/views/admin/service_list.cljs, ote/src/cljs/ote/views/transit_changes.cljs
* transit-changes: Fixed how contract traffic is filtered out using checkboxes even if they have errors in interfaces
* admin panel: Added "back to admin panel" link to admin panel transit changes detection section
* admin panel - contract traffic: Added services without interfaces to contract traffic list
* admin panel - interface errors: Added services without interfaces to the list
=> 165173937 contract traffic with errors

.gitignore
* .clj-kondo folder added to .gitignore
=> .gitignore add .clj-kondo/

ote/src/clj/ote/transit_changes/detection.clj, ote/src/clj/ote/transit_changes/detection.sql, ote/src/cljs/ote/views/transit_changes.cljs
* Change detection: Fixed first-of-may and other holidays when route didn't have traffic on those days.
* detection.clj refactor
* Links to transit visualization in transit changes view.
=> 165058132 first of may

ote/src/clj/ote/services/service_search.clj, ote/test/clj/ote/services/service_search_test.clj
*    Corrected spatial search result ranking when paging is used. Before this fix, spatial search results were ranked only withing the queried page.
=> 152841059 spatial search rank

ote/resources/public/language/fi.edn, ote/src/cljs/ote/views/service_viewer.cljs
* One missed text change
* Check if list is empty to show "Ei ilmoitettu" instead of empty string
=> Fixes missed in the earlier pull requests: 165270343, 165274555

ote/src/clj/ote/services/admin.sql, ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljs/ote/views/admin/interfaces.cljs
* Admin popup
* timestamp when interface error
=> 165304032 admin popup

.circleci/config.yml
It didn't work with our config anyway.
=> Cypress config change to avoid freemium recording limit

.circleci/config.yml
Need --record false, instead of absent --record switch.
=> Cypress recording opt tweak redux

.circleci/config.yml, aws/ansible/jenkins/jobs/cypress.groovy
* aws: remove CYPRESS_RECORD_KEY
* circleci: invalidate cache by iterating key name
=> Cypress ci set new cache key to try get latest ci config reloaded in cloud ci env

.circleci/config.yml, aws/ansible/jenkins/jobs/cypress.groovy, cypress.json, cypress/integration/pre-notice_spec.js, cypress/plugins/index.js, database/src/main/resources/db/migration/V1_145__detection_holidays.sql, ote/resources/public/csv/poikkeavat_ajopaivat.csv, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/admin.clj, ote/src/cljc/ote/db/gtfs.cljc, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs, ote/src/cljs/ote/views/main.cljs, ote/test/clj/ote/integration/import/exception_csv_test.clj
* New admin endpoint for starting the fetching of CSV data
* New admin views to call this endpoint and show results.
* Some swedish translations.
* New table for detection holidays
=> 165244062 csv fetching

ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/tasks/pre_notices.sql
* /new to email link
* This feature does another thing.
* unsent changes email detected changes count by adding distinct
=> 165437997 Unsent detected changes query was returning same changes multiple 

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/transit_changes.cljc
* Use the "detection-holidays" table in the change-detection.
* Responses for the admin panels csv importing.
=> 164597097 use holidays

ote/resources/public/language/sv.edn
* Changed sv translations to match the finnish texts
=> Language: Changed sv texts to match the finnish ones better.

.circleci/config.yml, aws/ansible/jenkins/jobs/cypress.groovy, cypress/integration/own-services_spec.js, cypress/integration/pre-notice_spec.js
* Cypress tests to see if they still break in CI
* Cypress to run in it's own electron browser instead of chrome to fix random issues in CI
=> CI/cypress: Test to see if clearing cookies before login does something.

ote/src/cljs/ote/views/admin/monitor.cljs
* Text changes, margin-bottom, chart type selection to the left
=> 165380488 Monitor view ui changes

ote/src/clj/ote/transit_changes/detection.clj, ote/src/clj/ote/transit_changes/detection.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* transit-visualization: calendar - when different-week-date is null
* service-route-hashes-for-date-range query when service has more than one interface
=> 165675643 multiple interfaces db query problem

cypress/integration/own-services_spec.js, ote/src/clj/ote/services/admin.clj, ote/src/cljs/ote/views/transport_service_common.cljs
* Admin endpoints admin rights check.
* Removed external interfaces checkbox from new service form.
* Tests to not check the removed checkbox
=> 165675611 admin endpoints

ote/src/cljs/ote/style/topnav.cljs
* z-index issue with leaflet map.
=> top-nav: increased z-index to fix map element overlap.

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
=> own-services translations

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/front_page.cljs, ote/src/cljs/ote/views/footer.cljs
* Some styling for visible email link.
* Visible email under mailto link in footer.
=> 165274531 mailto email

ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* Grouped tests according to tested functionality
* Test case implementation structure a bit more uniform
* Removed a few overlapping tests and re-implemented a few
=> Transit changes test refactoring

ote/src/cljs/ote/style/topnav.cljs, ote/src/cljs/ote/ui/main_header.cljs
* Email visible under mailto link in the header navigation.
=> Top-nav: Email visibile under mailto-link.

docs/transit-changes/README.md, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/config/transit_changes_config.cljc, ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* config: transit_changes_config.cljc added
* transit-changes: refactor internal functions to have less args
* transit-changes: move important constants into a config file, update doc
* doc: transit-changes detection actually 216 days into future 
* tasks: format indentations for gtfs.clj
=> 165815637 transit changes config into cljc

ote/src/clj/ote/services/transit_changes.sql, ote/src/clj/ote/services/transit_visualization.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/calendar.cljs, ote/src/cljs/ote/views/transit_visualization/change_utilities.cljs
* Visualization for recent changes in changes table.
=> 165672337 latest changes indicator

ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* Bug where multiple changes appeared on the same date.
=> 165996661 multiple changes same date

ote/resources/public/css/styles.css, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/service_search.clj, ote/src/cljs/ote/style/page.cljs, ote/src/cljs/ote/style/service_search.cljs, ote/src/cljs/ote/views/service_search.cljs
* service-search: New subheadings for spatial search
=> 165876582 spatial ui subheading

ote/src/clj/ote/components/http.clj, ote/src/clj/ote/services/admin.clj, ote/src/cljs/ote/app/controller/admin.cljs, ote/test/clj/ote/services/admin_test.clj, ote/test/clj/ote/test.clj
This initiates the refactoring of admin routes and endpoints to use properly HTTP status codes,  methods/verbs and url parametrization.
*  components: http.transit-response multi-arity to specifying http status
*  test: http-client/delete helper for unit tests
* services: admin/user DELETE id parsing for security and test for bad id
services: admin/user getting users refactored from POST to GET
services: admin/users refactored to admin/user and to use url parameters
services: admin/delete-user endpoint changed to DELETE admin/user/:id
services: tests improved admin/users, inspect https status etc.
services: admin endpoints refactored admin/users and admin/delete-user
Remaining admin endopoints will be refactored in upcoming PRs
=> 165675611 admin user endpoint refactoring

cypress/integration/operator_spec.js, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/operators.sql, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/app/controller/operator_users.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/app/utils.cljs, ote/src/cljs/ote/style/buttons.cljs, ote/src/cljs/ote/theme/colors.cljs, ote/src/cljs/ote/ui/spinner.cljs, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/operator_users.cljs
* New view for user access management
* New placeholder endpoints and controllers
* Possibility to remove padding from table body, if the rows don't need to be selectable
* Regex for detecting emails 
* Disabled button border
=> 166023904 handle org users view

ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/tasks/pre_notices.sql, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
* Change email: Fixed changed route count
* transit-visualization: Added route end icon to route list when no-traffic route has ending change also.
=> 166029512 notification email change count errors

docs/transit-changes/README.md
* docs: transit-changes fix typo
=> docs: transit-changes fix typo

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/tasks/pre_notices.clj, ote/src/clj/ote/tasks/pre_notices.sql
* Html email for outlook : More inline styles.
* Html email for outlook: Changed the way how gray background color is used.
=> 165786969 background color, font and button fix to html email

ote/src/clj/ote/services/service_search.clj, ote/src/clj/ote/services/service_search.sql, ote/src/cljs/ote/views/service_search.cljs
* service-search: Order spatial search results using difference and modified timestamp
=> 165560779 spatial search order

ote/src/clj/ote/services/admin.clj, ote/test/clj/ote/services/admin_test.clj
* admin fix delete user when there are no memberships
=> 165675611 admin fix delete user when there are no memberships

ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljc/ote/transit_changes.cljc, ote/src/cljs/ote/app/routes.cljs, ote/test/clj/ote/transit_changes/detection_test_weeks.clj, ote/test/clj/ote/transit_changes/detection_window_test.clj
* New tests for change detection.
* Change detection to include changes to and from nil days during the week
* Go to login page when trying to navigate to a page that requires authentication, while being unauthneticated.
=> 165992290 no change detected

ote/src/clj/ote/services/transit_changes.sql, ote/src/clj/ote/tasks/util.clj, ote/src/clj/ote/transit_changes/detection.clj
* transit-changes: upcoming-changes db query
* backend - update-transit-changes!: fixed how changes are calculated and stored to db
=> 166263523 detected changes wrong route counts

.circleci/config.yml
=> Comment out e2e tests in circle due to flakiness

ote/src/clj/ote/services/transit_changes.sql, ote/src/clj/ote/services/transit_visualization.sql, ote/src/clj/ote/tasks/gtfs.clj
* transit-changes page: Recalculate change amounts for all services every night
=> 166438650 remove expired detected changes from transit-changes list

ote/src/clj/ote/transit_changes/detection.clj, ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* Small fixes to old unit test cases
=> 166267438 transit changes, fix and refactor some old tests

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/views/admin/reports.cljs
* New csv report to admin panel: Ports
=> Ports csv report

ote/src/cljs/ote/views/admin/monitor.cljs, ote/src/cljs/ote/views/ckan_service_viewer.cljs, ote/src/cljs/ote/views/email_notification_settings.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs, ote/src/cljs/ote/views/pre_notices/listing.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/stop_sequence.cljs, ote/src/cljs/ote/views/transport_service.cljs
* Replace all spinners with circular_progess
=> Yet another spinner commit

cypress/integration/operator_spec.js, nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/emails/reset_password.txt, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
* Changed helpdesk email to nap@traficom.fi
=> 166538110 Update helpdesk email to nap@traficom.fi

ote/src/cljc/ote/util/transport_service_util.cljc, ote/src/cljs/ote/views/service_viewer.cljs, ote/test/clj/ote/util_tests.clj
* Add function that reorders week day set. And take it into use in service-viewer page
=> 166538796 reorder week days in service view

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* pre-notice-edit -page: Changed input field to link where users can download attachments.
* pre-notice-edit -page: Added link to previous page
=> 164793279 download attachment

ote/src/clj/ote/services/reports.sql
* Fixed 2 csv reports that were broken because of wrongly made user table join.
=> Fix csv report sql queries

ote/src/clj/ote/services/transit_visualization.sql
* Fixed fetch-route-trip-info-by-name-and-date
=> 166894083 Make fetch-route-trip-info-by-name-and-date faster

ote/src/clj/ote/transit_changes/detection.clj, ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* transit-changes: test case, :no-traffic and changes after resuming wk 
Not related to other commits in this PR, but adds a test for supported scenario
* transit-changes: detection, invalid route-differences assert to throw
=> 166732042 transit change detection new route handling - Additional refactoring improvements 1

database/src/main/resources/db/migration/V1_152__add_groupid_tokens.sql, database/src/main/resources/db/migration/V1_153__remove_revision_constraint.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/authorization.clj, ote/src/clj/ote/services/operators.sql, ote/src/clj/ote/services/pre_notices/authority.clj, ote/src/clj/ote/services/register.sql, ote/src/clj/ote/services/transport.clj, ote/src/clj/ote/util/email_template.clj, ote/src/cljs/ote/app/controller/common.cljs, ote/src/cljs/ote/app/controller/operator_users.cljs, ote/src/cljs/ote/app/controller/pre_notices.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/operator_users.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
* group-check function for endpoints
* Token management for invited users.
* Email for inviting totally new users
* All dialogs that used CKAN to manage user access to remove
* Use ckan group id instead of operator id to fetch users
=> 165675263 ckan remove final

ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/views/transport_service_common.cljs
* Add "Back to Draft" button to service form
=> 152601167 Add "Back to Draft" button to service form

ote/src/clj/ote/services/transport.clj, ote/src/clj/ote/util/email_template.clj
* Typo in email
* Wrong keywords used to fetch data from operator map.
=> Ckan remove fixes

ote/resources/public/language/fi.edn
=> Ckan-remove: Added a question mark to confirm dialog text.

ote/src/clj/ote/tasks/pre_notices.sql
#Fixed
* Add no-change filter to fetch-current-detected-changes-by-regions db query
=> 166900439 pre notice html error in date-fields

ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/views/register.cljs
* Removed tokens from urls sent to matomo.
* Show the "invalid token" notification first and when the token is checked show the "valid token" notification
=> Matomo url fix

cypress/integration/operator-users_spec.js, cypress/integration/operator_spec.js, cypress/integration/pre-notice_spec.js, ote/src/cljs/ote/views/operator_users.cljs
* New E2E test for managing operator members
* Skip a broken e2e test for opening authority modal.
=> 166755316 user control e2e

ote/src/clj/ote/util/email_template.clj
* spacing in header
* fixed email settings link not being in the email
=> 167006197 email fixes

ote/src/clj/ote/services/register.clj, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/views/confirm_email.cljs
* Registeration page to show errors properly.
* HTTP return codes on register events.
=> 166907227 email verification fix

ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
#Changed
* Made it more clear that the pre-notice form is not editable
=> 166893827 pre notices edit

cypress/integration/pre-notice_spec.js, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* pre-notice end 2 end tests
* button text when viewing old pre-notice
=> 166893827 pre notices e2e

ote/src/clj/ote/services/login.clj, ote/src/cljs/ote/app/controller/login.cljs
* The edit user information feature that was broken after user email confirmation was added.
=> edit-user: fixed editing user info

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* Removed trash can icon from confirmation dialog save button
* Changed texts
=> pre-notice: confirm dialog text change & icon remove

database/Dockerfile
* Updated ubuntu:artful to ubuntu:bionic and 9.6 postgres to 10
=> Change ubuntu:artful -> ubuntu:bionic and 9.6 postgres to version 10.

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/users.clj, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/views/confirm_email.cljs, ote/src/cljs/ote/views/user.cljs
* Possibility for users to edit own email
=> 167190672 editing own email fix

database/src/main/resources/db/migration/V1_159__alter_business_id_restriction.sql
* Changed business-id column into text to fit foreign business ids in to the field.
=> foreign-bid: changed business-id column from char(9) to text

ote/src/cljs/ote/app/routes.cljs
=> router: Fixed redirect after login.

ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/app/routes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs
* Possibility to pass route selection in url in transit visualization.
=> 166323305 selected route in url

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/pre_notices/authority.clj, ote/src/clj/ote/services/pre_notices/pre_notices.sql, ote/src/clj/ote/util/email_template.clj, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
* pre-notice-authority-list: Added first effective date
* pre-notice-authority-list: Changed table column order
* pre-notice-authority-list: Updated column spacing
* pre-notice-email: changed column headers
=> 161748573 pre notices

cypress/integration/pre-notice_spec.js, ote/src/clj/ote/services/pre_notices/pre_notices.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* Transit visualization page: Show next year only on select or if date is past September first
=> 164534477 show next years calendar

ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/calendar.cljs, ote/src/cljs/ote/views/transit_visualization/change_icons.cljs, ote/src/cljs/ote/views/transit_visualization/change_utilities.cljs
* transit-visualization page: Add date comparison summary data for trips and stops
=> 161918381 Add comparison data for trips and stops

ote/test/clj/ote/integration/export/geojson_test.clj, ote/test/clj/ote/integration/import/ytj_test.clj, ote/test/clj/ote/services/admin_test.clj, ote/test/clj/ote/services/pre_notice_test.clj, ote/test/clj/ote/services/service_search_test.clj, ote/test/clj/ote/services/transport_test.clj, ote/test/clj/ote/tasks/company_test.clj, ote/test/clj/ote/tasks/pre_notices_test.clj, ote/test/clj/ote/test.clj
#367 Changed
* bd14540e3 test: Test cases changed to get user-id from ote.test atom
* ffb41b009 test: atom for storing fetched db user ids for convenience
=> 167667113 test cases changed to get user id from atom

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/tasks/gtfs.sql, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs
* admin panel: Added input field to enable gtfs package download for selected service
=> 166440154 force gtfs download for service

ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs, ote/src/cljs/ote/views/pre_notices/listing.cljs, ote/src/cljs/ote/views/transit_changes.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* 0d4a87414 ui: table component's react key optimisation by removing some indices
*  views: table-name key set for tables for several views
=> 167665859 table view rendering optimisation via react key optimisation

ote/src/clj/ote/util/email_template.clj
* unregistered user invitation email template formatting newline
=> email: unregistered user invitation email template formatting newline

ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* views: transit-visualization update route change table 'new route' icon
=> views: transit-visualization update route change table 'new route' icon

ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/change_icons.cljs, ote/src/cljs/ote/views/transit_visualization/change_utilities.cljs
* views: transit-visualization move icon funcs from _utils to _icons
* views: transit-visualization fix layout and refactor date compare icons
=> 161918381 transit visualization tweak change icon headers and refactor

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/src/cljs/ote/views/transport_service.cljs
* views: transport-service update title, move instructions to info-toggle
=> views: transport-service update title, move instructions to info-toggle

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/user.cljs
* views: user profile, localize email confirmation sent infotext
=> 167190672 user profile email change info localized

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
* language: user profile, :change-email-confirmation-sent EN & SV
=> language: user profile, :change-email-confirmation-sent EN & SV

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
* language: user profile, :change-email-warning EN & SV
=> language: user profile, :change-email-warning EN & SV

database/testdata-ote.sql, ote/src/cljs/ote/views/admin.cljs
* views: admin, name and id added to delete operator modal for convenience 
* db: testdata operator 'Terminaali Oy' business id changed to unique
=> Test data fix and admin view tweak

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
* language: :move-to-services-page EN & SV updated**
=> language: :move-to-services-page EN & SV updated

ote/src/cljs/ote/style/admin.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs
* views: admin, detected changes control panel more margins and responsive
Same old thing, but 
- a bit of margin between button and input
- hr divider between the usual and dangerous buttons
- All buttons aligned to right, previously they were not quite or some were left
- Buttons wrap below text responsively
- Buttons could just as well be left-aligned, kept right for now because that layout leads user to first read the button help text on left/top.
=> views: admin, detected changes control panel more margins and responsive

ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* Transit visualization page: Fixed next years calendar checkbox overflow issue with IE Edge
*  Transit visualization page: Cryptic package download error text changed
=> 164534477 fix checkbox placement edge

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/tasks/pre_notices.clj, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs
* Simplify pre notice email subject to prevent issues in production
=> 167727513 Simplify pre notice email subject to prevent issues in production

ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/style/transit_changes.cljs, ote/src/cljs/ote/views/admin/interfaces.cljs
#Fixed
* admin interface tab: Removed duplicate row
* admin interface tab: checkboxes to radiobuttons
* transit visualization page - package info box - gray950 alert icon to red
=> 166572668 update admin interface tab

database/src/main/resources/db/migration/V1_164__new_service_search_result_view.sql
=> New version of search view

ote/src/clj/ote/services/transit_changes.sql
=> 167971578 upcoming-changes query

ote/src/clj/ote/services/admin.clj
* services: admin: fix send-pre-notice-email-response args to allow send
=> services: admin: fix send-pre-notice-email-response args to allow send

ote/src/clj/ote/tasks/pre_notices.clj
* services: pre-notices: fix notificaation email sending loop
=> services: pre-notices: fix notification email sending loop

ote/src/clj/ote/tasks/pre_notices.clj
* services: pre-notices: force mapcat to non-lazy when sending emails
And remove unused variable
=> services: pre-notices: force mapcat to non-lazy when sending emails

database/src/main/resources/db/migration/V1_165__add_on_delete_cascade_to_download_status_fkey.sql
=> 168103585 Add "on delete cascade" to foreign key that prevented service deletion

ote/src/cljc/ote/db/transport_service.cljc, ote/src/cljs/ote/views/service_viewer.cljs
* db-transport-service: Added default value to service-key-by-type case to prevent null point exceptions
* service-viewer: Added all data types to interface header.
=> 167283447 interface header update

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/service_viewer.cljs, ote/src/cljs/ote/views/service_viewer.cljs
* service-viewer: Fixed usage-area description
* service-view: Show brokerage? only for passenger-transportation types
* service-viewer: remove service-hour-info description
* service-viewer: Text change to payment method description
=> 167283447 changes to parking and rentals

docs/api/README.md
* doc: api readme tweaks, wording and official traficom name updated
=> doc: api readme tweaks, wording and official traficom name updated

ote/src/cljc/ote/transit_changes.cljc, ote/test/clj/ote/transit_changes/stop_name_detection_test_values.clj
* Sort stops also by stop sequence
=> 168215043 Sort stops also by stop-sequence

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/routes.clj, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/form_fields.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/basic_info.cljs, ote/src/cljs/ote/views/route/stop_sequence.cljs, ote/src/cljs/ote/views/route/trips.cljs, ote/src/cljs/ote/views/service_viewer.cljs, ote/src/cljs/ote/views/theme.cljs, ote/src/cljs/ote/views/transport_operator.cljs
HOX: operator homepage url branch should be merged to master first. This is build top of that.
* Decided to test if our new ui specification works well with other forms. This pr focus to pre-notice-form. If this is ok we could consider to update transport service form also.
* Updated pre-notice-form validation functions.
=> Pre notice form ui

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/routes.clj, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/basic_info.cljs, ote/src/cljs/ote/views/route/stop_sequence.cljs, ote/src/cljs/ote/views/route/trips.cljs, ote/src/cljs/ote/views/service_viewer.cljs, ote/src/cljs/ote/views/theme.cljs, ote/src/cljs/ote/views/transport_operator.cljs
* sea route editor: Added operator homepage to editor
* sea-route-editor: New ui for the form
=> 164826821 sea route operator homepage

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/views/admin/sea_routes.cljs
* admin-sea-routes: Show created and MAX active date
=> 166496305 active route days to admin

ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/app/controller/route/route_wizard.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/route/trips.cljs
* views: route: disable save if stop-times not chronological or valid
views: route: warning if stop-time not chronological or valid
controller: route: validate stop-times sequence
=> 168312913 sea route validate stop time input and chronology

ote/src/cljs/ote/app/controller/route/route_wizard.cljs
* 447219e  controller: route: fix add-remove stop corrupting stop-idx of stop-times
NOTE: this PR baseline is https://github.com/finnishtransportagency/mmtis-national-access-point/pull/1159 and contains only 1 more commit. Please review PR #1159 first.
=> 168369532 sea route trip stop time idx wrong after add delete stops

ote/src/clj/ote/transit_changes/detection.sql, ote/test/clj/ote/transit_changes/detection_integration_test.clj
* Added LEFT JOIN to service-route-hashes-for-date-range query
=> 168366947 Invalid change detection

ote/src/clj/ote/services/operators.sql
* manage users page: Fetch only active users
=> 167966860 - Fetch only active users to manage users page

ote/src/cljc/ote/transit_changes.cljc, ote/test/clj/ote/transit_changes/stop_name_detection_test.clj, ote/test/clj/ote/transit_changes/stop_name_detection_test_values.clj
* transit visualization page: Reorder removed stops by adding additional sorting function
=> 168311599 reorder removed stops

ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/views/admin/sea_routes.cljs
* Admin sea route tab: Fixed sql query for routes which are missing calendar rules.
=> 168453305 - sea route admin tab - some routes missing

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
* trips: stop time warning translations sv and en
=> language: trips: stop time warning translations sv and en

ote/resources/public/css/styles.css, ote/src/clj/ote/services/operators.sql, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/route/route_list.cljs
* Reduce header element bottom padding
* Fix invite users to operator sql query
* Add new small-text css element
* Remove black bottom borders from table component
* Remove black bottom borders from route list tables and own services tables
=> 165239455 ui improvements

ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/clj/ote/util/email_template.clj, ote/src/cljs/ote/app/controller/login.cljs
* Fixed translation issue in confirmation email
* Fixed stop name issue in transit visualization page
* Fixed route name selection issue when transit visualization page was opened from email
=> Small fixes

nap/docker/docker-compose.yml, ote/src/clj/ote/gtfs/kalkati_to_gtfs.clj, ote/src/clj/ote/services/transit_changes.clj
* docker: docker-compose: comment out nginx
* gtfs: kalkati-to-gtfs: set time seconds to :00 to follow gtfs spec
* services: transit-changes: force-interface-import upload zip to s3
=> 168657445 kalkati to gtfs set time seconds so gtfs specification is followed, update docker-compose to disable nginx

ote/src/clj/ote/integration/import/gtfs.clj
* integration: gtfs: cleanup code of analysis warnings and unused refs
=> integration: gtfs: cleanup code of analysis warnings and unused refs

database/src/main/resources/db/migration/V1_169__change_address_post_code.sql, database/testdata-ote.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/transport.clj, ote/src/cljc/ote/util/transport_operator_util.cljc, ote/src/cljs/ote/ui/validation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/transport_operator.cljs, ote/src/cljs/ote/views/transport_service_common.cljs, ote/test/clj/ote/db/generators.clj, ote/test/clj/ote/services/transport_test.clj, ote/test/clj/ote/util_tests.clj
* Added support for foreign postal codes (was char 5 is now varchar 10)
=> 163385823 foreign postal code

aws/ansible/environments/production/group_vars/ote/vars, aws/ansible/environments/staging/group_vars/ote/vars, aws/ansible/templates/ote/config.edn.j2, database/src/main/resources/db/migration/V1_170__netex_conversion_constraint_unique_sid_eid.sql, ote/config.edn, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/netex/netex.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/tasks/gtfs.sql, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs
* GTFS->NeTEx conversion via shell tool
* Upload output file to S3
* Update status to db netex-conversion table
Will add a unit test next and look at the todo's
=> GTFS->NeTEx conversion via chouette cmd line and uploading to S3

ote/src/cljc/ote/db/feature.cljc, ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/views/transit_visualization.cljs
* views: transit-visualization: remove unused parts fixes compile warnings
* time: remove unused joda-datetime->java-localdate to fix compile warning
* db: feature: require clojure.spec.alpha fixes compile warning
=> Fix compiler warnings and static analysis findings: views/transit-visualization, time.cljc, feature.cljc

aws/ansible/tasks/ote.yml, ote/src/clj/ote/netex/netex.clj
* aws: ansible: fix chouette zip download destination folder
=> Feature netex fix aws ansible destination folder etc.

ote/src/clj/ote/netex/netex.clj
* netex: after conversion validate chouette outputReport.json
=> netex: after conversion validate chouette outputReport.json

database/src/main/resources/db/migration/V1_171__netex_conversion_data_content.sql, ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/integration/export/netex.clj, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/netex/netex.clj, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/tasks/gtfs.sql, ote/src/cljc/ote/db/netex.cljc, ote/test/clj/ote/integration/export/geojson_test.clj
* external interface 'data-content' to netex coversion
* nap-generated netex package links to service geojson export
* export/netex endpoint for downloading netex zip
*  db: add specql for netex-conversion table's enum interface-data-content
db: netex-conversion add column 'data-content'
=> netex export to geojson, netex zip dowload service

aws/ansible/environments/staging/group_vars/ote/vars, ote/config.edn, ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/integration/export/netex.clj, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/import/ytj.clj, ote/src/clj/ote/tasks/gtfs.clj
* netex conversion feature flag variation
* :netex-conversion-automated set for local and staging
=> 169202436 feature flag for netex automated conversion

ote/src/clj/ote/services/admin.clj, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/mui_chip_input.cljs, ote/src/cljs/ote/views/admin/reports.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* tvv csv report
* mui chip input div was too shallow in pre-notice form
* Pre notice sent form: disabled text area changed to text
=> 169171640 tvv csv

ote/src/clj/ote/services/admin.sql
* services: admin: order netex conversions list by time
=> admin: order netex conversions list by time

database/src/main/resources/db/migration/V1_174__service_search_result_external_interface_id.sql, ote/src/clj/ote/integration/export/geojson.clj, ote/src/clj/ote/main.clj, ote/src/clj/ote/netex/netex.clj, ote/src/clj/ote/netex/netex_util.clj, ote/src/clj/ote/services/service_search.clj, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/admin/netex.cljs, ote/src/cljs/ote/views/service_search.cljs, ote/src/cljs/ote/views/service_viewer.cljs, ote/test/clj/ote/services/service_search_test.clj
* netex: netex_util.clj for netex-related data mangling
* views: service_viewer: netex tag to those service interfaces having it
* Some problem fixed.
* services: service-search: refactoring search handling
*  service-search: append netex urls to service interfaces 
*  netex: interface id to netex filename allows multiple s3 files per service
* db: service_search_result_external_interface_id
+ Code cleanup here and there
=> 169174702 netex tag to service search and refactoring service view netex link

ote/src/clj/ote/netex/netex_util.clj
*netex_util: refactor how to iterate appending ote netex urls
=> netex: netex_util: refactor how to iterate appending ote netex urls

ote/src/clj/ote/integration/export/geojson.clj
* integration: geojson: refactor ote-generated netex url appending
=> integration: geojson: refactor ote-generated netex url appending

ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/views/admin.cljs, ote/src/cljs/ote/views/admin/interfaces.cljs, ote/src/cljs/ote/views/admin/netex.cljs, ote/src/cljs/ote/views/admin/sea_routes.cljs, ote/src/cljs/ote/views/admin/service_list.cljs, ote/src/cljs/ote/views/admin/users.cljs
* admin view table content wrapping and minor styling tweaks
=> admin view table content wrapping and minor styling tweaks

database/src/main/resources/db/migration/V1_176__create_index_to_external_interface_download.sql, ote/src/clj/ote/netex/netex_util.clj
* db index to external-interface-download-status table
* Add check to netex file download url generation to not to generate url if there is no netex conversions.
=> 169393181 download table is missing an index

ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* views: transit-visualization: calendar code layout formatting
=> 169223029 transit visualization code formatting

database/src/main/resources/db/migration/V1_177__add_url_to_external_download_status.sql, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/views/admin/interfaces.cljs, ote/test/clj/ote/transit_changes/detection_integration_test.clj
* admin - interface tab
* Added url column to external-interface-download-status table
=> 168721862 admin interface tab

aws/ansible/environments/production/group_vars/ote/vars
=> 169447553 Add laundry url to prod env

ote/src/clj/ote/gtfs/kalkati_to_gtfs.clj, ote/src/clj/ote/tasks/gtfs.clj
* gtfs->netex by creating valid trips to gtfs package
* fixed kalkat->gtfs conversion by filtering out footnotes that are not valid
* fixed kalkati->gtfs conversion by taking into account start and end stops in stop sequences
* fixed kalati->gtfs conversion by taking into account that footnotes might not have start date
=> 169535972 kalkati to gtfs fixes

ote/project.clj, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/communication.cljs
* admin: forcedownload - change timeout 30 sek -> 7 minutes
* Update few project dependencies
=> Change admin forcedownload timeout from 30 sek to 7 minutes

aws/ansible/tasks/ote.yml, aws/ansible/templates/ote/ns-chouette.sh.j2, ote/src/clj/ote/netex/netex.clj
* aws: ansible: templates: Create sh file to call chouette using nsjail
* aws: ansible: tasks: Update ote.yml to load nsjail from github
=> 169223712 nsjail using ansible

aws/ansible/tasks/ote.yml, aws/ansible/templates/ote/ns-chouette.sh.j2
=> 169223712 Change nsjail to firejail

ote/src/clj/ote/gtfs/kalkati_to_gtfs.clj, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs
* Add timeout for few admin post requests
* gtfs: kalkati-to-gtfs: remove firststop and laststop restrictions
=> 169753987 kalkati to gtfs - changes

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/info.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/front_page.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/place_search.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_operator_selection.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Missing hr line from terminal service hours
* info-toggle
=> 169776247 hr

ote/src/cljs/ote/communication.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Missing required text from interface data type
* service view: external interfaces: to div table with new tooltips
=> 169588440 external interfaces

ote/src/clj/ote/netex/netex.clj, ote/src/clj/ote/services/routes.clj
* gtfs preprocessing: to change stops location_type to 1 (station)
* gtfs preprocessing:  to fix empty rows problem in netex conversion
=> 169673698 pre processing

ote/project.clj, ote/src/clj/ote/netex/netex.clj, ote/test/clj/ote/netex/gtfs_to_netex_test.clj, ote/test/resources/netex/46.xml
=> 169673850 post processing

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/info_style.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/ui/info.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Sea route editor help link address
* Refactored info-toggle help component
* edit-service-view: refactored all views to use new info-toggle help component
=> 169314290 help link

ote/src/cljs/ote/style/buttons.cljs, ote/src/cljs/ote/ui/buttons.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/transport_operator.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* pre-notice: make regions mandatory
* Update save, draft and cancel buttons to use icons
* Take new buttons into use in pre-notice, transport-operator, sea-routes and service views
=> 169589196 pre notice required field

ote/src/cljs/ote/app/controller/transport_operator.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/main_header.cljs
* Fixed header link when using IE11
* Fixed top-border typo from service form
=> Fixed ie11 header link and top-border

ote/resources/public/img/icons/outline-ballot-disabled-24px.svg, ote/src/clj/ote/netex/netex.clj, ote/src/cljs/ote/ui/icons.cljs, ote/src/cljs/ote/views/transit_changes.cljs
* transit-changed: Added new disabled change icon
* transit-changes: When interface didn't exist, it was communicated as "errors in interface". Fixed now with text "no interfaces"
* transit-chagnes: Changed black icons to disabled icons where disabled icon should be used.
=> 169808476 no interfaces

database/src/main/resources/db/migration/V1_178__add_service_id_to_service_search_view.sql
* Fix service search slowness due to search where interface-download query didn't use service-id
=> Fix service search slowness

ote/src/cljs/ote/app/controller/admin_validation.cljs, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* admin - service validation: 5min refresh timer added to service fetch
=> 170200926 5min refresh

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Change validation texts in service page and own services page
=> 170400662 - Change validation texts in service page and own services page

ote/src/cljs/ote/ui/icon_labeled.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/calendar.cljs, ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
* Ensure that transit visualization icon summaries gets correct parameter to show differences correctly
* icon label centering
=> 170485500 icon summaries

ote/src/clj/ote/services/transit_changes.sql
* Transit changes - upcoming changes filtered invalid interface services. This is now fixed
=> 170485398 Fix transit changes query

ote/src/cljs/ote/app/controller/own_services.cljs
* Auto refresh to own services page
=> 170470234 own services auto refresh

aws/ansible/environments/production/group_vars/ote/vars, aws/ansible/environments/staging/group_vars/ote/vars
* Memory issue by filtering out too big service
=> Add more operators to black list

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/app/controller/admin_validation.cljs, ote/src/cljs/ote/app/controller/own_services.cljs, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/theme/colors.cljs, ote/src/cljs/ote/views/admin/validate_service.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* New info text container to service page when service is in validation
* Hide duplicate (original) service from own services
=> 170596696 hide duplicate service

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/views/admin/reports.cljs
* Create new csv report from netex interfaces
=> 170101334 netex csv list

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/service_search.sql, ote/src/cljs/ote/views/pre_notices/listing.cljs
* pre-notice-list: New reports of change header for draft reports
* service-search: Removed operators from facets which do not have published services
=> 169914080 pre notice draft header

ote/project.clj, ote/src/cljs/ote/app/controller/own_services.cljs, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/ui/service_calendar_timeline.cljs, ote/src/cljs/ote/views/theme.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Change buttons order in confirm leave dialog
* transport-service: Add cancel for re-edit state
* Take alpha versio from http-kit into use
=> 170744727 cancel service

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/main_header.cljs
* Add privacy policy links to correct translated versions
=> 170794680 Add privacy policy links to correct translated versions

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/service_viewer.cljs, ote/src/cljs/ote/views/service_viewer.cljs
* Add service-hour-info description to service view
* Change terms of service url
=> 170743385 service view service hour info

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/transport_service_common.cljs
* transport-service: Added new netex info texts to external interfaces section. Texts are enabled if netex flag is on.
=> 170792503 netex texts

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/parking.cljs, ote/src/cljs/ote/views/passenger_transportation.cljs, ote/src/cljs/ote/views/rental.cljs, ote/src/cljs/ote/views/terminal.cljs, ote/src/cljs/ote/views/transport_service.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* transport-service -page: New fi texts to warn users
* transport-service -page: New warning/confirmation container when saving 
* transport-service -page: New footer element which is similar to sea routes form
* transport-service -page: Update footer button placements
* Removed unused texts from own-services -page
=> 170921075 service footer

aws/ansible/environments/production/group_vars/ote/vars, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/ui/form.cljs, ote/src/cljs/ote/views/transport_service_common.cljs
* Take validation into use in production
* transport-service page: Add new confirm dialog when changing service to draft mode
* Added translations to service validation
=> 170467849 validation translations and flag

ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/cljs/ote/views/admin/reports.cljs
* admin report: associated companies csv report
=> New admin report: associated companies

ote/src/cljs/ote/views/own_services.cljs
* own-services page: Fix validate icon visibility when interface has warning icon
=> 171128052 own service page - validate icon

ote/src/cljs/ote/views/front_page.cljs
* front-page: button link too wide: Wrapped front page buttons to fixed size div
=> 170765116 Front Page link too wide

ote/src/cljs/ote/views/own_services.cljs
* own-services -page: Add overflow visible to table body wrapper to fixi e11 overflow issue
=> 171145186 own services - ie 11 overflow issue

ote/src/clj/ote/services/service_search.sql
* service search: change service ordering from modified to published
=> 171203716 service search order by to published

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/import/import_gtfs.sql, ote/src/clj/ote/services/pre_notices/attachments.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_changes.sql
* admin upload gtfs: Fixed interface id when service has multiple interfaces
* transit changes: import first package from different interface fixed
=> 171126160 first package and upload issues

ote/src/clj/ote/services/transit_visualization.sql
* transit-visualization page: Speed up route date hashes query
=> 171226192 - Speed up route date hashes query

ote/src/clj/ote/services/transport_operator.clj
*  invite users: increase invite expiration date from 1 day to 62 days
=> 171045535  increase user invite expiration

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/main.cljs, ote/src/cljs/ote/views/own_services.cljs, ote/src/cljs/ote/views/transport_service/parking.cljs, ote/src/cljs/ote/views/transport_service/passenger_transportation.cljs, ote/src/cljs/ote/views/transport_service/rental.cljs, ote/src/cljs/ote/views/transport_service/service_type.cljs, ote/src/cljs/ote/views/transport_service/terminal.cljs, ote/src/cljs/ote/views/transport_service/transport_service.cljs, ote/src/cljs/ote/views/transport_service/transport_service_common.cljs
* transport-service view: Add translation tags for new service header section
* transport-service view: Update header section according to ui specifications
* Refactor service related files to their own folder
=> 170722711 service header

database/src/main/resources/db/migration/R__GTFS_query.sql, ote/resources/public/css/styles.css, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/clj/ote/transit_changes/detection.clj, ote/src/clj/ote/transit_changes/detection.sql, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/ui/table.cljs, ote/src/cljs/ote/views/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/gtfs_package_info.cljs, ote/test/clj/ote/transit_changes/detection_integration_test.clj, ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* change detection: Stop storing history date hashes
* transit-visualization page: Move gtfs-package-info codes to own file
* transit-visualization page: Add gtfs-transit-changes data
* common ui: Create new html-table component
=> 171380050 remove first package exception

ote/src/clj/ote/services/transport_operator.clj, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/src/cljs/ote/views/transport_service/transport_service.cljs
* transport service page: Added operator name even when admin is viewing service
=> 170722711 service header changes

aws/ansible/ote.yml, aws/ansible/tasks/ote.yml
* Take java 13 into use in ote servers
=> 170049544 java13

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/gtfs_viewer.cljs, ote/src/cljs/ote/views/main.cljs
* gtfs-viewer: Fix nan stoptimes
* Add translations
* Take page-controls into use
=> 171835219 nan stop times

ote/src/cljs/ote/ui/mui_chip_input.cljs, ote/src/cljs/ote/views/place_search.cljs
* pre-notice: auto-complete/chip-input - add max-height to fix overflow
* service view - place search: auto-complete/chip-input - add max-height to fix overflow
=> 171997725 - auto-complete overflow

ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/views/transit_visualization/change_icons.cljs, ote/src/cljs/ote/views/transit_visualization/transit_visualization.cljs
*  transit-changes page: Fix stop difference indication by calculating stop differences when trip is selected.
=> 171105177 - indicate stop differences

ote/src/cljs/ote/style/form.cljs, ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/transport_service/parking.cljs, ote/src/cljs/ote/views/transport_service/transport_service_common.cljs
* transport-service view: Added service hour labels
=> 171969509 service hour labels

database/src/main/resources/db/migration/V1_187__add_netex_error.sql, ote/src/clj/ote/netex/netex.clj, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/admin.sql, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/tasks/gtfs.sql, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/views/admin/admin.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs, ote/src/cljs/ote/views/admin/netex.cljs, ote/test/clj/ote/netex/gtfs_to_netex_test.clj
* netex conversion: Added two columns to store input and validation file errors
* admin - netex: Added links to enable error download
=> 171204161 save netex errors to db

.circleci/Dockerfile, database/Dockerfile, database/devdb_clean.sh, database/devdb_clean_docker.sh, database/devdb_down.sh, database/devdb_migrate.sh, database/devdb_rewrite_db_template.sh, database/devdb_simple_migrate.sh, database/devdb_testdata.sh, database/devdb_up.sh, database/finap_backup.sh, database/finap_backup_docker.sh, database/finap_backupdump_to_docker_db.sh, database/query_logging.sh, nap/docker/README.md, nap/docker/docker-compose.yml
* Update docker napotedb to use postgres 11
=> Update napotedb to postgres 11

ote/src/clj/ote/services/transport.clj
* saving transport service: Modified timestamp and modified-by user id were not saved when editing service due to validation process. Now both columns are updated correctly.
=> save transport service - add modified and modified-by

ote/src/cljs/ote/views/service_viewer.cljs
* service-viewer: Add pick-up-type to pick-up-locations segment
=> 172219465 - service-viewer - pick-up-type

ote/src/cljc/ote/time.cljc, ote/src/cljs/ote/views/transit_visualization/transit_changes.cljs
* transit-changes page: Add new error message when traffic is ended
=> 171852765  - transit change - traffic ending

ote/src/clj/ote/util/email_template.clj
* email-template: Change blue email button to blue border button
=> 170470919 - Change blue email button

ote/src/cljs/ote/ui/form_fields.cljs, ote/src/cljs/ote/views/transport_service/rental.cljs
* transport-service view: Rental services had wrong button for price classes
* transport-service view: Rental services price class dialog had wrong title
* transport-service view: Fixed rental services price class dialog ui issues
=> 173909277 Fix price class dialog issues in rental services form

ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/transit_changes/detection.clj, ote/src/clj/ote/transit_changes/detection.sql, ote/test/clj/ote/transit_changes/detection_test_route_end.clj, ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* Fix used gtfs package: Create own trip query for detection and for calendar
=> 173659145 change detection query changes

ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/transit_changes/detection.clj, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs
* Admins can start change detection on a given day even if day is in the past.
* Fix historic change detection package query
=> 174987587 Add new service for admins

ote/src/cljc/ote/transit_changes.cljc
=> Remove fixed first common stop if there arent any to found

ote/src/clj/ote/services/transit_visualization.clj, ote/src/clj/ote/services/transit_visualization.sql, ote/src/cljc/ote/transit_changes.cljc, ote/src/cljs/ote/app/controller/transit_visualization.cljs, ote/src/cljs/ote/ui/table.cljs
* transit-visualization page: Remove no-change type of changes from calendar change list
=> 175140356 old detection in change detection results

ote/src/cljs/ote/ui/form_fields.cljs
* Fixed form element date picker locale
=> 171491127 date picker locale

ote/src/clj/ote/services/pre_notices/attachments.clj, ote/src/clj/ote/services/transport.clj, ote/src/cljs/ote/app/controller/transport_service.cljs
And add simple file encode check
=> Add db-file-key to tmp company csv

.gitignore, database/devdb_clean.sh, database/devdb_migrate.sh, database/devdb_testdata.sh, ote/resources/public/language/fi.edn
* Use container internal service name for testdata database host instead of MacOS specific localhost resolver
* fix repository references for database migration scripts
* remove duplicate clj-kondo/ entry
=> New developer modifications

ote/resources/public/css/styles.css, ote/src/clj/ote/services/index.clj, ote/src/clj/ote/util/email_template.clj, ote/src/cljs/ote/style/base.cljs, ote/src/cljs/ote/style/form.cljs, ote/src/cljs/ote/style/front_page.cljs, ote/src/cljs/ote/style/topnav.cljs, ote/src/cljs/ote/style/transit_changes.cljs
* Changed topnav background color to black.
* Changed topnav dropdown background color to black.
* Changed footer background color to black.
* Changed primary font to Public Sans.
=> Finap 14/colors fonts layout

ote/src/clj/ote/services/index.clj
* Regenerated Public Sans font import statement to include all valid weights and variants
=> FINAP-12: regenerated font import directive to include all variants

ote/src/cljs/ote/style/topnav.cljs
Change the background color of terms of service container to #0034ac.
The color #0034ac is dark blue (tummansininen).
=> Change the background color of terms of service container to #0034ac

ote/resources/public/css/styles.css, ote/src/cljs/ote/style/page.cljs, ote/src/cljs/ote/style/topnav.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/gtfs_viewer.cljs, ote/src/cljs/ote/views/pre_notices/pre_notice.cljs, ote/src/cljs/ote/views/route.cljs, ote/src/cljs/ote/views/transport_service/transport_service.cljs
=> FINAP-12/layout adjustments and fixes

ote/src/cljs/ote/style/front_page.cljs, ote/src/cljs/ote/style/topnav.cljs, ote/src/cljs/ote/theme/colors.cljs
* Parametrized brand colors.
* Use parametrized brand colors on front page in header.
* Use parametrized brand colors on front page in buttons.
=> Finap 14/colors

ote/src/cljs/ote/style/front_page.cljs
* Change front page lower section box shadow alpha value to 0.25.
* Adjust parameters of linear gradient of lower section background image.
* Adjust box shadow parameters of lower section.
=> FINAP-14/lower section

ote/src/cljs/ote/style/footer.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/footer.cljs, ote/src/cljs/ote/views/main.cljs
* FINAP-13 new footer
* FINAP-15 social media links
---
=> FINAP-8/new footer and social media links

ote/src/cljs/ote/views/pre_notices/listing.cljs
* Use primary button type for "Add new report of change" button.
=> Use primary button type for "Add new report of change" button.

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
bits and pieces from eg. demo and such
=> FINAP-12/final touches

ote/src/cljs/ote/style/footer.cljs
* Footer CSS was broken by tidy-up in another branch
=> Fix error in CSS which caused page to render incorrectly

cypress/integration/operator_spec.js, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/util/email_template.clj, ote/test/clj/ote/services/login_test.clj
This is just a simple search&replace, translation updates and eg. phone numbers will follow separately.
* Replace all nap@traficom.fi references with nap@fintraffic.fi
=> Replace all nap@traficom.fi references with nap@fintraffic.fi

ote/src/clj/ote/services/index.clj
* cookieinformation consent popup
---
No other changes, lets take this step by step.
=> add cookieinformation consent popup/iframe to page

ote/src/cljs/ote/style/footer.cljs, ote/src/cljs/ote/views/footer.cljs
* add feedback email back directly to footer
=> add feedback email back directly to footer

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/service_search.cljs
* old blue topbar TOS is entirely removed, services search has an additional TOS notification text
=> FINAP-5/remove localstorage tos

ote/resources/public/language/fi.edn, ote/src/cljs/ote/style/front_page.cljs, ote/src/cljs/ote/views/front_page.cljs
* Traficom infobox to front page
---
=> FINAP-9/add Traficom infobox

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
* navigation alert translations
=> FINAP-22/English and Swedish translations for the popup

ote/resources/public/language/en.edn, ote/resources/public/language/sv.edn
* Swedish and English translations for Traficom notification box on the front page
=> FINAP-9/Swedish and English translations

ote/resources/public/css/taxiui/normalize.css, ote/resources/public/css/taxiui/styles.css, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/taxi_index.clj, ote/src/cljs/ote/main.cljs, ote/src/cljs/ote/theme/colors.cljs, ote/src/cljs/taxiui/app/controller/front_page.cljs, ote/src/cljs/taxiui/app/routes.cljs, ote/src/cljs/taxiui/styles/front_page.cljs, ote/src/cljs/taxiui/views/front_page.cljs, ote/src/cljs/taxiui/views/main.cljs
This is a bit copy-pastey in places, but the assumption is that most of those will be refactored out eventually. For example the new base page root is a direct copy-paste which reuses NAPOTE header and footer, but those will not exist anymore once the actual implementation starts.
* TaxiUI base
=> FINAP-64/Create TaxiUI secondary frontend application and needed forking logic to enable the development of it

ote/resources/public/css/styles.css, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/ote/views/footer.cljs, ote/src/cljs/ote/views/front_page.cljs
* EU flag and funding notification
---
=> FINAP-8/EU flag and funding notification

ote/resources/public/css/taxiui/styles.css, ote/src/clj/ote/services/places.clj, ote/src/clj/ote/services/places.sql, ote/src/cljs/taxiui/app/controller/pricing_details.cljs, ote/src/cljs/taxiui/app/controller/stats.cljs, ote/src/cljs/taxiui/app/routes.cljs, ote/src/cljs/taxiui/styles/front_page.cljs, ote/src/cljs/taxiui/styles/pricing_details.cljs, ote/src/cljs/taxiui/views/components/forms.cljs, ote/src/cljs/taxiui/views/components/pill.cljs, ote/src/cljs/taxiui/views/front_page.cljs, ote/src/cljs/taxiui/views/login.cljs, ote/src/cljs/taxiui/views/pricing_details.cljs
* basics for searching places and inserting pricing information
=> FINAP-60/area code based search

database/src/main/resources/db/migration/V1_191__create_taxi_service_prices.sql
* Create taxi_service_identifier PostgreSQL enum type.
* Create taxi_service_prices database table.
=> FINAP-60/Create taxi_service_prices database table.

ote/src/cljs/taxiui/views/front_page.cljs
=> FINAP-64/remove infobox for company information, this will reappear later with the YTJ integration

database/src/main/resources/db/migration/R__list_taxi_pricing_statistics.sql, ote/resources/public/language/fi.edn, ote/src/clj/ote/services/taxiui_service.clj, ote/src/cljs/taxiui/views/stats.cljs
Example price column for each service.
=> FINAP-61/example price column

database/src/main/resources/db/migration/R__list_taxi_pricing_statistics.sql, ote/resources/public/language/fi.edn, ote/src/clj/ote/services/taxiui_service.clj, ote/src/clj/ote/services/taxiui_service.sql, ote/src/cljs/taxiui/app/controller/stats.cljs, ote/src/cljs/taxiui/views/stats.cljs
Under six months, within a year, over a year ago filter for filtering ages.
The SQL horror expands, now there's query filters on three levels 😈
=> FINAP-62/price update age filter

ote/src/cljs/taxiui/app/controller/pricing_details.cljs, ote/src/cljs/taxiui/app/controller/stats.cljs, ote/src/cljs/taxiui/app/routes.cljs
Minor nice-to-have, clears page specific entry from app db to keep the data structure more compact and less data in local storage in general.
=> FINAP-64/router improvements

ote/src/cljs/ote/views/footer.cljs
* Change the link of privacy policy in Finnish ("Tietosuoja") in footer.
=> FINAP-105/Change the link of Finnish privacy policy ("Tietosuoja").

ote/resources/public/language/fi.edn, ote/src/clj/ote/services/taxiui_service.clj, ote/src/clj/ote/services/taxiui_service.sql, ote/src/cljs/taxiui/views/components/forms.cljs, ote/src/cljs/taxiui/views/stats.cljs
This is quite a bit simpler than envisioned, and only matches one area at any given time. This is mostly a time saving optimization, and can be improved later on.
=> FINAP-62/create area-filter for reducing amount of results

ote/src/cljs/taxiui/app/routes.cljs
=> FINAP-64/make stats page require authentication

ote/resources/public/language/fi.edn, ote/src/cljs/ote/app/utils.cljs, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/transport_service/passenger_transportation.cljs, ote/src/cljs/ote/views/transport_service/transport_service_common.cljs, ote/src/cljs/taxiui/app/controller/front_page.cljs, ote/src/cljs/taxiui/app/routes.cljs, ote/src/cljs/taxiui/views/main.cljs
Start linking from NAPOTE UI to Taxi UI
=> FINAP-64/links to taxiui

ote/resources/public/language/fi.edn, ote/src/clj/ote/services/taxiui_service.clj, ote/src/clj/ote/services/taxiui_service.sql, ote/src/cljs/taxiui/app/controller/front_page.cljs, ote/src/cljs/taxiui/styles/front_page.cljs, ote/src/cljs/taxiui/views/front_page.cljs
Real data is always nicer than fake data.
=> FINAP-64/front page data binding

database/src/main/resources/db/migration/R__list_taxi_pricing_statistics.sql, database/src/main/resources/db/migration/V1_195__taxi_prices_approval_status.sql, ote/src/clj/ote/services/taxiui_service.clj, ote/src/clj/ote/services/taxiui_service.sql, ote/src/cljs/ote/app/controller/admin.cljs, ote/src/cljs/ote/app/controller/taxi_prices.cljs, ote/src/cljs/ote/ui/tabs.cljs, ote/src/cljs/ote/views/admin/admin.cljs, ote/src/cljs/ote/views/admin/reports.cljs, ote/src/cljs/ote/views/admin/taxi_prices.cljs
Simple publishing process and admin UI for taxi prices
=> FINAP-107/price publishing controls

ote/resources/public/css/taxiui/styles.css, ote/src/cljs/taxiui/styles/front_page.cljs, ote/src/cljs/taxiui/styles/pricing_details.cljs, ote/src/cljs/taxiui/theme.cljs, ote/src/cljs/taxiui/views/components/forms.cljs, ote/src/cljs/taxiui/views/front_page.cljs, ote/src/cljs/taxiui/views/pricing_details.cljs
Making it look more like envisioned. Slightly WIP?
=> FINAP-64/layout prettification

ote/src/clj/ote/services/taxiui_service.sql
That's a mouthful for a header...anyway, it says what's up.
=> FINAP-64/unroll parts of the query to adjust how prices are fetched so that the front page always populates as many entries as possible

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
This should be all of them. Please cross check :)
=> Finap 64/translations

database/src/main/resources/db/migration/R__list_taxi_pricing_statistics.sql, database/src/main/resources/db/migration/V1_196__rename_accessibility_service_columns.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/taxiui_service.clj, ote/src/clj/ote/services/taxiui_service.sql, ote/src/cljs/taxiui/app/controller/pricing_details.cljs, ote/src/cljs/taxiui/views/pricing_details.cljs
Assistance/Accessibility field renames as requested by Traficom and related translations
=> Rename columns as requested by Traficom

ote/src/clj/ote/services/login.clj, ote/src/clj/ote/services/transport_operator.clj, ote/src/cljs/ote/app/controller/authority_group_admin.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/admin/admin.cljs, ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
Menu and feature visibility updates based on the newly refreshed group permission logic.
=> FINAP-53/use groups to limit visibilities

ote/project.clj, ote/src/cljs/ote/app/controller/login.cljs, ote/src/cljs/ote/app/state.cljs
some cleanup and more adjusting to initial app state loading
=> FINAP-53/cleanup

ote/src/clj/ote/services/transport_operator.clj
Being too fast isn't always good.
=> fix typo in variable name

ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/services/transit_changes.sql, ote/src/cljs/ote/app/controller/admin_transit_changes.cljs, ote/src/cljs/ote/views/admin/detected_changes.cljs
fix filters, limit results to latest only to avoid overloading the UI
=> FINAP-39/limit gtfs reports to latest

ote/src/clj/ote/services/transit_changes.clj, ote/src/cljs/ote/views/admin/detected_changes.cljs
some styling adjustments and maybe finally a solid fix for the checkbox magic
=> FINAP-39/admin view adjustments

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/taxiui/app/controller/loader.cljs, ote/src/cljs/taxiui/app/controller/pricing_details.cljs, ote/src/cljs/taxiui/views/components/link.cljs, ote/src/cljs/taxiui/views/components/loader.cljs, ote/test/clj/ote/integration/import/gtfs_test.clj
=> show fancy save confirmation splash message on saving fare information

ote/src/clj/ote/integration/import/gtfs.clj
adjust error reporting based on production feedback
=> FINAP-39/handle 304 and no new package correctly

ote/src/clj/ote/netex/netex.clj
=> fix validation-report-file reference for gtfs import report logging

database/src/main/resources/db/migration/V1_199__link_report_to_specific_ext_interface.sql, ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/report.clj, ote/src/clj/ote/netex/netex.clj, ote/src/cljc/ote/gtfs/parse.cljc, ote/src/cljs/ote/views/admin/detected_changes.cljs
Some refactoring and admin view improvements to test hypothesis about interface ids causing package duplication.
=> FINAP-39/admin view improvements and refactorings

ote/src/clj/ote/services/taxiui_service.clj
This check wasn't hit during testing because all testers were admins.
=> coerce operator-id to long before checking authorization to ensure the hash-based check actually works

ote/src/clj/ote/integration/report.clj, ote/src/clj/ote/integration/report.sql, ote/src/clj/ote/tasks/gtfs.clj
=> fix problems not noticed because of dirty REPL session

ote/src/clj/ote/main.clj, ote/src/clj/ote/services/transit_changes.clj, ote/src/clj/ote/tasks/gtfs.clj
This faulty DI was the reason automated import process hasn't worked for a few days.
=> unroll custom macro to enable correct dependency injection

ote/src/cljs/ote/ui/main_header.cljs
Add customer provided link to header navigation.
=> add link to announcements

ote/src/clj/ote/integration/export/gtfs_flex.clj, ote/src/cljc/ote/gtfs/parse.cljc, ote/src/cljc/ote/gtfs/spec.cljc, ote/src/cljc/ote/gtfs/transform.cljc, ote/src/cljc/ote/util/transport_operator_util.cljc, ote/src/cljs/ote/views/admin/detected_changes.cljs
=> FINAP-80/gtfs flex generate infinite timetables

ote/src/clj/ote/integration/export/gtfs.clj, ote/src/clj/ote/integration/export/gtfs_flex.clj
=> FINAP-80/gtfs flex prod data adjustments

ote/src/clj/ote/services/taxiui_service.clj, ote/src/clj/ote/services/taxiui_service.sql
=> FINAP-14/update all previous unapproved pricings in one go to avoid the need to mark everything one-by-one as approved in admin ui

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/netex/netex.clj, ote/src/clj/ote/tasks/gtfs.clj, ote/src/clj/ote/util/email_template.clj, ote/src/cljs/ote/views/service_viewer.cljs
Bunch of minor tunings and adjustements based on customer feedback.
=> FINAP-80/minor changes

aws/ansible/ote.yml, aws/ansible/tasks/ote.yml
Get the latest&greatest LTS with all the patches and improvements.
=> Update from Java 13.0.2 to 17.0.3

ote/src/clj/ote/netex/netex.clj, ote/src/cljs/ote/app/controller/transport_service.cljs, ote/test/clj/ote/netex/netex_test.clj
=> FINAP-144/service companies csv listing reupload

database/src/main/resources/db/migration/R__list_taxi_pricing_statistics.sql, ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/services/admin.clj, ote/src/cljs/ote/app/controller/service_viewer.cljs, ote/src/cljs/ote/views/service_viewer.cljs
All stats views now show operating areas on municipality level to make analysis and comparisons easier.
=> FINAP-153/normalize taxi operating areas to municipality level

database/src/main/resources/db/migration/V1_203__add_taxi_related_indices.sql
this column is used a lot in queries
=> add index for checking whether taxi price is already approved or not

ote/src/cljs/ote/app/controller/service_viewer.cljs
Some parenthesis fiddling to get prices to render correctly again.
=> fix invalid conditional branch logic to actually insert API response to internal state

ote/src/clj/ote/tasks/gtfs.clj
=> ignore no result exception produced by psql

ote/src/clj/ote/integration/export/gtfs.clj, ote/src/cljc/ote/gtfs/parse.cljc, ote/src/cljc/ote/gtfs/spec.cljc, ote/src/cljc/ote/gtfs/transform.cljc
Basic support for generating GTFS translations.txt, will be expanded soon in subsequent PRs.
=> FINAP-173/add support for gtfs translations txt

ote/src/cljc/ote/gtfs/transform.cljc
User might manage to input values such as
```
This is a
bus stop.
```
which breaks CSV based formats. This should fix the issue on multiple levels.
=> FINAP-196: sanitize few user-inputtable fields to prevent breaking CSV export

ote/src/cljs/ote/views/service_viewer.cljs, ote/src/cljs/ote/views/transport_service/passenger_transportation.cljs, ote/src/cljs/ote/views/transport_service/transport_service_common.cljs
This is a conglomeration of old functionality combined with the newish Taxi UI. Hopefully this won't be too confusing for the end user.
=> FINAP-199: rework pricing ui elements to show available payment methods, website link and description for taxis as well

ote/src/clj/ote/tasks/tis.clj
=> FINAP-209/fix key lookup

ote/src/clj/ote/tasks/tis.clj
This was a silly oversight on my part.
=> add locking to avoid double execution

ote/src/clj/ote/integration/import/gtfs.clj, ote/src/clj/ote/integration/tis_vaco.clj, ote/src/clj/ote/tasks/tis.clj, ote/src/cljs/ote/app/controller/transport_service.cljs
More adjustments to the integration now that VACO API is stabilizing.
=> TIS-495/run vaco integration task separately

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/cljs/taxiui/views/stats.cljs
translations done from fi->{en,sv} with DeepL
=> FINAP-220/change the wording of example trip slightly and put description text on the taxi ui stats page

database/src/main/resources/db/migration/V1_209__add_rental_booking_fk_cascade.sql
This got erased in git sync by accident.
=> FINAP-215/modify rental_booking's foreign key to be cascadeable

ote/src/clj/ote/tasks/tis.clj
This needs more thinking in the future, as it is format specific
=> FINAP-221/hardcode conversion result name

ote/src/clj/ote/integration/tis_vaco.clj, ote/src/clj/ote/tasks/tis.clj, ote/src/clj/ote/tasks/tis.sql
This will be used to send notification emails to org/service admin
=> TIS-232/add contact email to TIS API call

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn, ote/src/clj/ote/main.clj, ote/src/clj/ote/services/admin.clj, ote/src/clj/ote/services/health.clj, ote/src/clj/ote/services/health.sql, ote/src/clj/ote/services/reports.sql, ote/src/clj/ote/tasks/tis.sql, ote/src/cljs/ote/ui/common.cljs, ote/src/cljs/ote/ui/main_header.cljs, ote/src/cljs/ote/views/admin/reports.cljs, ote/src/cljs/ote/views/footer.cljs
Fixes FINAP-237, FINAP-240,  FINAP-241, FINAP-235, FINAP-174, FINAP-239
=> August fixes

ote/src/cljc/ote/util/tis_configs.cljc
=> add netex2gtfs for NeTEx feeds since some systems still rely on GTFS

aws/ansible/tasks/ote.yml
FTCLOUDS-2674 - enable ec2-imdsv2-support
=> Use aws_ec2_module to guery IMDSv2 ec2 metadata

aws/ansible/podman.yml
https://solita.atlassian.net/issues/FINAP-15
=> Finap 15/enabling lingering for jenkins podman

aws/ansible/podman.yml
FINAP-18 - update podman service file for simple mode and handle restarts
=> update podman service file

aws/ansible/podman.yml, database/Dockerfile, database/devdb_clean.sh, database/devdb_clean_docker.sh, database/devdb_down.sh, database/devdb_migrate.sh, database/devdb_rewrite_db_template.sh, database/devdb_simple_migrate.sh, database/devdb_testdata.sh, database/devdb_up.sh, database/finap_backup.sh, database/finap_backup_docker.sh, database/finap_backupdump_to_docker_db.sh, database/query_logging.sh, database/src/main/resources/db/migration/V1_141__remove_foreign_key_from_detected_routes.sql, nap/docker/README.md, nap/docker/docker-compose.yml, ote/src/clj/ote/services/admin.sql
Updating all relevant files to support postgresql 16.3 version.
Database update is simple:
- Drop detected-route-change_transit-change-date_fkey and gtfs_package_transport-service-id_fkey foreinkeys.
- Update 141 migration file
- Update vhecksum to schema_version table 
- Update database via AWS Console.
Those changes are hard to find from this pr.
Allmos all change changes are related to local docker update.
=> Finap 260 postgres update

ote/resources/public/language/en.edn, ote/resources/public/language/fi.edn, ote/resources/public/language/sv.edn
Add Discontinue info in english about MeriRAE
=> FINAP-251 - Add Discontinue info in english about MeriRAE

ote/src/clj/ote/tasks/gtfs.clj
Tämä voidaan mergetä, kunhan edelliset pr:t on ensin viety tuotantoon
=> Disable nightly change detection

ote/src/clj/ote/tasks/taxiui.clj
This is intended just to be tested in the staging environment
=> FINAP-290 Reschedule taxiui reminder emails for the 11th
