tmfg/mmtis-national-access-point

- nap/docker/redis/Dockerfile
This hasn't been added to Docker hub yet.
You can start it using command:
docker run -p 6379:6379 napoteredis
> NAP-56 Dockerfile for redis Docker container

- ote/config.edn
- ote/src/clj/ote/components/http.clj
- ote/src/clj/ote/nap/cookie.clj
CKAN uses mod_auth_tkt style cookie and OTE application must integrate to it. Add code to parse and verify "auth_tkt" cookie and a Ring middleware to enforce a check.
> NAP-60 Add mod_auth_tkt format cookie check

- nap/docker/.env
- nap/docker/docker-compose.yml
- nap/docker/nginx/Dockerfile
- nap/docker/nginx/proxy.conf
This feature adds a new docker container for nginx.
NGINX serves ckan and ote under a single host localhost:8080.
Local CKAN is accessible through localhost:8080/ and OTE is accessible through localhost:8080/ote/index.html (if ote server is running).
> Nginx docker

- nap/docker/ckan/Dockerfile
- nap/docker/ckan/ckan-entrypoint.sh
- nap/docker/docker-compose.yml
This pull request allows the team to develop ckan plugins more easily without running any additional scripts or tools. Additionally, some centos package install errors are now fixed in the ckan container.
Changes to local ckan plugin files are automatically detected by the napote-ckan container and the plugin will be updated if plugin files are moved, edited, added or removed. 
Changes to the ckan template are visible after refreshing the web browser.
> NAP 137 - Ckan plugin dev environment

- nap/docker/ckan/ckan-entrypoint.sh
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/plugin.py
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/package/read.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/package/snippets/package_basic_fields.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/package/snippets/package_metadata_fields.html
This pull request will add the following new features for the ckan theme plugin:
* Two custom mandatory datafields for the dataset creation form: Transport service type and operation area.
* Display the selected field values on the dataset info page.
* Two custom facet categories for the datasets page: Transport Service Type and Operation Area.
> NAP-141 CKAN custom dataset fields

- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/.gitignore
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/data/README.md
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/plugin.py
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/setup.py
Using finnish_municipalities.csv data in operation areas custom fields in our ckan plugin.
The finnish_municipalities.csv file must be copied into .../napote_theme/data directory.
> Load operation areas data for customized ckan field from csv file.

- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/fanstatic/napote_theme.css
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/header.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/home/layout1.html
Updating CKAN plugin templates and styles to conform with the newest UI proto.
* Note for later development: Strings "Tietoaineistot" and "Aloitussivu" are not yet changed to "Palvelukatalogi" or "Etusivu" in the template files. We will change the finnish translation of "Datasets" to "Palvelukatalogi" and so on, but that requires generating custom translation files for this plugin. That should be a different ticket, due the amount of work required. 
Additionally, we should use english as the base language in our template files, so we don't get strange mixed language translation files when we eventually generate them. 
This is not a blocker for this pull request, as this mainly concerns template style changes. The text string fixes and translating will be a separate ticket.
> NAP-207 CKAN styles update

- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/about.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/snippets/transport_operator_view.html
- ote/src/clj/ote/services/localization.clj
- ote/src/clj/ote/services/transport.clj
- ote/src/cljs/ote/app/controller/ckan_org_viewer.cljs
- ote/src/cljs/ote/main.cljs
- ote/src/cljs/ote/views/ckan_org_viewer.cljs
This pull request adds:
* Custom CKAN template for Organization info tab that embeds OTE  app in a org-view mode.
* OTE org view component shows basic organization data, styled with CKAN supported styles
> NAP 176 Embed OTE in CKAN org info view

- database/src/main/resources/db/migration/V1_14__service_search_view.sql
- ote/project.clj
- ote/resources/public/language/fi.edn
- ote/src/clj/ote/main.clj
- ote/src/clj/ote/services/service_search.clj
- ote/src/clj/ote/services/service_search.sql
- ote/src/cljc/ote/db/service_search.cljc
- ote/src/cljc/ote/db/transport_service.cljc
- ote/src/cljc/ote/localization.cljc
- ote/src/cljs/ote/app/controller/service_search.cljs
- ote/src/cljs/ote/app/routes.cljs
- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/style/form.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/main.cljs
- ote/src/cljs/ote/views/service_search.cljs
A new custom search page that can be used instead of the
CKAN default dataset page.
Supports our two facets: service type and operation area as well as free text search on name.
> 152670109 Better service search page

- TODO.md
- ote/resources/public/css/omat_tyylit.css
- ote/resources/public/language/fi.edn
- ote/src/cljs/ote/views/ckan_org_viewer.cljs
- ote/src/cljs/ote/views/front_page.cljs
- ote/src/cljs/ote/views/main.cljs
- ote/src/cljs/ote/views/transport_service.cljs
Remove 2 pages from OTE.
Now "Omat palvelutiedot" page opens transport service type selection page automatically if no transport services are added to ote.
I also added cursor element for header links and translated one title in organization viewer.
> 152791688 remove frontpages

- ote/resources/public/language/fi.edn
Fix some translations. Use "verkko-osoite" instead of "osoite" in context of service urls.
> 152797249 Make service url related translations more easily understandable.

- database/src/main/resources/db/migration/v1_18__other_sub_type.sql
- ote/resources/public/language/fi.edn
- ote/src/cljc/ote/db/transport_service.cljc
- ote/src/cljs/ote/app/controller/transport_service.cljs
- ote/src/cljs/ote/views/transport_service.cljs
Add Muu kutsuun perustuva liikenne transport service sub type to database and to ui.
Ensure that same sub types are used in search page, passenger-tranportation form and service type selection page.
> Muu kutsuun perustuva liikenne

- database/src/main/resources/db/migration/V1_20__cascade_service_delete.sql
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/plugin.py
- ote/resources/public/language/fi.edn
- ote/src/clj/ote/nap/ckan.clj
- ote/src/clj/ote/nap/publish.clj
- ote/src/clj/ote/services/transport.clj
- ote/src/cljs/ote/app/controller/transport_service.cljs
- ote/src/cljs/ote/views/front_page.cljs
When deleting a published service, call CKAN API to do the delete (via "dataset_purge" API call) which cascades to all OTE resources.
When deleting an unpublished, delete from OTE database directly.
> 152884765 Fix service delete and add confirmation

- ote/src/cljs/ote/views/transport_service_common.cljs
Form `disable-save?` checks that form is valid and has been modified. We don't need to check for modification, so changed the check to just use `can-save?`
> 152797367 Don't require modification for save

- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/header.html
- ote/src/cljs/ote/views/main.cljs
Hide "Omat palvelutiedot" header menu item from logged out users in CKAN and OTE.
> 152924732 header tuning

- ote/src/clj/ote/services/transport.clj
**Remove limit that breaks our JOIN**
We are already filtering by explicit ID, no need to limit as it limits
the row count (returning only 1 joined entity)
> 152797727 Fix external interface fetching

- ote/src/cljs/ote/app/controller/front_page.cljs
- ote/src/cljs/ote/ui/debug.cljs
- ote/src/cljs/ote/ui/validation.cljs
- ote/src/cljs/ote/views/ckan_org_editor.cljs
- ote/src/cljs/ote/views/ckan_org_viewer.cljs
- ote/src/cljs/ote/views/ckan_service_viewer.cljs
- ote/src/cljs/ote/views/main.cljs
- ote/src/cljs/ote/views/theme.cljs
- ote/src/cljs/ote/views/transport_operator.cljs
The `theme` component is the main app container all entrypoints use. That now contains the debug state and flash-message support so that we can define it only once.
**Add phone number regex**
**Refactor form**
**Have theme container provide common parts: flash-message and debug state**
> 153097659 Save notification

- ote/src/cljc/ote/util/values.cljc
- ote/src/cljs/ote/app/controller/transport_service.cljs
- ote/src/cljs/ote/ui/form.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/ckan_service_viewer.cljs
- ote/src/cljs/ote/views/parking.cljs
- ote/src/cljs/ote/views/passenger_transportation.cljs
- ote/src/cljs/ote/views/rental.cljs
- ote/src/cljs/ote/views/terminal.cljs
- ote/src/cljs/ote/views/transport_service_common.cljs
Support new `:prepare-for-save` key for a form schemas that allows for processing before sending values to the server. This is useful because most tables want to add post processing that removes empty values.
**Move effectively-empty? to new util ns**
**Fix values ns require**
**Force table to have one row, don't allow adding if last row is empty**
**Ignore some keys, add without-empty-rows helper**
**Fix naming of info fields**
**Add schemas to footer for use when preparing form data for save**
**Add schemas to footer params**
> 153208668 Table usability improvements

- ote/src/cljs/ote/app/controller/front_page.cljs
- ote/src/cljs/ote/app/controller/transport_service.cljs
- ote/src/cljs/ote/views/main.cljs
- ote/src/cljs/ote/views/theme.cljs
There is three fixes in this pr.
1. When spinner is shown whole page is rendered (footer and header) not empty page with spinner
2. :front-page page is now removed and we cannot redirect users to :front-page anymore
3. When user deletes a service, we now set :service-changed? flag to true, so we can refresh app-state completely when needed.
> 153130249 edge remove service bug

- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/index.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/organization/snippets/organization_item.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/user/dashboard_organizations.html
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/nap/ckan.clj
- ote/src/clj/ote/services/transport.clj
- ote/src/cljs/ote/app/controller/transport_operator.cljs
- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/ui/common.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/front_page.cljs
- ote/src/cljs/ote/views/main.cljs
- ote/src/cljs/ote/views/transport_operator.cljs
Change the CKAN dashboard (remove my services as OTE has a better view for it). Create organizations in OTE (via CKAN API). This removes the need to have 2 different forms for creating an org.
**Hide pictures from org list**
**Buttons for adding new transport operator**
**Create CKAN org**
**Event for creating a transport operator**
**Add helper for two column table**
**Support special :divider option in select list**
**Force postal code to be valid with regex**
**Remove org edit from user menu**
**Refactor front page operator selection**
**Add authorization check editing transport operator**
**Remove image from transport operator**
**Set services changed flag immediately**
When returning from creating without saving, this makes sure no stale
operator data is in app state
**Remove add …
> 153474070 CKAN/OTE flow changes

- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/style/form.cljs
- ote/src/cljs/ote/ui/common.cljs
- ote/src/cljs/ote/views/passenger_transportation.cljs
Remove borders and background colors and icons from into texts.
Set padding and margin to right-border on accessibility section
> Tyylimuutoksia lomakkeen info-teksteihin

- ote/src/cljc/ote/time.cljc
**Don't format 0 seconds**
Time input field doesn't allow seconds (regex validation). Omit
seconds if they are zero.
> 153848260 Bug: unable to edit previously saved time

- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/fanstatic/napote_theme.css
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/header.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/home/layout1.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/home/snippets/promoted.html
- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/user/dashboard.html
From page: /ckan-admin/config
Split messages using "--"
Add 
```
###Palveluiden poisto on korjattu. 
Voit poistaa palvelusi Omat palvelutiedot -sivulta normaalisti.
Täältä -> http://localhost:8080/ote/#/
--
Välityspalveluille on lisätty mahdollisuus antaa ulkoinen rajapinta .csv tiedostoon, jossa välityspalvelu voi listata kaikki yritykset, joiden palveluita välittää.
--
Kolmas info
```
To info text textarea to see how this works
> 154021861 front page info box

- ote/src/clj/ote/nap/ckan.clj
- ote/src/clj/ote/nap/publish.clj
Make sure that ckan datasets and resources are actually updated and not deleted and recreated each time.
* Add missing :ckan/id keys
* Use dataset_patch and resource_patch instead of _update. Patching will
update only provided params, update will delete are params that are not
defined in the payload.
* fixes #154242505
> 154242505 Make sure that ckan datasets and resources are actually updated

- ote/src/clj/ote/services/login.clj
- ote/src/cljs/ote/views/main.cljs
**Use . instead of + in base64 alphabet**
> Use . instead of + in base64 alphabet

- ote/src/cljs/ote/views/transport_service_common.cljs
- Show missing required fields help text in all situations in service form
> Change missing-required-fields check to can-save?

- database/src/main/resources/db/migration/V1_49__rental_service_hours_info.sql
- ote/src/cljs/ote/app/controller/transport_service.cljs
- Rental pick-up location service hours info
- Service hours info moved from rentals type to pick-up location type.
> Save and load service hours info for rentals.

- ote/src/cljs/ote/app/controller/place_search.cljs
- ote/src/cljs/ote/views/place_search.cljs
- Change 3 char limit to 2 char in operation area search
- Remove alphabetical ordering and return previous version of ordering results
> 154919036 operation area search - replace with previous version

- tools/dashboard/project.clj
- tools/dashboard/src/clj/dashboard/data/cloudwatch.clj
- tools/dashboard/src/clj/dashboard/main.clj
- tools/dashboard/src/cljs/dashboard/ui.cljs
- tools/dashboard/src/cljs/dashboard/view.cljs
Add cloudwatch metrics for DB load (CPU utilization). Shows 5min avg/max/min in dashboard widget.
> Improve radiator dashboard

- ote/src/clj/ote/services/index.clj
- Fix `goog.require` JS console error on startup
> 155181346 Run goog.require cal only in dev mode

- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/style/form.cljs
- ote/src/cljs/ote/ui/common.cljs
- ote/src/cljs/ote/ui/form.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/transport_service_common.cljs
* Add a new gray "generic help box" for external interfaces. This will replace gradually the blue help boxes.
* Fixed a margin-right problem with brokerage form group check box help text.
> 155214317 Use generic help box for external interfaces help bo

- ote/src/clj/ote/services/transport.clj
- ote/src/cljs/ote/app/controller/login.cljs
- User menu is now visible even if the user has no associated transport operators
> 154956543 User info not visible if no operators

- database/src/main/resources/db/migration/V1_66__operation_area_search_postal_codes_etc.sql
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/ui/mui_chip_input.cljs
- ote/src/cljs/ote/views/service_search.cljs
* Autocompleting chip-input field for opeartion area search in service catalog.
* A new feature for chip-input that makes typing autocomplete search terms  easier. If the feature is enabled, the first autocomplete suggestion is selected if pressing a key defined in :new-chip-key-codes vector. Enable the feature: [chip-input {:auto-select? true} ...]
* Re-enabled all the area polygons for the operation area search facet, excluding the self-drawn polygons.
> 154560658 Service catalog operation area search field changes

- ote/resources/public/css/styles.css
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljc/ote/localization.cljc
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/ui/mui_chip_input.cljs
- ote/src/cljs/ote/views/service_search.cljs
- ote/src/cljs/ote/views/transport_service_common.cljs
* Removed global <p> element styling completely. Fixed some styling issues related to rendered markdown.
* Added some translation fixes for #155062911.
* Fix a bug in chip-input auto-select feature. Now supporting autocomplete vector-map datasources in addition to plain strings.
* Change interfaces data-content field to chip input, format field to autocomplete and remove AGPL suggestion from licesenses field.
> 155533490 ulkoiset rajapinnat  osio muutoksia 26.2. läpikäynnin pohjalta

- ote/src/clj/ote/services/service_search.clj
- ote/src/cljc/ote/util/url.cljc
- ote/src/cljs/ote/app/controller/service_search.cljs
* The search now supports service provider names that have special
characters such as '/'.
> 155623988 Fix service search by provider name

- ote/src/cljs/ote/views/service_search.cljs
* Add a better filter for "operation area" -field autocomplete that matches postal
area name instead of postal code if  using text character search query. Also, use startswith? instead of matching substring for more logical user experience. Now, user will get "**Tam**pere" as a first search result instead of e.g. "Pal**tam**o", if using "tam" as a search query.
If the search query starts with a number, we will match all the places with startswith?.
* Sorting for operation area facet:
* Sort all place names with no numbers in the beginning.
* Sort all place names with numbers in the beginning, e.g. postal
codes.
* Combine results.
> 155654319 - Improve service search by operation area.

- ote/src/cljs/ote/app/controller/route.cljs
* Service calendar data deduplication on client-side.
* Added missing service-calendar-idx values for trips.
> 155616199 Deduplicate service calendars and add missing service-calendar-idxs for trips

- ote/src/cljs/ote/views/transport_operator.cljs
- Business ID is now a required field in operator form
> 155246666 Make business-id a required field

- ote/src/cljs/ote/views/place_search.cljs
* Place search now properly warns if primary place field is not filled,
ignoring secondary optional place field.
> 155978703 Fix place search required? warning.

- ote/src/cljs/ote/app/controller/route.cljs
- Two same stops are not allowed to be next to each other in route planner.
> 156124444 - Two same stops are not allowed to be next to each other.

- ote/src/cljc/ote/gtfs/transform.cljc
* Use route-long-name instead of route-short-name in GTFS
* Set short-name as empty string as specifications asks us to do. (https://developers.google.com/transit/gtfs/reference/)
> 156194960  Use route-long-name instead of route-short-name in GTFS

- ote/src/cljs/ote/app/controller/route.cljs
* Use trips stop-sequence validator to validate stop sequence arrival and departure times.
> 156151479 Add validator for stop times minutes

- ote/src/clj/ote/services/routes.clj
* Localized custom stop names are now saved properly in the database
> 156612783 Fix custom stop names not saving

- ote/src/cljs/ote/app/controller/route/route_wizard.cljs
* New sea route when page was refreshed using browser refresh. :ferry type was missing and it is mandatory field.
> 156683885 Force route-type to :ferry

- ote/src/cljs/ote/views/parking.cljs
- ote/src/cljs/ote/views/passenger_transportation.cljs
- ote/src/cljs/ote/views/rental.cljs
- ote/src/cljs/ote/views/terminal.cljs
- ote/src/cljs/ote/views/transport_service_common.cljs
* Removed is-empty? function from localized-texts that can be empty
> 157033324 Remove is-empty? from localized texts that arent required

- aws/ansible/templates/ote/config.edn.j2
- ote/config.edn
- ote/src/clj/ote/tasks/pre_notices.clj
* Add email configs in ote aws config template.
* Separate email server configs and common email msg configs.
> Add ote email configuration for aws, improve email config.

- cypress/integration/route_spec.js
- database/testdata-ote.sql
* Sea route stop are overlapped easily which may cause the test fail. Changed the test to use stops outside Finland with larger distances.
> Change the test to use stops with larger distance to prevent the stops covering each other.

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/ui/table.cljs
- ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
- ote/src/cljs/ote/views/pre_notices/listing.cljs
- ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* Type :file and :file-and-delete form fields can be now disabled.
* Added row-style and show-row-hover options for Table component.
* User can now view sent pre-notices by clicking sent pre notices list rows. (Opened in view-only-mode in edit path).
* Added mouse pointer and hover effects for pre-notices authority listing. [#157273507](https://www.pivotaltracker.com/story/show/157273507)
* Removed "Valitse tiedosto" table header from "Muutoksen tarkemmat tiedot" section and changed button translation to "Lisää liite". [#157251005](https://www.pivotaltracker.com/story/show/157251005)
> 156989927 allow viewing sent pre notice

- ote/src/cljs/ote/views/terminal.cljs
* Return missing field type in terminal assistance service group.
> 157421776 Return missing field type in terminal assistance service group 

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/service_search.clj
- ote/src/clj/ote/services/service_search.sql
* Update operator hint text to match operator search functionality.
* Remove like from business-id search. Only full business-id are a match in search from now on.
> 157276910 Search only with full business id

- ote/src/cljs/ote/views/service_search.cljs
* Fixed a crash caused by a missing external interface format value, when scrolling down for more results in service catalog.
> 157728395 Check if format is nil when adding gtfs-viewer-links in service catalog.

- nap/docker/nginx/proxy.conf
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/pre_notices/attachments.clj
- ote/src/cljs/ote/app/controller/pre_notices.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
* File content validation for pre-notice form attachments. Allowed file types are now pdf, jpeg and png.
* Increased nginx max request body size to 33MB.
> 157994008 Pre-notice attachment file content type validation

- ote/src/cljs/ote/app/controller/pre_notices.cljs
- ote/src/cljs/ote/app/controller/route/route_list.cljs
- ote/src/cljs/ote/app/controller/route/route_wizard.cljs
- ote/src/cljs/ote/app/controller/transport_service.cljs
- ote/src/cljs/ote/app/routes.cljs
- ote/src/cljs/ote/views/route.cljs
* Added on-leave-event in the app router, for invoking events when the user is leaving from the current route.
* Prevent  router triggering on-navigate-event twice times when pressing the browser back button.
* Improved sea-route state handling and fixed some issues related to sea-route state management.
* Show a warning prompt if trying to cancel form creation / edit when there is unchanged data in the following forms: sea route, pre-notice or service form.
> 156606540 Unsaved changes prompt for all major forms, state and routing management improvements.

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/pre_notices/authority.clj
- ote/src/cljs/ote/views/pre_notices/authority_listing.cljs
* Use sent timestamp in authority pre-notices listing.
> Use sent timestamp in authority pre-notices listing

- database/src/main/resources/db/migration/V1_102__external_interfaces_search_import_errors.sql
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/service_search.clj
- ote/src/cljs/ote/views/service_search.cljs
* Show an error msg in service search results in external interfaces section if GTFS viewer cannot be used (i.e. GTFS import failed).
> 158486660 Show a notice in search results if GTFS viewer cannot be used.

- ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* Fixed overlapping input labels in pre-notice form map area.
> 159652151 Fix overlapping input labels in pre-notice form map area.

- ote/src/cljc/ote/time.cljc
- ote/src/cljs/ote/views/ckan_service_viewer.cljs
* Fixed bugs in timestamp conversion in ote.time. Previously, the convert functions just returned todays date no matter what timestring was used as a parameter.
> 159885008 Fix critical bugs in timestamp formatting in ote.time.

- ote/src/cljs/ote/ui/leaflet.cljs
* Use a secured url for the osm tile layer. Prevents mixed content warnings in production.
> 157991591 Use a secured url for the osm tile layer.

- database/src/main/resources/db/migration/V1_107__add_companies_from_ts_companies.sql
- ote/src/clj/ote/services/service_search.sql
* Added missing company info in service search results in case user filled the companies info manually using the service form.
* Changes in transport_service_search_result. Using also transport-service "companies" in search results.
> 160162515 Add missing companies info in search results

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* Transit changes: compare dates crashed if there was no traffic
> 160482359 Fix nil compare if first common stop can't be found

- ote/src/cljs/ote/style/transit_changes.cljs
* Use default background color in date highlight styles. This makes the hightlight circle appear also on dates that have no hash color.
> 160547133 Make sure that the balls are visible when hovering

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* Open next year calender if second selected date is in next year in transit changes visualization.
> 160509327 - Open next year calender if second selected date is in next year.

- ote/src/clj/ote/services/settings.clj
- ote/src/clj/ote/tasks/pre_notices.sql
- ote/src/cljs/ote/app/controller/email_notification_settings.cljs
- ote/src/cljs/ote/views/email_notification_settings.cljs
* Pre-notices weren't send to in everybody in some cases because sql query didn't work.
Now the sql query is fixed and it uses && to check if regions arrays overlap each other.
* Also ui in email notification settings is changed so that it shows like has selected all regions when he/she isn't selected any in situation where there isn't row in user_notifications table.
> Email settings update

- ote/src/cljs/ote/app/controller/front_page.cljs
* Remove :transport-operators-with-services when operator is deleted to enable page update
> 158816592 Fix operator delete.

- nap/docker/docker-compose.yml
* Fixed security issue with docker-compose. By default docker exposes container ports to all interfaces. We do not want that, so now they are strictly locahost only. https://www.techrepublic.com/article/how-to-fix-the-docker-and-ufw-security-flaw/
> Make sure that docker container ports are exposed only on localhost.

- ote/src/clj/ote/services/viewer.clj
* GET /viewer response was cached with ie11. Added no-cache-headers
> Add no-cache-headers to GET /viewer request

- ote/src/clj/ote/services/transit_visualization.sql
* Added missing COALESCEs in fetch-route-differences. Fixes missing changes under calendar when manually choosing dates for comparison.
> 161173800 Add missing COALESCEs in fetch-route-differences.

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* Show next years calendar on transit visualization page always
> Remove show-next-year checkbox and show next years calendar always

- ote/src/cljs/ote/views/service_search.cljs
* Null business-ids are breaking operator search suggestions. Do not show operators in search suggestion list if they have null business-id. Business-id is used as an unique identifier and should be mandatory for all operators.
> 161407877 Do not show operators search suggestions if they have no business-id

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/external.clj
- ote/src/cljs/ote/app/controller/transport_service.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/transport_service_common.cljs
* Made business ids and business names mandatory for csv import fields. Added better error messaging for invalid companies csvs.
* Fixed a problem with :file type form fields that caused it not to trigger on-change event if a new file with a same name was uploaded multiple times.
> 161009873 Make business ids mandatory for csv company source

- database/src/main/resources/db/migration/V1_118__change_stop_times_display.sql
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
- ote/src/cljc/ote/transit_changes.cljc
- ote/test/clj/ote/transit_changes/stop_name_detection_test.clj
* New stop problem in trip stop sequence fixed
* Use stop-lat and stop-lon as key to indentify stop instead of stop-name. Also stop-name change don't appear as a change in automatic change detection.
> 161108708 stop name is not chg

- ote/project.clj
* Change repository uri to "https:" because new figwheel requires TLS.
Otherwise lein figwheel fails.
>  Geotools osgeo repository uri to https

- ote/src/clj/ote/tasks/pre_notices.clj
- ote/src/cljs/ote/views/transit_changes.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* Changed conjugation of finnish "1:seen muutokseen" to "1. muutokseen" which is according to grammar, ref. e.g. https://www.kielikello.fi/-/jarjestysluv-1
Affects email notification and root view for schedule changes and view for route schedule changes
> Label time to first trip change

- ote/src/clj/ote/services/transit_changes.sql
- ote/src/cljs/ote/app/controller/transit_changes.cljs
- ote/src/cljs/ote/views/transit_changes.cljs
* Sorting changed back to previous version. Order is now: 1. changes, 2. problems, 3. no interfaces, 4. no changes.
* Changed also the text that describes checkbox functionality. It hides problems from the list by default now.
> 161671943 Change transit changes list sorting 

- ote/src/cljc/ote/time.cljc
* Change days-until function to work only with cljs. Make it handle all dates as local-date due to sql.date values are in utc format.
> 161834850 fix days until in transit visualization

- ote/src/cljs/ote/app/controller/transport_operator.cljs
The previous nil check broke the view because the loaded flag was not getting set.
> Ensure view "loaded?" flag is set

- ote/src/clj/ote/tasks/pre_notices.sql
- ote/test/clj/ote/tasks/pre_notices_test.clj
* Remove old changes from detected changes email. chg.date in with clau…se will remove most of the packages out of "inner table" and it will speed up the query.
* By taking gtfs_package into account we can check that the relevant new changes happens for packets that are downloaded (created) in current day.
> 161439932 remove old changes from detection email

- database/src/main/resources/db/migration/R__GTFS_query.sql
- database/src/main/resources/db/migration/V1_122__add_route_hash_ids_to_all_packages.sql
* Add postgres functions to calculate route-hash-id for all routes using default "short-long-headsign" pattern.
> 162234002 Calculate route-hash-id for all routes

- database/src/main/resources/db/migration/R__GTFS_query.sql
- ote/src/clj/ote/services/transit_changes.sql
- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
- ote/src/cljc/ote/transit_changes.cljc
- ote/src/cljs/ote/views/admin/detected_changes.cljs
* Few more options to calculate route-hash-id
* Null pointer when we can't find trips for route
* route long name, route short name and trip headsign queries to use only route-hash-id as a key
> 162383037 route hash id options

- database/testdata-ote.sql
- ote/src/clj/ote/tasks/pre_notices.sql
- ote/test/clj/ote/tasks/pre_notices_test.clj
* Prevent email to send notifications from detected changes if the parent service is something else than scheduled (e.g. taxi.)
> 162167133 Add sub-type to notification email

- database/src/main/resources/db/migration/R__GTFS_query.sql
- database/src/main/resources/db/migration/V1_125__add_delted_to_gtfs_package.sql
- ote/src/clj/ote/integration/import/gtfs.clj
- ote/src/clj/ote/services/transit_changes.sql
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/tasks/pre_notices.sql
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
* Transport service could not be removed or transport services external interface could not be removed if interface url did contain something that our system added as gtfs package to db.
Removing interface or service caused foreign key error due to delete "no action".
I added delete cascade when could and removed link to gtfs_package because we want to keep gtfs packages in our db in situations where service or interface is removed.
> 162110175 foreign key

- cypress/integration/pre-notice_spec.js
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/integration/import/ytj.clj
- ote/src/clj/ote/main.clj
- ote/src/clj/ote/services/transport.clj
- ote/src/cljc/ote/db/user.cljc
- ote/src/cljs/ote/app/controller/transport_operator.cljs
- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/style/form.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/main.cljs
- ote/src/cljs/ote/views/transport_operator_ytj.cljs
* Feature flag variation in controller transport_operator.cljs: previous non-ytj functionality and new with ytj-integration.
* transport_operator view variation done using a new "-ytj" view
* Under the feature flag modified transport operator creation logic: fields from ytj, option to create multiple operators if companies share the business id/y-tunnus, retains support for creating an operator which doesn't have a business-id from YTJ.
* WIP UI localisation strings
* integration/import/ytj tweaks to pass more detailed ytj results to allow view error handling
* services/transport.clj feature flag variated ytj integration support
* Under the feature flag group and member table updating directly without CKAN i.e. dependency removed from operator creation/updating
* group table created_time …
> 161874264 operator ytj integration

- ote/src/cljc/ote/gtfs/transform.cljc
- ote/src/cljs/ote/app/controller/route/route_wizard.cljs
* Creating gtfs package failed because of outofbounds error when adding stops to gtfs file.
* Changed stop-index to index when fetching stops from vector.
> 162086762 - route gtfs package problem

- ote/src/clj/ote/services/transport.clj
When :open-ytj-integration is set
- services: cleanup transport require dependencies
- services: transport cleanup code
- services: operator group created, state, approval_satus fields set when ytj. Some relevant-looking group table's fields were previously not set.
Also code rearranged to match table schema order, for convenience.
- services: transport operator insert group assert if name is nil
> 161874264 improvements for transport-operator ytj creation

- database/src/main/resources/db/migration/R__GTFS_query.sql
- ote/src/clj/ote/tasks/pre_notices.sql
* The logic that decided which services should be taken into account when automatic detection was start was wrong. Fixed it by taking into account services that either have new package or earliest change date is bypassed.
> 162751595 wrong services in automatic change detection

- ote/src/cljs/ote/app/controller/transport_operator.cljs
* controller: transport-operator clear ytj metadata before new fetch
* controller: transport operator allow edit if YTJ fetch changed a field
Previously saving was enabled only after user interaction with the fields.
* controller: transport-operator company aux names alphabetically, primary name first
> 161874264 transport-operator field edit logic and other improvements

- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/style/form.cljs
- ote/src/cljs/ote/style/form_fields.cljs
- ote/src/cljs/ote/views/transport_operator_ytj.cljs
This restricts input field widths on wide screens, 100% on smaller screens.
Also sets form-group-contiainer width 100% which has a global impact potentially. No problems met (yet).
* views: transport-operator remove unused constructor wrapper fn
* style: form field width def 100%/35rem
* views: transport-operator field width styling
* style: form-group-container width 100%
* style: remove now unuser experimental flex-container2
> 161836698 transport operator style fields

- nap/docker/ckan/ckan-plugins/ckanext-napote_theme/ckanext/napote_theme/templates/emails/reset_password.txt
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
* In previous pr I missed reset password email. Now traficom contact details are updated to there as well.
> Update contact details from reset password email

- ote/src/cljs/ote/ui/select_field.cljs
* Splitted and improved from form field select field.
This uses an atom for internal state keeping, allowing reusability
without polluting app state namespace.
Also value resolving simplified to avoid state resolution problems
if appstate changes elsewhere.
> ui: select-field reusable dropdown component

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/operators.sql
- ote/src/clj/ote/services/transport.clj
- ote/src/cljs/ote/app/controller/transport_operator.cljs
- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/style/form.cljs
- ote/src/cljs/ote/style/form_fields.cljs
- ote/src/cljs/ote/theme/colors.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/ui/select_field.cljs
- ote/src/cljs/ote/ui/success_msg.cljs
- ote/src/cljs/ote/ui/warning_msg.cljs
- ote/src/cljs/ote/views/transport_operator_ytj.cljs
- ote/test/clj/ote/services/admin_test.clj
* some themed colours
* re-usable components for displaying a themed icon-lable, e.g. for conveying a result next to an UI control
* (re-usable) styling for several UI components
* transport-operator (ytj) operator name merging wizard section
* localisation strings with initial values
* test: fix admin_test to evaluate last auditlog event, not last
* ui: select-field support for dynamically changing options
* controller: transport-operator remove debug logs
> 162262078 transport operator ytj merge section

- ote/src/cljs/ote/views/transport_operator_ytj.cljs
* views: transport-operator delete dialog dom key to fix runtime warning
> views: transport-operator delete dialog dom key to fix runtime warning

- ote/src/cljs/ote/app/controller/transport_operator.cljs
- ote/src/cljs/ote/views/transport_operator_ytj.cljs
* views: transport-operator disable ytj fetch button when input not valid
* controller: transport-operator hide ytj result msg when business-id changes
UI displays a message about ytj fetch results, those should be removed when user edits business id input field.
> 163146424 disable ytj querty btn

- ote/src/clj/ote/services/index.clj
* Google analytics script tag removed so we don't send anymore data.
> removed google analytics script tag

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljs/ote/app/controller/transport_operator.cljs
- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/ui/form.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/ui/select_field.cljs
- ote/src/cljs/ote/views/transport_operator_ytj.cljs
* transport-operator wizard section (for selecting ytj name for those nap
operators which do not have a ytj name match), supports now
an empty default value and selecting & reverting selection per orphan.
And updating operators-to-save checkbox list accordingly.
> 163208379 operator wizard selections

- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* Get route-hash-id-type from database and based on that show headsign in route list or not
If headsign is shown it must relate to route detection. Otherwise it only confuses users.
> 163289310-route-list-headsign

- ote/src/cljs/ote/app/controller/admin.cljs
- ote/src/cljs/ote/app/controller/transport_operator.cljs
- ote/src/cljs/ote/views/transport_operator_ytj.cljs
* Transition from operator page to own services when operator is deleted. Previously we moved user away from operator page always when operator was deleted. Now we change page only if non-ytj company is deleted.
> 163220298 transition in delete operator

- database/src/main/resources/db/migration/R__GTFS_query.sql
- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/ui/table.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* Changed gtfs_route_difference stored procedure to work with route-hash-id only.
* This prevents finding multiple route differences and fixes the bug.
* Also added few random numbers to table component to prevent js console warnings. However our table component doesn't take into account :keys that are passed to header row it is always 'h1' and it cannot be fixed using this version of material ui.
> 163361831 compare days 500 error

- ote/src/cljs/ote/app/routes.cljs
* Gtag manager being called in on navigate event, even after it was removed.
> removed call to gtag manager on navigate

- ote/resources/public/css/styles.css
- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/style/buttons.cljs
- ote/src/cljs/ote/style/info_style.cljs
- ote/src/cljs/ote/theme/colors.cljs
- ote/src/cljs/ote/ui/buttons.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/login.cljs
- ote/src/cljs/ote/views/own_services.cljs
- ote/src/cljs/ote/views/route/route_list.cljs
- ote/src/cljs/ote/views/service_search.cljs
- ote/src/cljs/ote/views/theme.cljs
- ote/src/cljs/ote/views/transport_operator_ytj.cljs
* New styles for primary, negative, outline buttons and related elements like text colour
* New negative (=red) button
* Some problem fixed.
* Changed following buttons to use html button element instead of material ui components: save, delete, cancel 
* buttons updated for buttons 
- embedded in tables a few old ones like file upload remain). Tables e.g. in service and sea route views
- navigation-prompt
- service/operator/(sea)route deletion modal
- user settings
- user email settigs
- user login
- user registration
> 161836698 button styles updated globally

- ote/src/cljs/ote/app/controller/transport_operator.cljs
*  controller: transport-operator fix edit when no :open-ytj-integration
Otherwise extra keys assert in backend specql call
> controller: transport-operator fix edit when no :open-ytj-integration

- ote/src/clj/ote/services/transit_changes.sql
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* Force package-id to be integer in stored-procedure calls.
* Small refactoring to transit-visualization controller and detection.clj file.
> 163509847 route hash id bigint

- ote/src/clj/ote/email.clj
.. because postal will fall back to local /usr/bin/sendmail, and
configuring an empty smtp server means we don't want the app to send
out emails.
> don't send email when smtp server is undefined

- aws/ansible/environments/production/group_vars/ote/vars
- aws/ansible/environments/staging/group_vars/ote/vars
- aws/ansible/templates/ote/config.edn.j2
- ote/config.edn
- ote/src/clj/ote/services/index.clj
- ote/src/clj/ote/services/transit_changes.sql
* Problem in transit changes showing changes as 0-0-0-0 instead of "Ei muutoksia"
* Default of favicon changed to show the proper favicon instead of development.
* Querying transit_changes.sql to use different-week-date
> Production env variable

- ote/src/cljc/ote/time.cljc
* Fixed days-until function by using correct date object in day-difference function.
> Fix days-until

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* controller: transit-visualization fix show-no-change-routes? toggling
Checkbox was stuck forever because state passed to it was a container
instead of the boolean which is toggled.
> controller: transit-visualization fix show-no-change-routes toggling

- database/src/main/resources/db/migration/R__GTFS_query.sql
* Empty row in route changes table.
* `gtfs_service_routes_with_daterage` to check if the hash id is valid.
> Fixes empty routes appearing in transit visualization.

- ote/src/cljs/ote/ui/main_header.cljs
* main header :user-menu-video-tutorials-link commented out. For now videos are not available. Shall be restored when they are.
> 163941143: main header :user-menu-video-tutorials-link commented out

- ote/src/cljs/ote/views/transit_visualization.cljs
* views: transit-changes dont hide calendar during date change
Not hiding calendar prevents view flickering when route details are
reloaded. Route details don't affectc calendar data model.
> 163936103: transit-changes dont hide calendar during date change

- database/src/main/resources/db/migration/V1_133__transport_service_publish_time.sql
- database/src/main/resources/db/migration/V1_134__drop_published.sql
- ote/src/clj/ote/services/admin.clj
* Moved drop column to a new migration file so trigger events in the same migration don't stop it from dropping.
> Moved drop column and view refresh to a new file.

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* Calendar selections are now always in the certain order.
> Calendar selections and hovers made more logical.

- ote/src/clj/ote/transit_changes/detection.clj
- ote/test/clj/ote/transit_changes/detection_test.clj
* When route have a different weed followed by normal week followed by different week the first different weeks was considered as a change. Which was wrong. Added a check that two following weeks must be different to count as a change.
> 163781982 one different week should not be considered as a change

- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/util/clojure.clj
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* services: remove unused changed-routes-to-service-by-date sql
* views: transit-visualization fix route-change checkbox disabling
* services: transit-visualization fix for route-changes and keyword type, not-changes routes were not shown
* util: file for clojure-language related functions with remove-coll-key-ns
> 164075691 routes without changes missing

- ote/src/cljs/ote/ui/common.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
Made this to work with event instead of normal link, because IE doesn't properly launch popstate event for some reason.
* IE11 fix for back to transit-changes page.
> Fixed IE link not working.

- ote/project.clj
* figwheel-logfile to tmp
Prerviously .log file was created under source code folder, which is
unnecessary.
> figwheel-logfile to tmp

- database/src/main/resources/db/migration/V1_137__fuzzy_location_to_gtfs_stoptime_display.sql
- ote/src/clj/ote/integration/import/gtfs.clj
- ote/src/clj/ote/integration/import/stop_times.sql
- ote/src/clj/ote/services/pre_notices/attachments.clj
- ote/src/clj/ote/services/transit_visualization.sql
* GTFS import: Added fuzzy location calculation for stops when new gtfs is imported
* Update clause to update all null stop-fuzzy-lat and stop-fuzzy-lon values in db.
* Admin panel: when new gtfs package was imported and automatic detection started it failed because service-id was string and not integer.
* gtfs-stoptime-display composite type modified by adding fuzzy location for stops
* Changed existing feature.
* Change to DB migrations.
* Changes to CI environment
* Builds now 200% faster with change X!
> 164134455 fixed stop fuzzy location problem in transit visualization page.

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
*  controller: transit-visualization simplify route filtering checkbox logic
Also some refactoring of state initialization
Now state toggling does not monitor `componentDidMount` event and is more simple - but also chckbox toggling on UI does not always give instant feedback to user & don't get disabled if there's a long rendering delay.
> 163902792 transit visualization simplify route filtering checkbox logic

- database/src/main/resources/db/migration/V1_138__fix_service_search_view.sql
* Migration was missing `OR REPLACE`
Fixes problem introduced in https://github.com/finnishtransportagency/mmtis-national-access-point/pull/895
> Fix transport_service_search_result Just create isn't enough.

- database/src/main/resources/db/migration/R__GTFS_query.sql
- database/src/main/resources/db/migration/V1_139__mark_interface_as_contract_traffic.sql
* Add new column to transport service table so we can mark which services are contract traffic so we can skip them from hash calculations and transit changes list
> 163649701-skip-contract-traffic

- ote/src/cljs/ote/ui/common.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* fix navigate back event runtime error from call to e!
Workaround for IE backstepping doesn't need a call to e! which expects
an event. routes/navigate! call alone is enough.
> 1640467650: fix navigate back event runtime error from call to e!

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
Previously:
1. given user had selected a service in "tunnistetut muutokset"
2. and selected a route
3. when user navigated back to "tunnistetut muutokset"
4. and selected another service
then the route selected in step 2 was still visible in transit visualization view
Now the selected route is cleared from app state when user navigates to transit visualization view.
> 163934214 Clear selected route when opening transit visualization

- ote/src/cljs/ote/views/transport_operator.cljs
* Single business name heading value when no ytj integration, multiple business names if editing
all via business-id fetch from ytj.
> 16426682: transport-operator logic for singular/plural name heading

- ote/config.edn
- ote/src/cljs/ote/views/transit_visualization.cljs
key of the row
* Removed empty space from config.edn
* Removed key-fn for stoplist because the row data doesn't have a property that's unique enough to be key. stop-names are duplicated when circular route.
> Removed key-fn because stop names are not unique, so it can't be,

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljs/ote/views/transport_operator.cljs
* transport-operator: When editing in "single operator mode", the name may be either primary
or auxiliary business name. The title should clarify this.
> views,language: transport-operator heading to business name or -auxnames

- database/src/main/resources/db/migration/R__GTFS_query.sql
* detection: Removed ended routes from gtfs_service_routes_with_daterange stored procedure.
> 164198231 Hide routes that doesn't have traffic anymore.

- ote/src/cljs/ote/style/service_search.cljs
* break word looks better than break-all
> break-all to break-word because it looks better.

- ote/src/clj/ote/services/transit_changes.clj
- ote/src/cljs/ote/views/admin/detected_changes.cljs
* Transit changes backend: Start hash calculations in different thread and return ok response
* Admin transit changes: do not block route hash id type list.
* Admin transit changes: Start change detection automatically when date hashes are calculated.
> 164600197 hash calculation to new thread

- ote/src/cljs/ote/views/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization/calendar.cljs
- ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
- ote/src/cljs/ote/views/transit_visualization/change_utilities.cljs
* Transit visualization page: Move route change table header icon texts to correct order
* Transit visualization page: Do not add trip and stop changes to route change summary if change type is :removed
* Transit visualization page: At the calendar change list end trip changed.
* Transit visualization page: Move calendar change table header icons to correct order.
> 164756947 route summary updates

- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/cljc/ote/transit_changes.cljc
- ote/test/clj/ote/transit_changes/detection_test.clj
* transit-changes: for changed weeks, report all no-traffic without threashold
* transit-changes: ignore no-traffic which starts on last analysis wk end
because if normal week has traffic on weekdays
and nil on last day, analysis reports a started no-traffic run even
if it actually ends on next day.
This happens because analysis doesn't run on weeks 3. & 4. of the last
4-week window.
* transit-changes: detection code cleanup
transit-changes: tests fix test-change-on-2nd-to-last-wk
transit-changes: tests added for real life cases, plus restructuring
transit-changes: tests: reorganize + summer period week and day tests
transit-changes: detection code formatting for day comparison
transit-changes: test changed-days-of-week when daily traffic individual
transit-changes: unit test cleanup …
> 164796337 discard no traffic if starts on last analysis week & report no-traffic for changed weeks

- ote/src/cljc/ote/util/text.cljc
* rand-str for generating random text strings
This could be used e.g. for generating unique ^{:key id } id's on view templates for reagent/react.
> util: define rand-str for generating random text strings

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljc/ote/time.cljc
- ote/src/cljs/ote/ui/service_calendar_compact.cljs
- ote/src/cljs/ote/ui/table.cljs
- ote/src/cljs/ote/views/transit_changes.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization/calendar.cljs
- ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
* Transit visualization: Add date of week to calendar change list
* calendar component: Fix month name for February when current day is greater than day count in February (29,30,31)
* All tables: Move header labels and column values to start at the same spot
* All tables: Fix long text values in tables by changing pre-wrap to pre-line
* transit-changes: Move change icons more to left
> 164941250 transit visualization ui tuning

- ote/src/cljs/ote/views/transit_visualization.cljs
* views: transit-visualisation fix show routes without changes
Invalid reagent hiccup form produced a runtime warning and prevented
displaying some rows when table couldn't be rendered.
> 165178236: transit-visualisation fix "show routes without changes"

- ote/src/cljs/ote/views/transit_visualization.cljs
* transit-visualization show all changes via history link
navigation via the history link in infobox shows all changes and not filtered by date. Route navigation doesn't work without the url arg.
> 165178236: transit-visualization show all changes via history link

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* transit-visualization: route table lists detected changes for one route, currently above
the calendar. It reads changes from :changes-all, an another vector
than the table listing different routes.
This commit filters also :changes-all.
> 165210544: transit-visualization hide past changes in route table

- aws/ansible/jenkins/jobs/cypress.groovy
* aws: chrome --record false to allow freemium usage without recording
> aws: chrome --record false to allow freemium usage without recording

- .circleci/config.yml
- aws/ansible/jenkins/jobs/cypress.groovy
- cypress.json
* some warnings in cypress tests. And possibly remove restrictions from the amount of tests that can be ran
> Video false for cypress settings to stop warnings.

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/transit_changes.sql
- ote/src/cljs/ote/views/transit_changes.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* views: transit-visualization use :time-days-abbr instead of hard coding
* views: transit-changes use :time-days-abbr instead of hard coded string
* views: transit-changes use days-until-change from response
* services: transit-changes days-until-change from different-week-date
* services: transit-changes fetch only future upcoming-changes
> 165208562 transit changes hide past changes and transit-visualization ui abbreviation for days

- ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
* Alignment does not match for rows with different number of icons.
This sets same places regardless if other icons are displayed.
Also switched "no-traffic" and "removed" icons to same order as in table legend.
> transit-visualization: same place for change icons always

- ote/src/clj/ote/transit_changes/detection.clj
- ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* transit-changes: on no-traffic detection ignore holiday keyworded days
* transit-changes: new test for route start
* transit-changes: cleanup old test case code
* transit-changes: detection code formatting
> 165575508 transit change detection to ignore holidays between no traffic

- docs/transit-changes/README.md
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/cljs/ote/app/routes.cljs
- ote/src/cljs/ote/views/transit_visualization/calendar.cljs
- ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* transit-changes: rename route-day-changes-new remove -new
transit-changes: rename detect-route-changes-for-service-new remove -new 
transit-changes: rename route-weeks-with-first-difference remove -new
transit-changes: rename route-next-different-week-new remove -new
transit-changes: remove legacy detection functions for route wks & days
transit-changes: remove legacy detection functions for route weeks
views: transit-visualization cleanup code
* 4b76177 transport-operator: remove unused REST route
> 165815622 transit changes remove old logic funcs and remove unused operator route

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
When we are currently in a pause in traffic use current date as date1.
* Selected date problem in no-traffic situations.
> Transit_visualization: Removed unnecessary check and fixed date1 check

- ote/src/cljs/ote/style/buttons.cljs
- ote/src/cljs/ote/ui/info.cljs
- ote/src/cljs/ote/views/own_services.cljs
- ote/src/cljs/ote/views/place_search.cljs
* A caret for info-toggle to indicate it's clickable
* event handlers in place-search so that they don't break figwheel hot-reloading.
* Button styles, so that the extra border pixel on hover doesn't cause the button to take up more space.
* Ability to pass atom to info-toggle, because it was just more confusing and the only use case where it was used was no longer necessary.
> Caret for info

- ote/src/cljs/ote/app/controller/pre_notices.cljs
* pre-notices convert filename to lowercase
Allows uppercase file extensions.
As a side effect normalizes all filenames to lowercase.
> controller: pre-notices convert filename to lowercase

- ote/src/clj/ote/services/transport.sql
Duplicated the service if it had many interfaces.
* own services page showed error if a service had multiple interfaces and one of the wasn't type `route-and-schedule`
> own-service: fixed bug with service errors.

- ote/src/clj/ote/tasks/pre_notices.sql
* Add group by clause for fetch-unsent-changes-by-regions query to enable multiple package-ids to be used when area is fetched
> 165877303 Fix empty area in change email

- ote/src/cljs/ote/ui/table.cljs
* no-selection? keyword check was implemented wrong. So the padding was never given to tables, so the border on selected rows wasn't showing properly.
> Table: fixed table body padding.

- ote/src/clj/ote/components/http.clj
- ote/src/clj/ote/services/admin.clj
- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/util/clojure.clj
- ote/src/cljc/ote/util/collections.cljc
- ote/src/cljc/ote/util/fn.cljc
- ote/src/cljs/ote/app/controller/admin.cljs
- ote/src/cljs/ote/views/admin/users.cljs
- ote/test/clj/ote/services/admin_test.clj
Utility funcs used in REST endpoint implementation:
* http: generic func for returning http error if map spec validation fails
* util: spec validation function with error string output on fail
admin REST endpoint refactoring: 
* controller: admin refactoring rename misleading symbol name
* controller: admin user-operator-members api renamed as member, refactoring
* services: admin user-operator-members api renamed as member, refactoring
* views: admin view typo fix
Other minor cleanup
* util: deleted clojure.clj, content moved to ote.util.collections
* services: transit-visualization remove unused ote.util.clojure require
* util: moved remove-coll-key-ns to existing more suitable namespace
> 165675611 admin service endpoint refactoring 2

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization/calendar.cljs
- ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
* views,controller: transit-visualization hide route change focus frame
* 658ec65d views: transit-visualization calendar sanity check for nil dates
* 060afabc controller: transit-visualization hide and fix diff stats when loading
* e82709dd views: transit-visualization fallback to 0 when no diff stats
> 166113289 bugfix transit visualization calendar wrong header diff stats and similar improvements

- ote/config.edn
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* controller: transit-visualization refactor loading state for spinner
* controller: transit-visualization remove dead code LoadOperatorDates
* view: transit-visualization loading spinner for map,trip,stop selections
> 166491363 transit-visualization, replace trip and stop tables using a spinner after calendar selection

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* transit-visualization- route-list:  We didn't pass change counts from grouped changes to route list.
> 166438650 Fix change counts to transit-visualization route list

- ote/src/clj/ote/tasks/pre_notices.sql
* pre-notices are now sent only on transport servies with type `road`.
> pre-notice: only send road pre_notices on road typed traffic.

- ote/src/clj/ote/transit_changes/change_history.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/cljc/ote/transit_changes.cljc
- ote/test/clj/ote/transit_changes/detection_test_utilities.clj
- ote/test/clj/ote/transit_changes/detection_test_weeks.clj
* transit-changes: tests, new cases for changes after no-traffic
* transit-changes: detection_test_utilities create-data-all-routes
* transit-changes: change_history, safety check
* transit-changes: detection, generic :holiday keyword for holiday hashes
* transit-changes: detection, refactor changes-by-week->changes-by-route
* transit-changes: detection, refactor no-transit detection
* transit-changes: simplify no-traffic detection logic
Let's plan whether to merge this to master and then https://github.com/finnishtransportagency/mmtis-national-access-point/pull/1008, or if these should be merged together before merging to master.
> 166495087 transit changes no-traffic period logic refactoring

- ote/src/clj/ote/transit_changes/detection.clj
- ote/test/clj/ote/transit_changes/detection_test_weeks.clj
Holiday keyword hides traffic days and no-traffic is reported if route
has traffic only on holiday. This fixes the issue by making a
distinction if holiday has traffic or not.
> transit-changes: detection, fix if traffic only on holiday

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljs/ote/views/pre_notices/pre_notice.cljs
* Pre-notice, pre-notice-list, authority-pre-notice-list, pre-notice-email: Everywhere "other change, what?" is changed to "other change" 
* Removed other-type-change input field from pre-notice page.
> 161748643 Change "other change, what?" to just "other change"

- ote/src/cljs/ote/views/admin/users.cljs
Admin panel's edit user button removed entirely as first workaround for the feature due to ckan removal.
> 166926481: admin, remove edit user button because ckan shall be removed

- database/src/main/resources/db/migration/V1_154__fix_transport_service_search_view.sql
* transport_service_search_result view to use create a concatenated list of arrays instead of finding the first non null value to select.
> Service search: fix view to use array_cat instead of coalesce

- ote/src/clj/ote/services/index.clj
- ote/src/cljs/ote/app/routes.cljs
* views: index, routes, matomo trackPageView only on route navigation
Allows setting custom url before reporting url to analytics script.
Otherwise direct link navigation to register or reset-password is
reported before removing url argument and query strings.
> 166922371: views: index, routes, matomo trackPageView only on route navigation

- ote/src/clj/ote/services/operators.sql
- ote/src/clj/ote/services/register.clj
- ote/src/clj/ote/services/register.sql
- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/util/email_template.clj
* Controlling user rights to operators is now based on just the group-id instead of using transport operator to fetch this ID. This is because authority users don't have a proper transport operator, which broke the existing implementation for their user group.
> 167066486 authority users controls

- database/src/main/resources/db/migration/V1_155__add_email_confirmation_columns.sql
- database/src/main/resources/db/migration/V1_156__email_confirmation_table.sql
- database/src/main/resources/db/migration/V1_157__existing_users_confirmed.sql
- database/testdata-ckan.sql
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/main.clj
- ote/src/clj/ote/services/index.clj
- ote/src/clj/ote/services/login.clj
- ote/src/clj/ote/services/login.sql
- ote/src/clj/ote/services/register.clj
- ote/src/clj/ote/util/email_template.clj
- ote/src/cljc/ote/db/user.cljc
- ote/src/cljs/ote/app/controller/confirm_email.cljs
- ote/src/cljs/ote/app/controller/login.cljs
- ote/src/cljs/ote/app/controller/resend_confirmation.cljs
- ote/src/cljs/ote/app/routes.cljs
- ote/src/cljs/ote/style/notification.cljs
- ote/src/cljs/ote/style/register.cljs
- ote/src/cljs/ote/ui/form.cljs
- ote/src/cljs/ote/ui/notification.cljs
- ote/src/cljs/ote/views/confirm_email.cljs
- ote/src/cljs/ote/views/login.cljs
- ote/src/cljs/ote/views/main.cljs
- ote/src/cljs/ote/views/register.cljs
- ote/src/cljs/ote/views/resend_confirmation.cljs
- ote/src/cljs/ote/views/user.cljs
* Email confirmation
* Login form returning status code 200 on every response. 
* Users can no longer change their emails, because this would bring a lot of unwanted complexity to confirming email addresses. This feature could be done in a different ticket.
* New table for email confirmation tokens
* User now has email-confirmed? column and confirmation timestamp column
> 166907227 email verification

- ote/resources/public/language/en.edn
- ote/resources/public/language/sv.edn
* translations to include a needed space
* The translations for the email footer were in the email confirmation pull request
> Reset-password: added needed spaces to texts

- database/src/main/resources/db/migration/V1_160__user_name_drop_unique_non_null.sql
- database/src/main/resources/db/migration/V1_161__user_email_constraint_unique_not_null.sql
- ote/src/clj/ote/nap/users.clj
- ote/src/clj/ote/nap/users.sql
- ote/src/clj/ote/services/login.clj
- ote/src/clj/ote/services/register.clj
- ote/src/clj/ote/services/register.sql
- ote/src/clj/ote/services/users.clj
- ote/src/cljs/ote/app/controller/common.cljs
- ote/src/cljs/ote/app/controller/login.cljs
- ote/src/cljs/ote/app/routes.cljs
- ote/src/cljs/ote/ui/main_header.cljs
- ote/src/cljs/ote/views/admin/user_edit.cljs
- ote/src/cljs/ote/views/admin/users.cljs
- ote/src/cljs/ote/views/front_page.cljs
- ote/src/cljs/ote/views/register.cljs
- ote/src/cljs/ote/views/user.cljs
- ote/test/clj/ote/integration/export/geojson_test.clj
- ote/test/clj/ote/integration/import/ytj_test.clj
- ote/test/clj/ote/services/admin_test.clj
- ote/test/clj/ote/services/pre_notice_test.clj
- ote/test/clj/ote/services/service_search_test.clj
- ote/test/clj/ote/services/transport_test.clj
- ote/test/clj/ote/tasks/company_test.clj
- ote/test/clj/ote/tasks/pre_notices_test.clj
- ote/test/clj/ote/test.clj
* 6608475  services: users register fix for 167619111 future tokens deleted
* test: fetch run-time the user id of username for session cookie
* db: user table add email field constaint unique not null
* views: admin, in admin user list replace username field using id field
* services: login, fetch user data based on id instead of username
* app: routes requires-authentication? check to use user-logged-in?
* views: front_page,main_header user-logged-in? moved to common controller
* views: main_header use appstate user key instead of username
* views:  remove username handling
* services: register-user to set db row id to username field
* services: save-user not to modify username db field
* controller: login, dissoc register from appstate when navigating away
* db: user username drop …
> 166180208 remove username field 167647241 session to use userid not username

- ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* Fixes a run-time error if route is already selected from url element when navigating to view for the first time.
> 167697239 transit-visualization date->hash nil check to fix runtime error

- ote/src/cljs/ote/theme/colors.cljs
- ote/src/cljs/ote/views/transit_visualization/calendar.cljs
* theme: remove unused color spinner code and order defs by name 
* views: transit-visualization calendar day font color to existing theme
> Transit visualization calendar day font color from theme

- ote/src/clj/ote/nap/users.sql
- ote/src/clj/ote/services/admin.clj
- ote/src/clj/ote/services/register.clj
- ote/src/clj/ote/services/register.sql
* services: remove reqister.sql, the only query is also in user_service.sql
services: register, use email-exists? form user_service.sql
* services: admin, clear email token when user is deleted
* services: allow delete-user! by setting email to id instead of null
> 167723828 clear deleted user email  167723801 clear email token on admins delete user

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljs/ote/views/user.cljs
*  views: user, profile form, password required warning only if form modified
*  views: user, profile form :change-email-warning only if field is edited
* language: :change-email-warning updated FI string to all languages
> 167190672 user settings form, email change and password required warnings displayed only after field/form edited

- ote/src/cljs/ote/ui/main_header.cljs
* New amazing feature that does a thing.
* This feature does another thing.
* main view: set header user menu text as user fullname or email
> main view, set header user menu text as user fullname or email

- ote/src/cljs/ote/app/controller/login.cljs
- ote/src/cljs/ote/views/user.cljs
* views: user profile, clear state on init and no form after email change
* controller: login, event UserSettingsInit and dissoc :edit-response
* views: user, profile form, remove colon from email change info note
> 167190672 user profile form hide fields after email change

- ote/src/cljs/ote/views/user.cljs
* views: user profile, display a link to own services after email change
> views: user profile, display a link to own services after email change

- ote/src/cljs/ote/style/transit_changes.cljs
* transit-visualization-page: Overflow issues with ie
> Css changes to fix overflow issues with ie 11

- ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
* Changed existing feature.Stop time icons happen to align with the above change icons.
New layout from UX to avoid impression that the change-icon's change
count would apply only for the day below it. When it actually displays
the difference of the two days.
The problem is not just as bad for the view's other tables, because
there the change-icon row has more than just two indicators.
> views: transit-visualization, custom trip stop diff icon layout

- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/parking.cljs
- ote/src/cljs/ote/views/passenger_transportation.cljs
- ote/src/cljs/ote/views/rental.cljs
- ote/src/cljs/ote/views/terminal.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization/change_icons.cljs
- ote/src/cljs/ote/views/transport_service.cljs
- ote/src/cljs/ote/views/transport_service_common.cljs
* Removed all warning from transport service page by adding missing id's and removing empty error messages
* Added more space to sequence and date icons
* Moved time and sequence icons closer together when there is only two elements on the same row
> 161918381 move icon placement

- ote/src/cljs/ote/views/transit_visualization.cljs
* Fixes default icon not using icon-disabled color because of missing :color keyword.
Instead of adding :color, remove icon because it's according to UX spec
> views: transit-visualization, stops table default icon to none

- ote/src/clj/ote/services/admin.clj
- ote/src/clj/ote/tasks/pre_notices.clj
* services: pre-notices: email subject via java time, debug prints
* services: admin: java time prints to log-different-date-formations
> 167727513 pre notices email subject composed using java time, added debug prints

- ote/src/clj/ote/services/admin.clj
- ote/src/clj/ote/tasks/pre_notices.clj
- ote/src/cljs/ote/app/controller/admin_transit_changes.cljs
- ote/src/cljs/ote/views/admin/detected_changes.cljs
- ote/test/clj/ote/tasks/pre_notices_task_test.clj
* views: admin: button to manually trigger pre-notice email sending
controller: admin: SendPreNotices event for manual triggering
* services: admin: pre-notices/notify endpoint for manual email triggering
* services: pre-notices: email subject composition to dynamic, was static
> 167727513 pre notices email subject timestamp fixed, admin button to manually trigger pre-notice emails

- ote/src/cljs/ote/app/controller/admin_transit_changes.cljs
- ote/src/cljs/ote/views/admin/detected_changes.cljs
* views: admin: clear response of manual pre-notice sending on view load
* views: admin: simplify download single gtfs result notification hiccup
> Admin view clear pre-notice sending result on view load

- ote/src/cljc/ote/transit_changes.cljc
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/style/transit_changes.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* transit-visualization - stop section: stops are now sorted by date2 departure time.
* transit-visualization - map section:  map line colors where in wrong order.
> 167216897 stop order

- database/src/main/resources/db/migration/V1_166__alter-transit-stop-time-to-interval.sql
- ote/src/clj/ote/integration/export/gtfs.clj
- ote/src/clj/ote/services/admin.clj
- ote/src/clj/ote/services/routes.clj
- ote/src/cljc/ote/db/transit.cljc
- ote/src/cljc/ote/gtfs/transform.cljc
- ote/src/cljs/ote/app/controller/route/route_list.cljs
- ote/src/cljs/ote/app/controller/route/route_wizard.cljs
- ote/src/cljs/ote/views/admin/sea_routes.cljs
- ote/src/cljs/ote/views/route/route_list.cljs
- ote/src/cljs/ote/views/route/trips.cljs
* services: route: sort trips by stop time, fetch-sea-trips for reuse
* views: admin: spinner to accompany loading content placeholder message
* integration, views: endpoint export gtfs renamed to gtfs-sea
* route-id key renamed from id in various places
* views: route: unrestricted stop times except first departure
* views: route-wizard addtrip to use data model with trip or stop-time ids
* services: routes: trips and stop-times from new db tables
* db: specql define transit-trip and stop-time tables, route table id key
* gtfs: transform: sea route-id key renamed from id, renamed functions
gtfs: route: route-id key renamed from id and reuse db fetching
* db: alter sea transit stop time to interval and drop old types
> 167393604 sea transit route data model to unrestricted stop times 2

- ote/src/clj/ote/services/index.clj
- ote/src/clj/ote/services/routes.clj
- ote/src/cljs/ote/ui/main_header.cljs
* doctype to index.html template
* sea route front page: Sea routes were in cache when IE11 in use
* selecting "own services" from main header prevented "sea routes editor" to be selected from menu
> 168370140 e11 link and cache problems

- ote/src/cljs/ote/app/controller/route/route_wizard.cljs
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/route/trips.cljs
* form fields support in :time field for :on-blur event
* views: route: stop-time validation moved to :on-blur event
> 167393604 sea route stop-time validation moved to :on-blur event 

- ote/src/cljs/ote/views/route/trips.cljs
* views: route: trip stop list vertical-align top so warning doesn't jump 
When added, an invalid input warning element moves the input control,
which user is editing, up.
This commit aligns cell elements to top so that appearing warning
element only pushes following elements down,
instead of pushing preceding elements up.
> views: route: trip stop list vertical-align top so warning doesn't jump

- database/src/main/resources/db/migration/V1_168__feature_table.sql
- ote/project.clj
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/components/http.clj
- ote/src/clj/ote/services/routes.clj
- ote/src/cljc/ote/db/feature.cljc
- ote/src/cljs/ote/app/controller/common.cljs
- ote/src/cljs/ote/app/controller/route/route_list.cljs
- ote/src/cljs/ote/app/controller/route/route_wizard.cljs
- ote/src/cljs/ote/app/routes.cljs
- ote/src/cljs/ote/app/utils.cljs
- ote/src/cljs/ote/ui/main_header.cljs
- ote/src/cljs/ote/views/error/error_landing.cljs
- ote/src/cljs/ote/views/error_landing.cljs
- ote/src/cljs/ote/views/front_page.cljs
- ote/src/cljs/ote/views/main.cljs
* language: error landing page and maintenance break strings
* services
routes: :maintenance-break-sea-route flag checked from db
routes: endpoints wrapped to service state check handler
* db
cljc specql namespace for feature variation
create feature_variation table and feature_type
* views
route-wizard: load stops failure handler to common servererror
route-list: load routes failure handler to common servererror
main: error-landing page selection
error-landing: first WIP version
ote.sovellus height to 100vh to fill screen and put footer down
* controller: common: ServerError to redirect 503 to error-landing page
* ote: revert lein-figwheel to 0.5.13, connecting to browser not ok
> 168367747 dynamic db feature flag for sea route maintenance mode

- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/route/trips.cljs
* ui: form_fields: time field support for hour and min required indication
* views: trips: stop time error indication for missing input field value
> 168477239 sea route stop missing stop time error indication

- ote/src/clj/ote/services/admin.sql
- ote/src/clj/ote/services/routes.clj
- ote/src/cljs/ote/app/controller/route/route_wizard.cljs
- ote/src/cljs/ote/views/admin/sea_routes.cljs
* Sea route on-blur when save is clicked without clicking "off" from homepage input field
* Admin sea-route-list last active day when only added calendar date is given and no calendar rule
> 164826821 random fixes

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljs/ote/app/controller/route/route_wizard.cljs
- ote/src/cljs/ote/views/route/trips.cljs
* controller: route-wizard: clear stop chronology error if input cleared
* views: trips: tweak stop time error for non-chronological stop times
* language: :route-list-page :warn-check-stop-time initial versions
> 168477239 sea route stop missing stop time error indication v2

- ote/src/clj/ote/integration/export/gtfs.clj
- ote/src/clj/ote/services/routes.clj
- ote/src/cljs/ote/views/admin/sea_routes.cljs
- ote/src/cljs/ote/views/route/route_list.cljs
* reverts 206a154c3c5a83d9dca37d14601df7ea060815f0 i.e. revert endpoint url export/gtfs-sea to export/gtfs
> views, services: revert endpoint url export/gtfs-sea to export/gtfs

- ote/src/cljc/ote/transit_changes.cljc
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* Fixed situation where transit visualization page could not show stops or trips. Now we return first stop as first-common-stop if there is no common stops trips
> 168477136 - No stops or trips in transit visualization page

- database/src/main/resources/db/migration/R__GTFS_query.sql
- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization.cljs
* Transit visualization view: Fixed calendar traffic by adding detection date as a limit in used package list
* Transit visualization view: Fixed url when route was selected in /all/ mode
> 169115839 old routes have wrong data in calendar

- ote/src/clj/ote/components/http.clj
- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/services/transport_operator.clj
* IE11 caches operator and service data. This is now fixed using more aggressive no-cache-response function
> Modify no-cache-response and take it into use when editin operator or service

- ote/src/cljs/ote/views/rental.cljs
* service view: Could not make service hours and exceptions to work without modal so here it is added back in use. We'll do another try in the future.
> 168894470 Take pick-up-location service hour modal back in use

- ote/src/cljs/ote/views/service_search.cljs
* service-search: reduce autocomplete list height to 300px
> 169839070 - service-search autocomplete

- ote/src/cljs/ote/app/controller/service_search.cljs
- ote/src/cljs/ote/views/service_search.cljs
* service-search: chipinputs doesn't work well with ie11 so we changed them to multiselect dropdown lists
> 169839070 ie11 autocomplete

- database/src/main/resources/db/migration/V1_180__add_parent_id_for_service.sql
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/admin.clj
- ote/src/clj/ote/services/admin.sql
- ote/src/clj/ote/services/places.clj
- ote/src/clj/ote/services/places.sql
- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/services/transport.sql
- ote/src/cljs/ote/ui/form_fields.cljs
- ote/src/cljs/ote/views/own_services.cljs
- ote/src/cljs/ote/views/transport_service_common.cljs
* When user edits published services they are duplicated in database and duplicated service is moved to validation process and original is staying in published state.
* Added parent-id to transport-service table
* Added new sproc to handle copying interfaces from child service to parent service
> 170258400 duplicate public service

- database/src/main/resources/db/migration/V1_182__change_detection_route_unique_idx.sql
* detected-route unique index
* Old index prevented same route be twice in the table when it did come from two different agency. Now duplicate check is a bit different and we allow same route-hash-id be in the table with same package-id if route-id remains different. This will allow two agencies to drive same trip with same route-hash-id but with different calendar days.
> 170840682 Change detected-route unique index

- database/src/main/resources/db/migration/R__GTFS_query.sql
- database/src/main/resources/db/migration/V1_183__new_index_gtfs_route_hash.sql
- ote/src/clj/ote/integration/import/gtfs.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
* Add transport-service-id to gtfs-date-hash calculations.
* Speed up trip queries by using transport-service-id
> 170840682 Speed up trip queries by using transport-service-id

- ote/src/clj/ote/transit_changes/change_history.clj
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* Fix calendar change counts when :no-change is selected from calendar change list
* Change change history date when gtfs package is loaded from admin form
> 171015606 transit-visualization Fix calendar

- database/devdb_rewrite_db_template.sh
- database/devdb_simple_migrate.sh
- database/src/main/resources/db/migration/V1_185__interface_download_status_service.sql
- ote/src/clj/ote/integration/import/gtfs.clj
- ote/src/clj/ote/services/transit_changes.clj
- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/tasks/gtfs.clj
* external interfaces: Remove cascade delete from interface -> download status to prevent loss of download history
* external interface download history: Add service-id to the table to make history independent of interface.
> 170094026 preserve download history

- ote/src/clj/ote/netex/netex.clj
- ote/src/cljc/ote/gtfs/parse.cljc
- ote/src/cljc/ote/gtfs/transform.cljc
- ote/src/cljs/ote/views/route/route_list.cljs
* export gtfs: When SeaRae trip had two or more calendar dates added trip-id was duplicated in exported gtfs. This is now fixed by adding trip twice with different trip-id.
> 171718301 duplicate trip-id

- ote/src/clj/ote/transit_changes/detection.sql
* Fixed gtfs-date-hash query: Add missing dates to gtfs-date-hash query by adding left join to query section where no package is found
> 171808772 - Friday compared to Saturday in change detection

- database/src/main/resources/db/migration/R__GTFS_query.sql
- ote/project.clj
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/tasks/util.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
* Create new sql query to get change detection routes
* Deleted interfaces must be filtered out from change detection. To enable this, we needed new queries to get gtfs packages
> 171809348 - Use only packages from valid interfaces in newest change detection

- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/tasks/util.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/test/clj/ote/transit_changes/detection_integration_test.clj
* To fix detection history we need to use given detection date in all detection algorithms instead of current date.
> Pass detection/analysis date to rest of the detection algorithms

- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization/transit_visualization.cljs
* transit-visualization page: Fix route change filtering for old change detections
* transit vizualization page: Added changed route count and unchanged route count under the route list to help investigate problems. Might be removed later because it won't help so much the users than the testers and developers.
> 171894277 transit vizualization - route change filtering

- database/src/main/resources/db/migration/R__GTFS_query.sql
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
* detection: Pass detection date to stored procedure which gets 3 years of routes for detection
> 171993432 - pass detection date to route sproc

- ote/src/clj/ote/services/transit_changes.sql
*  transit-changes: upcoming-changes query fixed to return correct value when something is downloaded from interface
> 171620402 transit-changes: update upcoming-changes query

- database/src/main/resources/db/migration/V1_186__add_transit_change_over_night_updates.sql
- ote/src/clj/ote/services/admin.clj
- ote/src/clj/ote/services/transit_changes.sql
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/cljs/ote/app/controller/admin_transit_changes.cljs
- ote/src/cljs/ote/ui/table.cljs
- ote/src/cljs/ote/views/admin/detected_changes.cljs
* When transit changes were analyzed every night we were removing data that could be needed later. Now added new columns to store this changing transit changes data.
* new columns to store current added-changes, removed-changes, no-transit-changes, changes
> 171620402 - transit changes current stats

- database/src/main/resources/db/migration/R__GTFS_query.sql
* detection: Changed how we search all routes for service when detecting changes. Which fixes detecting same route as a new route again.
> 172239469 - Fix route search for detection

- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/services/transport.sql
* Fix gtfs_package and download-status tables:
When service is modified and validated external-interface-descriptions gets new id:s. Those ids are now passed to gtfs_package table and to external-interface-download-status table.
> 172408308 - fix interface ids 

- database/src/main/resources/db/migration/R__GTFS_query.sql
* Fix detection route query, When route has multiple headsigns and route-hash-id is type of short-long
> 172758633 - Fix detection route query

- ote/project.clj
- ote/src/clj/ote/services/operators.sql
- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
- ote/src/clj/ote/util/db.clj
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* transit-visualization: Fixed trip fetch. It used wrong package to get trips. Now changed to those packages that were present when detection was made.
* There were also another bug in these situations where service has multiple interfaces. Detection used to find same date has twice which ended up adding non change to route changes list. Those non-changes are now filtered out.
> 172691911 trips wont show up

- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/services/transport.sql
* Edit transport service: When service is modified all interface id:s changes. Those new id's must be updated to package_gtfs table to ensure that change detection finds correct packages. When updating interface id:s there were filttering problem. Sql query didn't filter out json type interfaces and those id's were used in package_gtfs table.
Now fixed
> 173657270 Filter wrong data-contents off from child-parent interfaces update

- database/src/main/resources/db/migration/V1_189__origina_interface_id.sql
- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/services/transport.sql
* modify service - publish service: When transport service is moved to validation we make a duplicate of it. This process affects on gtfs_package table. To fix those package download issues, we need to update old interface id's with new one. This fixes this issue completely.
> 173657270 - Save interface original id to db when editing service data

- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
* transit-visualization page: Fix missing change detected date from no-traffic changes
> 172408308 - Fix missing change detected date

- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
* transit change detection: Fixed db queries for services with multiple interfaces and identical traffic from all.
> 172691911-Fix detection queries for services with multiple interfaces

- database/src/main/resources/db/migration/V1_190__mark_interfaces_removed_for_packages.sql
- ote/src/clj/ote/services/admin.clj
- ote/src/clj/ote/services/transit_visualization.clj
- ote/src/clj/ote/services/transit_visualization.sql
- ote/src/clj/ote/services/transport.clj
- ote/src/clj/ote/services/transport.sql
- ote/src/clj/ote/services/users.clj
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/clj/ote/transit_changes/detection.clj
- ote/src/clj/ote/transit_changes/detection.sql
- ote/src/cljs/ote/app/controller/transit_visualization.cljs
- ote/src/cljs/ote/views/transit_visualization/gtfs_package_info.cljs
- ote/test/clj/ote/db/service_generators.clj
- ote/test/clj/ote/services/transport_test.clj
* In change detection wasn't possible to identify which packages were downloaded from deleted interfaces and which weren't. Now gtfs_package table contains interface-deleted? boolean which is used when todays change-detection is run.
It won't affect if change detection is run in the past.
* Add interface-deleted? column to gtfs_package table
> 174987587 mark interface deleted

- ote/project.clj
- ote/src/cljs/re_svg_icons/core.cljs
- ote/src/cljs/re_svg_icons/feather_icons.cljs
inline tatut/re-svg-icons:feather-icons to project to avoid NoClassDefFoundError in build process
Leiningen plugins cannot be set to ignore transitive dependencies and since re-svg-icons isn't a publically available JAR, the only option left is to include the relevant code directly into the project.
* feather icon dependency causing build errors in CI
> inline feather icons dependency

- ote/src/cljs/ote/app/controller/front_page.cljs
- ote/src/cljs/ote/style/topnav.cljs
- ote/src/cljs/ote/ui/main_header.cljs
* collapsible two-level menu for mobile layout
---
Screenshot in three parts:
1. What it was like before (logged in)
2. What it is now when collapsed (logged out)
3. What it is now when expanded fully (logged out)
> add collapsible two-level menu for mobile layout

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljs/ote/views/admin/monitor.cljs
- ote/src/cljs/ote/views/own_services.cljs
* Add Finnish text "Lataa liikkumispalveluiden tarjoajien tiedot CSV:nä" to translations.
* As Swedish and English translations for this button text are missing, they have the Finnish text preceded by a TODO message to translate them into the corresponding target language.
* Use primary button type for CSV data download button in Monitor view.
> Use primary button type for CSV data download button in Monitor view.

- ote/resources/public/language/en.edn
- ote/resources/public/language/sv.edn
* Use button text "Lataa liikkumispalveluiden tarjoajien tiedot CSV:nä" in Monitor view in Swedish and English as well.
> Use button text in Finnish as is in Swedish and English translations.

- ote/src/cljs/ote/views/own_services.cljs
- ote/src/cljs/ote/views/pre_notices/listing.cljs
- ote/src/cljs/ote/views/service_search.cljs
* Use feather-icons/trash-2 for delete transport service button in Transport service catalog.
* Use feather-icons/trash-2 for delete transport service button in Own transport services.
* Use feather-icons/edit for edit transport service button in Own transport services.
* Use Feather icons for edit and delete buttons in Report changes in regular scheduled passenger transport view.
> FINAP-14/more buttons and icons

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/cljs/ote/style/base.cljs
- ote/src/cljs/ote/style/topnav.cljs
- ote/src/cljs/ote/ui/common.cljs
- ote/src/cljs/ote/ui/main_header.cljs
- ote/src/cljs/ote/views/footer.cljs
- ote/src/cljs/ote/views/service_viewer.cljs
* even more generalized `linkify` component which detects external links, renders an _(optional)_ external link icon next to the link and adds an on-click nagger if the URL is not a known good URL
---
> FINAP-22/common link interceptor component for all links

- ote/src/clj/ote/middleware/throttler.clj
- ote/src/clj/ote/services/login.clj
* throttle failed login attempts using (almost) exponential delay, limited to a maximum wait of one minute
---
Inspector screenshot shows the behavior of this piece of code the best:
> FINAP-32/implement Ring middleware for throttling failed login attemps

- ote/src/cljs/taxiui/views/pricing_details.cljs
Division between prices is now daytime, nighttime and weekends.
> FINAP-60/more generic labels to avoid issue where not all taxi drivers have exactly the same schedules

- ote/src/cljs/taxiui/views/components/devtools.cljs
- ote/src/cljs/taxiui/views/main.cljs
Visible in localhost and test.
> FINAP-64/add simple warning header to the page to differentiate test environments from production

- database/src/main/resources/db/migration/V1_193__add_constraints_for_columns_used_for_input_data.sql
* Add constraints to database columns used to store input data.
* Constraints have been defined only for columns that are not empty, that is, they contain some data.
> FINAP-45/Add constraints for columns used for input data

- ote/resources/public/language/fi.edn
- ote/src/clj/ote/services/taxiui_service.clj
- ote/src/cljc/ote/transit.cljc
- ote/src/cljs/taxiui/app/controller/pricing_details.cljs
- ote/src/cljs/taxiui/styles/pricing_details.cljs
- ote/src/cljs/taxiui/views/components/loader.cljs
- ote/src/cljs/taxiui/views/components/pill.cljs
- ote/src/cljs/taxiui/views/pricing_details.cljs
* operating areas are now stored to database; existing ones are cleared if they have been removed, new ones will be saved as expected
* loader spinner now can have localized context specific helper texts below it, just to calm the users a bit
> FINAP-60/operating area databinding

- database/src/main/resources/db/migration/R__list_taxi_pricing_statistics.sql
- ote/project.clj
- ote/resources/public/language/fi.edn
- ote/src/clj/ote/services/taxiui_service.clj
- ote/src/clj/ote/services/taxiui_service.sql
- ote/src/cljs/taxiui/views/components/formatters.cljs
- ote/src/cljs/taxiui/views/stats.cljs
Adds primary operating areas to the table, and a two-level sorting to enable sort for both name and operating areas column.
> FINAP-61/add primary operating areas to statistic view results

- ote/src/cljs/taxiui/app/controller/pricing_details.cljs
As it says on the title, noticed this while fiddling around with statistics view.
> FINAP-60/move tuck fx to load refreshed data only after save is successful to avoid desyncing UI

- ote/resources/public/language/fi.edn
- ote/src/clj/ote/services/taxiui_service.clj
- ote/src/clj/ote/services/taxiui_service.sql
- ote/src/cljs/taxiui/app/controller/stats.cljs
- ote/src/cljs/taxiui/views/components/forms.cljs
- ote/src/cljs/taxiui/views/stats.cljs
Also uses `goog.functions.debouncer` to prevent hammering the API character by character.
> FINAP-62/add filtering results by company name to stats view

- ote/src/clj/ote/services/taxiui_service.sql
Previous logic, upon further inspection, didn't really make sense.
> FINAP-61/fix date range comparison by comparing only the filter interval

- database/src/main/resources/db/migration/R__list_taxi_pricing_statistics.sql
Seems the function overloads turned ambiguous in test environment at least, so need to add params.
> FINAP-61/Add params to function drop to disambiguate which function should be removed

- ote/src/cljs/ote/views/footer.cljs
* Swedish "Dataskydd" link points now to Finnish "Tietosuojaseloste" page.
* English "Privacy policy" link points now to Finnish "Tietosuojaseloste" page.
> Finap 105/change link of swedish and english privacy policies

- ote/src/cljs/taxiui/views/components/forms.cljs
- ote/src/cljs/taxiui/views/pricing_details.cljs
- ote/src/cljs/taxiui/views/stats.cljs
Lets keep pushing those pixels. No screenshots this time, things are just...better :)
- when user clears area filter, it now equates to "all areas" search which is more intuitive
- Stats page are selector was broken because bottom padding pushed the element off axis; this is now fixed
> FINAP-64/more layout finetuning

- ote/src/cljs/ote/app/state.cljs
- ote/src/cljs/taxiui/app/routes.cljs
- ote/src/cljs/taxiui/styles/front_page.cljs
Rollback the local storage based app state to fix multi tab support for good.
The original reason for having a local storage backed state isn't valid anymore anyways; there's not actual state we want to share between the two apps and authentication is in cookies, so everything still works as expected.
> FINAP-121/multi tab support

- ote/src/clj/ote/services/transport_operator.clj
Fixes incorrect checking of clause vector and an earlier misunderstanding in regards to what `:admin?` really means.
> bugfix for can't remove users from org

- database/src/main/resources/db/migration/V1_198__link_netex_conversion_to_package.sql
- ote/src/clj/ote/netex/netex.clj
This needs to run in an actual environment with Chouette for a night so that we'll see how it behaves. Local testing is difficult because of Chouette itself.
> first draft of linking and reporting netex conversion errors as part of GTFS import errors

- ote/src/clj/ote/integration/import/gtfs.clj
Chouette will report this separately anyways, plus it is considered noise.
> remove unnecessary extra file reporting

- ote/src/clj/ote/authorization.clj
- ote/src/clj/ote/integration/import/gtfs.clj
- ote/src/clj/ote/integration/report.clj
- ote/src/clj/ote/integration/report.sql
- ote/src/clj/ote/main.clj
- ote/src/clj/ote/netex/netex.clj
- ote/src/clj/ote/services/transit_changes.clj
- ote/src/clj/ote/services/transit_changes.sql
- ote/src/clj/ote/tasks/gtfs.clj
- ote/test/clj/ote/integration/import/gtfs_test.clj
- ote/test/clj/ote/netex/netex_test.clj
Plumbing for sending GTFS/NeTEx validation reports as scheduled emails after nightly imports. Currently only logs the sends so that we can scope out how many emails we'd end up producing.
> Finap 39/email reports

- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
Especially the Swedish translation misguided users to add alternate websites, eg. Facebook pages as external interfaces instead of actual APIs.
> Improve translations for external interfaces

- ote/src/clj/ote/services/transit_changes.clj
This bug was caused by earlier macro unrolling, which had its own magic for handling this.
> Fix API not sending out properly serialized response

- aws/ansible/jenkins/tasks/leiningen.yml
The build was broken because JDK on bastion has been updated but tooling wasn't, now everything's fine again. Of course these Ansible scripts are out-of-date anyway and the actual change was done with sudo+curl, but at least this way there's a slight change someone will see this was updated.
> leave a trace about updating Leiningen from 2.7.1 (!!) to 2.9.10

- ote/src/clj/ote/services/index.clj
- ote/src/clj/ote/services/taxi_index.clj
The script is active only in production to avoid messing with the collected data.
> FINAP-167: update matomo script to use Fintraffic Cloud's specific script

- ote/src/cljs/ote/ui/common.cljs
- ote/src/cljs/ote/views/service_viewer.cljs
Add simple link tag to track whether someone's actually clicked the external API homepage link.
> Add Matomo analytics tag to service API link

- ote/src/cljs/ote/app/routes.cljs
This probably made sense back in 2019 when this was originally created.
> disable manual piwik/matomo event generation to prevent double navigation event tracking

- ote/src/clj/ote/integration/export/netex.clj
TIS VACO integration reuses the conversion result publishing functionality
> make NeTEx export functionality rely on TIS VACO feature flag instead

- aws/ansible/environments/staging/group_vars/ote/vars
- ote/config.edn
- ote/resources/public/language/en.edn
- ote/resources/public/language/fi.edn
- ote/resources/public/language/sv.edn
- ote/src/clj/ote/services/external.clj
- ote/src/clj/ote/tasks/gtfs.clj
- ote/src/cljs/ote/views/admin/interfaces.cljs
- ote/src/cljs/ote/views/transport_service/transport_service_common.cljs
These are for data input, logic underneath remains unchanged. In fact cunning users have already been able to set the format as whatever they please, the autofill dropdown has just held their hands well enough that they haven't.
> FINAP-218/add extended formats support for external interfaces

- ote/src/clj/ote/integration/tis_vaco.clj
These versions are not needed anymore
> TIS-602/remove versioning from TIS VACO integration specifics

- aws/ansible/podman.yml
https://solita.atlassian.net/issues/FINAP-8
Playbook will Build and deploy Podman Container napotedb11 as a persistent systemd service, that can handle reboots. 
Playbook will also rebuild and redeploy existing systemd service, that runs a Podman container named napotedb11
- Running container as system service 
- Service running in Jenkins' namespace
- Config can be found in /etc/systemd/system/container-napotedb11.service
> ansible playbook for podman container & postgre as systemd service

- ote/src/cljc/ote/util/tis_configs.cljc
netex.entur configuration requires at least codespace and maximumErrors to be set
> add missing default values to netex.entur configuration
